#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Lithuanian (Lietuvių)####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Vartotojas"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Slaptažodis"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Vykdyti"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Viso"
		)
	dictionary["fromlabel"] = (
		"From",
		u"Nuo"
		)
	dictionary["tolabel"] = (
		"To",
		u""
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Kaina"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Apibūdinimas"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Taip"
		)
	dictionary["nolabel"] = (
		"No",
		u"Ne"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Redaguoti"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Šalinti"
		)
	dictionary["searchlabel"] = (
		"Search",
		"Rasti"
		)
	dictionary["resetlabel"] = (
		"Reset",
		"Perkrauti"
		)
	dictionary["movelabel"] = (
		"Move",
		"Kelti"
		)
	dictionary["unitlabel"] = (
		"Unit",
		"Vienetas"
		)
	dictionary["onlabel"] = (
		"on",
		"*"
		)
	dictionary["namelabel"] = (
		"Name",
		"Vardas"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"Užbaigta atviro kodo veterinarinės praktikos vadybos programa"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"Šią programą galite laisvai keisti ir redaguoti pagal savo poreikius"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"*"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Laikas"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Operacijos"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Operating"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"Konsultacija"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Vet.gydytojas"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Gyvūno aprašas"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Apie šeimininką"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Išrašas"
		)
	dictionary["problemlabel"] = (
		"Problem",
		u"Problema"
		)
	dictionary["noteslabel"] = (
		"Notes",
		"Pastabos"
		)
	dictionary["planlabel"] = (
		"Plan",
		"Planas"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Vartotojas ištrintas"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Keisti Log-ą"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Pozicija"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Data"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Neteisingas laikas"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Turinys"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Pakartoti"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Joks"
		)
	
	##Menus
	
	dictionary["clientmenu"] = (
		"&Clients",
		u"&Klientai"
		)
	dictionary["appointmentsmenu"] = (
		"&Appointments",
		u"&Paskyrimai"
		)
	dictionary["medicationmenu"] = (
		"&Medication",
		u"&Vaistai"
		)
	dictionary["proceduresmenu"] = (
		"&Procedures",
		u"&Procedūros"
		)
	dictionary["lookupsmenu"] = (
		"&Lookups",
		u"&Paslėptukai"
		)
	dictionary["formsmenu"] = (
		"&Forms",
		u"&Formos"
		)
	dictionary["staffmenu"] = (
		"&Staff",
		u"&Budėjimai"
		)
	dictionary["settingsmenu"] = (
		"Se&ttings",
		u"Nustatymai"
		)
	dictionary["helpmenu"] = (
		"&Help",
		"&Pagalba"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Visas"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Sterilizuota"
		)
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Įrašyti klientą", u"Naujo kliento įrašas")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Surasti klientą", u"Surasti kliento ir gyvūno įrašus")
		)
	dictionary["viewappointmentsmenu"] = (
		("Todays Appointments", "View todays appointments"),
		(u"Šiandienos paskyrimai", u"Žiūrėti šiandienos paskyrimus")
		)
	dictionary["viewoperationsmenu"] = (
		("Todays Operations", "View todays operations"),
		(u"Šiandienos operacijos", u"Žiūrėti šiandienos operacijas")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Redaguoti vartotoją", u"Įrašyti ir redaguoti Evette vartotojus")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Redaguoti etatus", u"Redaguoti etatą")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Redaguoti vaistus", u"Redaguoti vaistus")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Redaguoti skiepus", u"Redaguoti skiepus")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Redaguoti procedūras", u"Redaguoti procedūras")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Redaguoti spalvą", u"Redaguoti spalvą")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Redaguoti veisles", u"Redaguoti veisles")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Redaguoti rūšis", u"Redaguoti rūšis")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Redaguoti formas", u"Redaguoti formas")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Redaguoti nustatymus", u"Redaguoti nustatymus, skirtus šiai praktikai")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Atsitiktiniai duomenys", u"Sukurkite atsitiktinius duomenis, kad bandytumėte su")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Atstatyti duomenų bazę", u"Visiškas Evette duomenų bazės nustatymas. Būkite atsargus!")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Pagalba", u"Gaukite Evette naudojimo pagalbą")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Apie", u"Informacija apie Evette")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u" Įrašyti klientą ", u"Naujas kliento įrašas")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u" Surasti klientą ", u"Suraskite klientus ir jų gyvūnus")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u" Šiandienos paskyrimai ", u"Žiūrėti šiandienos paskyrimus")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u" Šiandienos operacijos ", u"Žiūrėti šiandienos operacijas")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Naujas klientas"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Titulas"
		)
	dictionary["clientforenameslabel"] = (
		"First Name",
		u"Vardas"
		)
	dictionary["clientsurnamelabel"] = (
		"Last Name",
		u"Pavardė"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Adresas"
		)
	dictionary["clientpostcodelabel"] = (
		"Post Code",
		u"Paštas"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Namų tel."
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Mobilus tel."
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Darbo tel."
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"El. paštas"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Įrašyti naują gyvūną"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Redaguoti gyvūno įrašą"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Naikinti gyvūno įrašą"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Atnaujinti gyvūnų įrašą"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Įrašyti gyvūnui paskyrimą"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Balansas"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Detali kaina"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"išsaugoti kliento įrašo pakeitimus"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Šis kliento įrašas neišsaugojo pakeitimų, ar tikrai uždaryti?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Trinti gyvūną?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Atnaujinti sąskaitą"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u" Neseni veiksmai", u"Reguliuoja rodytų sąskaitos veiksmų datos diapazoną")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Nepasirinkti einamosios sąskaitos veiksmo, išvalti kainą ir apibūdinimo įėjimus"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Pateikite pakeitimus išrinktai sąskaitai"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Pašalinkite išrinktą sąskaitą"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Naujas gyvūnas"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Savininkas"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Redaguoti gyvūno savininką"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Vardas"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Lytis"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Rūšis"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Veislė"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Spalva"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Gimimo data"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Integrinio grandyno Nr."
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["animalneuteredtooltip"] = (
		"Check if the animal is neutered",
		u"Žymėti gyvūnas neatpažintas"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Sukurkti gyvūno įrašo atspausdinimą"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Sukurkite formą naudodamas šiuos gyvūnų aprašymus"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Paskyrimai"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Įrašyti gyvūnui paskyrimą"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Redaguoti paskyrimą"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Atnaujinti paskyrimų sąrašą"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Trinti pasirinktą paskyrimą"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Sukurti paskyrimų atspausdinimą"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Vet Formos", u"Redaguoti vet formas šiam paskyrimui")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Paskyrimų detalės"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Vakcinacijos"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Išsaugoti bet kokius pakeitimus, padarytus šio gyvūno įraše"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Šis gyvūno įrašas neišaugotas, ar tikrai norite uždaryti?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Pašalinti paskyrimą?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Perkrauti skiepus"
		)
	dictionary["animalvaccinelabel"] = (
		" Vaccine: ",
		u" Vakcina: "
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Atlikta: "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u" Sekanti: "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Pašalinti vakcinas"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Pateikti šį skiepijimą"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Jūs esate įsitikinęs, kad norite pašalinti šį skiepijimą?"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Ser.Nr.: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Paskyrimas"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Operacija"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Jei šis paskyrimas yra specifiniam veterinarui, įveskite veterinaro vardą čia"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Atnaujinti paskyrimų sąrašą"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Paskyrimo priežastis"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Paskyrimo laikas"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Check this box if you would like to book an operation"),
		(u"Operacija?", u"Tikrina šią vietą, jei norėtumėte rezervuoti operaciją")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Pateikti paskyrimą"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Naikinti paskyrimą"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Statusas"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"Neatvyko"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Laukti"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Su Vet.gydytoju"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Baigti"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Redaguoti savininką", u"Redaguoti kliento įrašą")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Redaguoti gyvūną", u"Redaguoti gyvūno įrašą")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Paskyrimai"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Operacijos"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"Susitikimo laikas yra anksčiau, negu klinika atsidaro!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"Susitikimo laikas yra vėlesnis, negu klinika užsidaro!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Neteisingas laikas - turi būti HH:MM!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Rasti klientą"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Last Name",
		u"Vardas"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Tel.Nr."
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Adresas"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Post Code",
		u"Paštas"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"El. paštas"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Valyti", u"Valyti viską")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Rasti", u"Įvykdykite paiešką")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"Redaguoti surastus klientų įrašus"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Trinti surastus klientų įrašus"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Vardas"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Lytis"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Rūšis"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		"Veislė"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Integrinio grandyno Nr."
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Redaguoti surasto gyvūno įrašą"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Trinti surasto gyvūno įrašą"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Kvitas - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Ar trinti kvitą?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Išvalyti užmokesčius"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Sumokėta"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Pateikite užmokestį"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Sumokėta"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Konfigūracijos rinkmena, nesurasta! Sukurti dabar?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Evette rinkmena, nesurasta! Sukurti dabar?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Negaliu prisijungti prie duomenų bazės serverio! Prašom patikrinti, kad programa įdiegta ir paleista. Gal Jūs norėtumėte sureguliuoti savo vietinius nustatymus?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"Negaliu nustatyti Evette duomenų bazės vietos! Gal Jūs norėtumėte sukurti tokią dabar?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Konfigūracijos rinkmena sukurta"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Evette aplankas sukurtas"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"Duombasė IP Adresas"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Duombasė vartotojas"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Duombasė slaptažodis"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Negaliu sukurti duomenų bazės, prašom tikrinti savo MySQL serverio konfigūraciją!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Duomenų bazė sukurta!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Prisijungti"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Redaguoti paslėptuko spalvas"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Redaguoti paslėptuko rūšis"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Redaguoti paslėptuko veisles"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Atnaujinti sąrašą"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Ištrinti paslėptukus"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Pateikti paslėptukus"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"Toks paslėptukas jau egzistuoja, vėl tai dėti beprasmiška!"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Pavadinkite paslėptuką"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Ar tikrai pašalinti paslėptuką?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Redaguoti vaistus"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Refresh Medication List",
		u"Atnaujinti vaistų sąrašą"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Trinti vaistą"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Partija #"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Sukurkti pranešimą, parodyti visą šios partijos apyvartą"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Spausdinti sandėlio sąrašą"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		"Apyvarta "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"Ar tikrai trinti "
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Ar perrašyti šį vaistą?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Apyvarta pagal partijos numerį "
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Galioja"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Atnaujinti vaisto aprašus"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Trinti vaisto apyvartą"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Apyvarta"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Ar perrašyti šią apyvartą?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Ar ištrinti šią apyvartą?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Atnaujinti vaisto aprašus"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Atnaujinti paiešką"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Einamoji partija"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Vieneto kaina"
		)
	
	##Weekdays
	
	dictionary["monday"] = (
		"Monday",
		"Pirmadienis"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		"Antradienis"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Trečiadienis"
		)
	dictionary["thursday"] = (
		"Thursday",
		"Ketvirtadienis"
		)
	dictionary["friday"] = (
		"Friday",
		"Penktadienis"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Šeštadienis"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Sekmadienis"
		)
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Radaguoti procedūras"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Atnaujinti procedūrų sarašą"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Trinti procedūrą"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"Pavadinkite procedūrą!"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"Ar tikrai redaguoti šią procedūrą?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"Ar tikrai trinti šią procedūrą?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Atsitiktiniai duomenys"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"Klientų Nr."
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"Gyvūnų Nr."
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"Paskyrimų Nr."
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"Operacijų Nr."
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"Vaistų Nr."
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"Paskyrimai"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Operacijos"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Vaistai"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Generuoti atsitiktinius duomenis"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Dirbančio vardas"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Darbas nuo"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Dirba iki"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Darbo laikas"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"HTML peržiūra"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"HTML peržiūra"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Lietuvių"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Redaguoti Vet Formas"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Redaguoti finansus"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Rodyti įrankinę"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		"View Changelogs"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Redaguoti nustatymus"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		"Personalo narys"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Trinti vartotoją"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Paskyrimai"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Vaistai"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Paslėptukai"
		)
	dictionary["formslabel"] = (
		"Forms",
		"Formos"
		)
	dictionary["userslabel"] = (
		"Users",
		"Vartotojai"
		)
	dictionary["misclabel"] = (
		"Misc",
		"Misc"
		)
	dictionary["tickalllabel"] = (
		"Check All",
		u"Žymėti viską"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"Leisti vartotojams panaudoti VISUS sistemos įpatumus. Elkitės atsakingai!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"Ar perrašyti šį vartotoją?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"Ar trinti šį vartotoją?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Laikas nuo"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		"Laikas iki"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Veikimas"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Darbuotojų reziumė"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Dienos planas"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Įrašykite veterinaro vardą!"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"Vet.gyd.negali baigti nepradėjęs!"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This vet cannot be in two places at once!",
		u"Šis veterinaras negali būti dviejose vietose tuo pat metu!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		"Redaguoti vakcinacijas"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		"Vakcinos"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Atnaujinti vakcinacijų sąrašą"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		"Delete the selected vaccination"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		"Print a list of your current stock"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		"Are you sure you want to delete this vaccination?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		"Are you sure you want to overwrite this vaccination?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		"Refresh the details of this vaccination"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		"Delete this vaccination movement"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		"Are you sure that you want to edit this movement?"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		"Are you sure that you want to delete this movement?"
		)
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		"Vet Formos"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Paskyrimų istorija"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Paskyrimų detalės"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		"Vaist"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		"Vakc"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		"Proc"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		"Rank"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		"Delete the selected item from the receipt"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		"Mark this appointment as complete and close"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		"Save any changes made to this vet form"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		"Receipt Item"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		"Are you sure you want to delete this receipt item?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		"Clear the \"Contains\" entry"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		"Refresh the medication list"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		"Enter the number of units that you are dispensing here"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		"Instructions"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		"Enter instructions on how to administer this medication here"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		"Print a label for this medication"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		"Enter the batch number here"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		"Refresh the vaccination list"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		"Refresh the procedures list"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"Jūs turite apibūdinti!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Žiūrėti paskyrimus"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Žiūrėti operacijas"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"Pažymėti paskyrimą su vet.gyd."
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Rinktis vet.gyd."
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Atlikti veterinaro vizitą paskyrimui"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Pažymėkti šį paskyrimą neatvykęs"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Pažymėti paskyrimą užbaigtu"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Redaguoti klientą"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Redaguoti kliento įrašą (kaip galintys užmokėti savo sąskaitą)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		"Vet.gyd." #error if u"" in viewappointments  #572 		self.datetimewindow.SetPage("<c
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Paskyrimo paieška"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Paskyrimo paieška", u"Surasti paskyrimą")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Gyvūno vardas"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Priežastis"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Žiūrėti operacijas"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"YYYYMMDD"
		)
	dictionary["currency"] = (
		"&pound;",
		"Lt "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Pašto išsiuntimas", u"Surinkti klientų sąrašą ryšio palaikymui ")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Pašto išsiuntimas"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Bet kokia vakcina"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Bet kokia rūšis"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Negyvas"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Mirties priežastis"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Įtraukti negyvus"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Sukurti paskyrimą", u"Sukurti paskyrimą vakcinacijai")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"Sukurti CSV rinkmeną", u"Sukurti ir išsaugoti CSV rinkmeną diske. Pašto siuntimų sukūrimui gali būti panaudojama daugelis tekstų rengyklių")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"CSV rinkmenos išsaugotos į"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Versijai vieta nesurasta, sukurti dabar?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"Ar pamėginti paleisti evette"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"duomenų bazės versija"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Gal Jūs norėtumėte patobulinti savo duomenų bazę?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		"Ar tikrai perkrauti visas lenteles? VISI DUOMENYS BUS PRARASTI!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"Visos lentelės perkrautos!"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Pridėti darbuotojus?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Vet.gyd."
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Seselės"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Kiti"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Kitas mėnuo"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Buvęs mėnuo"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Atgal į kalendorių"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Pridėti darbuotoją į dienų budėjimo grafiką"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Trinti budėjimo grafiką"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Pateikti budėjimo grafiką"
		)
	dictionary["vetpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet
		"Vet",
		u"Vet"
		)
	dictionary["vetnursepositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet nurse
		"Nurse",
		u"Seselės"
		)
	dictionary["managerpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a manager
		"Manager",
		u"Ūkvedys"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		"Gaila,bet įvyko kita klaida"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Redaguoti dienoraštį", u"Redaguoti dienoraštį")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Redaguoti dienoraštį"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Iki"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Temos turinys"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Pastaboje:"
		)
	dictionary["showremovedlabel"] = (
		"Include removed?",
		u"Įrašyti ištrintus?"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Tema"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Pastabos"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Ištrinti"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Sąsaja"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Klientas"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Gyvūnas"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Atidaryti įrašą, susietą su šia dienoraščio pastaba"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Dienoraščio pastabos"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"Ar tikrai ištrinti šią dienoraščio pastabą?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"Be temos"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Sukurti dienoraščio pastabą, susietą su šiuo įrašu"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Sukurti dienoraščio pastabą"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Redaguoti dienoraščio pastabą"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Trinti dienoraščio pastabą"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Atnaujinti dienoraščio pastabas"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Valyti dienoraščio filtrus"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade then try again",
		u"Jūs bandote prisijungti su pasenusiais kliento duomenim, prašom atnaujinti ir bandyti dar kartą"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Įrašyti į dienoraštį"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Redaguoti dienoraštį"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Trinti iš dienoraščio"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Dienoraštis"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Licencija", u"Žiūrėti šios programos licenciją.")
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Asocijuoti rinkmeną", u"Redaguoti išorines paraiškas, asocijuotas su pridėtomis rinkmenomis")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Licencija"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Apie"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Pridėtos rinkmenos"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Ar tikrai trinti šią rinkmeną?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Pridėti naują išorinę rinkmeną prie šio įrašo"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Atnaujinti rinkmenos apibūdinimą"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Trinti rinkmeną"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Išsaugoti rinkmeną diske"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Asocijuoti rinkmeną"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Ištęsimas"
		)
	dictionary["programlabel"] = (
		"Program",
		u"Programa"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"There is already a program associated with this file extension!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Ar tikrai norite pašalinti šią asocijuotą rinkmeną?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		u"Neparinkta programa, šiam rinkmenos tipui!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Perdidelė rinkmena!"
		)
	############################## 1.1.9 ###############################################
	
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Svoris"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Trinti svorį"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"Ar tikrai trinti svorį?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Tas pats"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Minimalus"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"Senka ištekliai?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Dienoraštis"
		)
	
	############################## 1.2 ###############################################
	
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Kad filtruotumėte gyvūnus vardu, įveskite vardą čia"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Žiūrėti paskyrimus", u"Žiūrėti visus paskyrimus" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Žiūrėti paskyrimus"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"paskyrimas"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Sausis"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Vasaris"
		)
	dictionary["marchlabel"] = (
		"March",
		u"Kovas"
		)
	dictionary["aprillabel"] = (
		"April",
		u"Balandis"
		)
	dictionary["maylabel"] = (
		"May",
		u"Gegužė"
		)
	dictionary["junelabel"] = (
		"June",
		u"Birželis"
		)
	dictionary["julylabel"] = (
		"July",
		u"Liepa"
		)
	dictionary["augustlabel"] = (
		"August",
		u"Rugpjūtis"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"Rugsėjis"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Spalis"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"Lapkritis"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"Gruodis"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"Daugiau sužinoti apie rinkmenos asociacijas galima pagalbos skyriuje."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"Tinklalapis"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Sukurkite spausdintiną sąskaitą šiam klientui"
		)
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Gyvūno formos", u"Sukurkite ar suredaguokite formas naudodamas gyvūno detales")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Kliento formos", u"Sukurkite ar suredaguokite formas naudodamas kliento detales")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Gyvūno formos"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Kliento formos"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Peržiūra"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Slaptažodžiai"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Sąskaitų formos", u"Redaguoti sąskaitos šablonus")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Redaguoti sąskaitas"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Vaistų Formos", u"Suredaguoti vaisto šablonus")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Vaistų Formos"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Sąskaitos"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Sukurti sąskaitą"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Redaguoti sąskaitą"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Trinti sąskaitą"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Negaliu sudėlioti sąskaitų, prašom sureguliuoti datas"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Sukurkite formą, naudodamas klientų detales"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Pastaba:Kai šis procesas pasibaigs Evette turės užsidaryti,\nprašom Evette paleisti iš naujo, kad pamatytumėte rezultatus."
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"Sąskaitos dokumentas"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"apmokėta"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"nesumokėta"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Pasirinkite sąskaitos tapatybės dokumentą, kad pažymėtumėte sąskaitą kaip apmokėtą."
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Redaguoti kiekį, užmokėtą šiai sąskaitai."
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Redaguoti užmokestį"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Redaguoti gyvūną"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Medikamentai"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		(u"Redaguoti medikamentus", u"Redaguoti medikamentus")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		(u"Partijos paieška", u"Žiūrėti apyvartą pagal partijos numerį")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"Gal būt nesutampa medikamento partijos numeris"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Redaguoti judėjimą"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Įrašyti apyvartą"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Vartojamas"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Parduotuvė"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Procedūra"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Aprašymas"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Nurodykite vaistą"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Kiekis"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Neteisingas kiekis"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"Žiūrėti sąskaitą"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnozė"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Sukurti kvitą"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"Redaguoti patalpas gyvūnams", u"Redaguoti prieglaudą")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"Žiūrėti prieglaudą", u"Žiūrėti prieglaudą")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"&Prieglauda"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		"Prieglaudos dalys"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"Patalpos gyvūnams"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"Redaguoti prieglaudą"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"Are you sure that you want to delete this kennel block?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"Are you sure that you want to delete this kennel?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"Edit kennel"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"Buvimas"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"užimtas"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"neužimtas"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"Šio gyvūno perkėlimo nuosavybė"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"Rinktis naują savininką"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"Du kart spragtelti pasirinkimui"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"Sukurti gyvūno ASM įrašą"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"Pasirinkite gyvūną"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"Nuorodos numeris"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"Paieška davė per didelį skaičiųs rezultatų, prašom apriboti savo paiešką"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"Neturintis darbo"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"Jungiasi"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"Prisijungęs"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"Klaida"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"Nesėkminga registracija"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"Sėkminga registracija"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"Sukuriama Evette byla"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"Sukuriama Evette duombazė"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"Klaida įrašant Evette duomenų basę"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"ASM Importas", "Importuoti gyvūną iš ASM")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"Nesurastas savininkas"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"Šis gyvūnas buvo jau importuotas. Gal Jūs norėtumėte patikrinti tai?"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"Įrašyti svorį"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"Redaguoti svorį"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"Įrašyti vartotoją"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"Redaguoti vartotoją"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"Redaguoti priežastis",u" Suredaguokite bendras paskyrimo priežastis")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"Paskyrimo priežasčių paslėptukai"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"Dvikartis spragtelėjimas bendrų paskyrimo priežasčių pasirinkimui"
		)
	dictionary["filemenu"] = (
		"File",
		u"Byla"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"Išeiti", u"Išeiti iš Evette")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"Uždaryti visus skirtukus", u"Uždaryti visus atvertus skirtukus")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"Ar įsitikinęs, kad norite uždaryti visus atidarytus skirtukus? Bet kokie neišsaugoti duomenys bus prarasti.")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"Vieta"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"Redaguoti procedūras"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Sukurti paslėptuką"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Patinas"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Patelė"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"Nenustatyta"
		)
	dictionary["dayslabel"] = (
		"days",
		u"dienos"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"savaitės"
		)
	dictionary["monthslabel"] = (
		"months",
		u"mėnesiai"
		)
	dictionary["yearslabel"] = (
		"years",
		u"metai"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"Neteisingas gimtadienis"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Sukurkite naują patalpų gyvūnams bloką"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Sukurkite naują vadą"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"ASM Kliento importas", u"Importuoti klientą iš ASM")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Rinktis klientą"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Dvigubas spragtelėjimas kalendoriaus pasirinkimui"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Rinktis datą"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"Redaguoti paskyrimą"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Amžius"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Įrašyti vakcinaciją"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Spausdinti"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Kitas vartotojas pakeitė šią rinkmeną kadangi jūs atidarėte ją. Prašom uždaryti šį įrašą ir pabandyti dar kartą."
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM dėl"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Nežymėti"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Įrašyti paskyrimą"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Leisti atidaryti daugiau panelių"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Kitas vartotojas pakeitė šią rinkmeną. Ar Jūs norėtumėte perrašyti savus pakeitimus?"
		)
	dictionary["latelabel"] = (
		"Late",
		u"Vėlai"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"min"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Mikročipas"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Mikročipas implantuotas"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Savikaina"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"Žiūrėti vet. pastabas"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Dešinys spragtelėjimas, kad apžiūrėti pasiekiamus vet.gydytojus\Dvigubas spragtelėjimas laiko tarpo pasirinkimui"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"Shop išpardavimas"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"Shop Dalykai"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"Krepšys"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"Atidėtas"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"Į krepšį"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"Sujunkite kitą klientą į šį"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"Klientų sujungimas"
		)
	dictionary["addlabel"] = (
		"Add",
		u"Įdėti"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"Išimti"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"Apibrėžkite antkainio taisykles", u"Apibrėžkite antkainio taisykles")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"Padauginti iš"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"Santrauka į"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"Ši vertė nėra įtraukta į jūsų nustatymus, ji turi čia tiesiog leisti jums išmėginti jūsų nustatymus ant kai kurių tikrų skaičių."
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"Neteisinga kaina!"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"Prašom įeiti į kainas į centus vnt. \"50 \" į skirsnį į artimiausius 50 centų, \"100 \" į skirsnį į artimiausią dolerį."
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"Kliento kaina"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"Pateikite nustatymus"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"Pritaikykite einamuosius antkainio nustatymus visiems vaistams"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"Antkainis, pritaikytas visoms kainoms"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"Pasikeis visos viešos kainos, ar tikrai  tęsti?"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"Surinkite \"a\" kad sukurtumėte kainą su antkainiu."
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"Surinkite \"c\" pagalbai, apskaičiuojančiai savikainą."
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"Apskaičiuokite savikainą"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"Kaina už paką"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"Vienetai pako"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"CTRL + P paviešinimui."
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"Dingę gyvūnai"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"Rasti gyvūnai"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"Radinių biuras", u"Žiūrėti/Redaguoti radinių biurą")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"Dingę"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"Rasti"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"Dingimo data"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"Suradimo data"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"Kailio ilgis"
		)
	dictionary["longlabel"] = (
		"Long",
		u"Ilgas"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"Trumpas"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"Pūkuotas"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"Plikas"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"Dydis"
		)
	dictionary["largelabel"] = (
		"Large",
		u"Didelis"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"Vidutinis"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"Mažas"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"Jauniklis"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"Suaugęs"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"Pagyvenęs"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"Temperamentingas"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"Draugiškas"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"Bailus"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"Agresyvus"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"Spalva"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"Spalvos apibūdinimas"
		)
	dictionary["arealabel"] = (
		"Area",
		u"Rajonas"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"Prašom įdėti numanomus pašto indeksus, ir miestas/valstybė, atskirtus tarpais."
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"Įrašo data"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"Įšsaugoti"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"Kontaktai"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"Užbaigta"
		)
	dictionary["idlabel"] = (
		"ID",
		u"ID"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"Dešinys spragtelėjimas galimoms parinktims."
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"Search for a match"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"Surasti viršutinę ribą"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"Surasti apatinę ribą"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"Šis gyvūnas jau yra radinių biure!"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"Įtraukti užbaigtus?"
		)
	dictionary["closelabel"] = (
		"Close",
		u"Uždaryti"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"Rezultatas"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"Radinių biuro radiniai"
		)
	dictionary["systemlabel"] = (
		"System",
		u"Sistema"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"Versija"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"Įrašyti dingusį", u"Įrašyti dingusį gyvūną")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"Įrašyti surastą", u"Įrašyti surastą gyvūną")
		)
	dictionary["alllabel"] = (
		"All",
		u"Visi"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"Atnaujinti"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"Gyvūnų filtravimas"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"Žymėti apmokėtas"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"Gyvūno Prieglaudos Vadybininkas (ASM Shelter)"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"Jei naudojate Gyvūno Prieglaudos Vadybininko (Animal Shelter Manager) sistemą, jūs galite pažymėti klientą kaip \"Prieglauda \" , kad importuotumėte gyvūną,kurie neturi savininko įrašote nuo ASM."
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"Paskyrimo atnaujinimo intervalas"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
