#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Español####

def GetDictionary():

  dictionary = {}

  ##Misc
  dictionary["usernamelabel"] = (
    "Username",
    u"Nombre de Usuario"
    )
  dictionary["passwordlabel"] = (
    "Password",
    u"Contraseña"
    )
  dictionary["submitlabel"] = (
    "Submit",
    u"Aceptar"
    )
  dictionary["totallabel"] = (
    "Total",
    u"Total"
    )
  dictionary["fromlabel"] = (
    "From",
    u"De"
    )
  dictionary["tolabel"] = (
    "To",
    u"A"
    )
  dictionary["pricelabel"] = (
    "Price",
    u"Precio"
    )
  dictionary["descriptionlabel"] = (
    "Description",
    u"Descripción"
    )
  dictionary["yeslabel"] = (
    "Yes",
    u"Si"
    )
  dictionary["nolabel"] = (
    "No",
    u"No"
    )
  dictionary["editlabel"] = (
    "Edit",
    u"Editar"
    )
  dictionary["addlabel"] = (
    "Add",
    u"Agregar"
  )
  dictionary["deletelabel"] = (
    "Delete",
    u"Borrar"
    )
  dictionary["searchlabel"] = (
    "Search",
    u"Buscar"
    )
  dictionary["resetlabel"] = (
    "Reset",
    u"Reiniciar"
    )
  dictionary["movelabel"] = (
    "Move",
    u"Mover"
    )
  dictionary["unitlabel"] = (
    "Unit",
    u"Unidad"
    )
  dictionary["onlabel"] = (
    "on",
    u"en"
    )
  dictionary["namelabel"] = (
    "Name",
    u"Nombre"
    )
  dictionary["headertext1"] = (
    "The complete FREE veterinary practice management package",
    u"Programa completo de Gestión de una Clí­nica Veterinaria gratuito y libre"
    )
  dictionary["headertext2"] = (
    "You can change this header to anything you like by editing",
    u"Puede cambiar este encabezado editándolo como usted prefiera"
    )
  dictionary["generatedbylabel"] = (
    "Generated by",
    u"Generado por"
    )
  dictionary["timelabel"] = (
    "Time",
    u"Hora"
    )
  dictionary["operationslabel"] = (
    "Operations",
    u"Cirugías"
    )
  dictionary["operatinglabel"] = (
    "Operating",
    u"Operando"
    )
  dictionary["consultinglabel"] = (
    "Consulting",
    u"En consulta"
    )
  dictionary["vetlabel"] = (
    "Vet",
    u"Doctor/a"
    )
  dictionary["animaldetailslabel"] = (
    "Animal Details",
    u"Datos de la Mascota"
    )
  dictionary["ownerdetailslabel"] = (
    "Owner Details",
    u"Datos del Dueño"
    )
  dictionary["receiptlabel"] = (
    "Receipt",
    u"Recibo"
    )
  dictionary["problemlabel"] = (
    "Problem",
    u"Diagnóstico"
    )
  dictionary["noteslabel"] = (
    "Notes",
    u"Notas"
    )
  dictionary["planlabel"] = (
    "Plan",
    u"Procedimiento"
    )
  dictionary["userdeleted"] = (
    "User deleted",
    u"Usuario Eliminado"
    )
  dictionary["changelog"] = (
    "Change Log",
    u"Cambiar Datos"
    )
  dictionary["positionlabel"] = (
    "Position",
    u"Posición"
    )
  dictionary["datelabel"] = (
    "Date",
    u"Fecha"
    )
  dictionary["invalidtimemessage"] = (
    "Invalid Time",
    u"Hora no válida"
    )
  dictionary["containslabel"] = (
    "Contains",
    u"Contenido"
    )
  dictionary["nextduelabel"] = (
    "Next Due",
    u"Próxima consulta"
    )
  dictionary["nonelabel"] = (
    "None",
    u"Ninguna"
    )

  ##Menus
  dictionary["clientmenu"] = (
    "Clients",
    u"Clientes"
    )
  dictionary["appointmentsmenu"] = (
    "Appointments",
    u"Citas"
    )
  dictionary["medicationmenu"] = (
    "Medication",
    u"Medicamento"
    )
  dictionary["proceduresmenu"] = (
    "Procedures",
    u"Procedimientos"
    )
  dictionary["lookupsmenu"] = (
    "Lookups",
    u"Configuraciones"
    )
  dictionary["formsmenu"] = (
    "Forms",
    u"Formularios"
    )
  dictionary["staffmenu"] = (
    "Staff",
    u"Personal"
    )
  dictionary["settingsmenu"] = (
    "Settings",
    u"Parámetros (configuraciones)"
    )
  dictionary["helpmenu"] = (
    "Help",
    u"Ayuda"
    )
  dictionary["entirelabel"] = (
    "Entire",
    u"Entero"
    )
  dictionary["neuteredlabel"] = (
    "Neutered",
    u"Esterilizado-Castrado"
    )

  ##Menu items
  dictionary["addclientmenu"] = (
    ("Add Client", "Create a new client record"),
    (u"Añadir Cliente", u"Crea una nueva Ficha de Cliente")
    )
  dictionary["findclientmenu"] = (
    ("Find Clients", "Find client and animal records"),
    (u"Buscar Cliente", u"Busca los datos de un Cliente o Mascota")
    )
  dictionary["clienttitles"] = (
    ("Mr", "Ms", "Mrs", "Miss", "Dr"),
    ("Sr", "Sra", "Srto", "Srta", "Dr")
  )
  dictionary["viewappointmentsmenu"] = (
    ("View Appointments", "View todays appointments"),
    (u"Ver Citas", u"Ver las citas del día")
    )
  dictionary["viewoperationsmenu"] = (
    ("View Operations", "View todays operations"),
    (u"Ver Cirugías", u"Ver Cirugías del día")
    )
  dictionary["viewgroomingsmenu"] = (
    ("View Groomings", "View todays groomings"),
    (u"Ver Turnos de Peluquería", u"Ver Turnos de Peluquería del día")
    )
  dictionary["editusersmenu"] = (
    ("Edit Users", "Add and edit Evette users"),
    (u"Editar Usuarios", u"Agregar y Modificar Usuarios de Evette")
    )
  dictionary["editrotamenu"] = (
    ("Edit Rota", "Edit the rota"),
    (u"Editar Turnos", u"Editar y modificar el calendario de turnos")
    )
  dictionary["editmedicationmenu"] = (
    ("Edit Medication", "Edit Medication"),
    (u"Editar Medicamento", u"Editar Medicamento")
    )
  dictionary["editvaccinationsmenu"] = (
    ("Edit Vaccinations", "Edit Vaccinations"),
    (u"Editar Vacunaciones", u"Editar Vacunaciones")
    )
  dictionary["editproceduresmenu"] = (
    ("Edit Procedures", "Edit Procedures"),
    (u"Editar Procedimientos", u"Editar Procedimientos")
    )
  dictionary["editcoloursmenu"] = (
    ("Edit Colours", "Edit Colours"),
    (u"Editar Colores de Pelaje", u"Editar Colores de Pelaje")
    )
  dictionary["editbreedsmenu"] = (
    ("Edit Breeds", "Edit Breeds"),
    (u"Editar Razas", u"Editar Razas")
    )
  dictionary["editspeciesmenu"] = (
    ("Edit Species", "Edit Species"),
    (u"Editar Especies", u"Editar Especies")
    )
  dictionary["editformsmenu"] = (
    ("Edit Forms", "Edit Forms"),
    (u"Editar Formularios", u"Editar Formularios")
    )
  dictionary["editsettingsmenu"] = (
    ("Edit Settings", "Edit settings unique to this practice"),
    (u"Editar Configuraciones", u"Editar Configuraciones únicamente para esta práctica")
    )
  dictionary["randomdatamenu"] = (
    ("Random Data", "Generate random sample data to experiment with"),
    (u"Datos Aleatorios", u"Generar datos aleatorios para hacer pruebas")
    )
  dictionary["resettablesmenu"] = (
    ("Reset Database", "Completely reset the evette database"),
    (u"Reiniciar Base de Datos", u"Reiniciar totalmente la información de Evette")
    )
  dictionary["gethelpmenu"] = (
    ("Help", "Get help on using Evette"),
    (u"Ayuda", u"Obtener Ayuda en el uso de Evette")
    )
  dictionary["aboutmenu"] = (
    ("About", "Information about this program"),
    (u"Acerca de", u"Información acerca de Evette")
    )

  ##Toolbar
  dictionary["addclienttoolbar"] = (
    (" Add Client ", "Create a new client record"),
    (u" Agregar Cliente ", u"Crear la Ficha de un Cliente Nuevo")
    )
  dictionary["findclienttoolbar"] = (
    (" Client Search ", "Find clients and animals"),
    (u" Buscar Cliente ", u"Buscar Clientes y Mascotas")
    )
  dictionary["viewappointmentstoolbar"] = (
    (" Todays Appointments ", "View todays appointments"),
    (u" Citas Diarias ", u"Ver las citas del día")
    )
  dictionary["viewoperationstoolbar"] = (
    (" Todays Operations ", "View todays operations"),
    (u" Cirugías Diarias ", u"Ver las Cirugías del día")
    )
  dictionary["viewgroomingstoolbar"] = (
    (" Todays Groomings ", "View todays groomings"),
    (u" Peluquería ", u"Ver las citas de peluquería del día")
    )

  ##Client Panel
  dictionary["newclientpagetitle"] = (
    "New Client",
    u"Nuevo Cliente"
    )
  dictionary["clienttitlelabel"] = (
    "Title",
    u"Título"
    )
  dictionary["clientforenameslabel"] = (
    "Forenames",
    u"Nombre"
    )
  dictionary["clientsurnamelabel"] = (
    "Surname",
    u"Apellido"
    )
  dictionary["clientaddresslabel"] = (
    "Address",
    u"Domicilio"
    )
  dictionary["clientpostcodelabel"] = (
    "Postcode",
    u"Código Postal"
    )
  dictionary["clienthomephonelabel"] = (
    "Home Phone",
    u"Teléfono fijo"
    )
  dictionary["clientmobilephonelabel"] = (
    "Mobile Phone",
    u"Celular"
    )
  dictionary["clientworkphonelabel"] = (
    "Work Phone",
    u"Teléfono del Trabajo"
    )
  dictionary["clientemailaddresslabel"] = (
    "Email",
    u"Correo Electrónico"
    )
  dictionary["clientcommentslabel"] = (
    "Comments",
    u"Comentarios"
    )
  dictionary["clientanimalslabel"] = (
    "Animals",
    u"Mascotas"
    )
  dictionary["clientaddanimaltooltip"] = (
    "Create a new animal",
    u"Agregar una Mascota Nueva"
    )
  dictionary["clienteditanimaltooltip"] = (
    "Edit the selected animal record",
    u"Editar la ficha de la Mascota seleccionada"
    )
  dictionary["clientdeleteanimaltooltip"] = (
    "Delete the selected animal record",
    u"Borrar la ficha de la mascota seleccionada"
    )
  dictionary["clientrefreshanimalstooltip"] = (
    "Refresh the list of animals",
    u"Actualizar la lista de Mascotas"
    )
  dictionary["clientcreateappointmenttooltip"] = (
    "Create an appointment for the selected animal",
    u"Crear una cita para la Mascota seleccionada"
    )
  dictionary["clientbalancelabel"] = (
    "Balance",
    u"Balance"
    )
  dictionary["clientdetailedbilllabel"] = (
    "Detailed Bill",
    u"Factura detallada"
    )
  dictionary["clientsavetooltip"] = (
    "Save changes to client record",
    u"Guardar los datos del Cliente"
    )
  dictionary["clientunsavedchangesmessage"] = (
    "This client record has unsaved changes, are you sure you want to close?",
    u"Este cliente tiene datos sin guardar, ¿está seguro de salir?"
    )
  dictionary["clientdeleteanimalmessage"] = (
    "Really delete animal?",
    u"¿Realmente quiere borrar los datos de la Mascota?"
    )
  dictionary["clientrefreshbilltooltip"] = (
    "Refresh bill",
    u"Actualizar Factura"
    )
  dictionary["clientrecentbillitems"] = (
    (" Recent Items", "Adjust the date range of the bill items displayed"),
    (u"Facturas Recientes", u"Ajustar el intervalo de fechas entre las facturas mostradas")
    )
  dictionary["clientcleardetailedbillentriestooltip"] = (
    "Unselect the current bill item and clear the price and description entries",
    u"Desseleccionar la factura actual y borrar los precios y descripciones de los artículos"
    )
  dictionary["clientsubmitdetailedbillentriestooltip"] = (
    "Submit changes to the selected bill item",
    u"Guardar los cambios del artículo seleccionado de la factura"
    )
  dictionary["clientdeletedetailedbillentriestooltip"] = (
    "Delete the selected bill item",
    u"Borrar el artículo seleccionado de la factura"
    )

  ##Animal Panel
  dictionary["newanimalpagetitle"] = (
    "New Animal",
    u"Nueva Mascota"
    )
  dictionary["animalownerlabel"] = (
    "Owner",
    u"Dueño"
    )
  dictionary["animaleditownertooltip"] = (
    "Edit this animals owner",
    u"Editar la ficha del Dueño de esta Mascota"
    )
  dictionary["animalnamelabel"] = (
    "Name",
    u"Nombre"
    )
  dictionary["animalsexlabel"] = (
    "Sex",
    u"Género"
    )
  dictionary["animalspecieslabel"] = (
    "Species",
    u"Especie"
    )
  dictionary["animalbreedlabel"] = (
    "Breed",
    u"Raza"
    )
  dictionary["animalcolourlabel"] = (
    "Colour",
    u"Color"
    )
  dictionary["animaldoblabel"] = (
    "DOB",
    u"Fecha de Nacimiento"
    )
  dictionary["animalchipnolabel"] = (
    "Chip #",
    u"Tatuaje o Chip"
    )
  dictionary["animalcommentslabel"] = (
    "Comments",
    u"Comentarios"
    )
  dictionary["animalneuteredtooltip"] = (
    "Tick if the animal is neutered",
    u"Marcar si el animal está esterilizado o castrado"
    )
  dictionary["animalprintentirerecordtooltip"] = (
    "Generate printable output of this entire animal record",
    u"Generar una Versión para Imprimir de la ficha completa de la Mascota"
    )
  dictionary["animalgenerateformtooltip"] = (
    "Generate a form using this animals details",
    u"Generar un formulario usando los datos de la Mascota"
    )
  dictionary["animalappointmentslabel"] = (
    "Appointments",
    u"Citas"
    )
  dictionary["animalcreateappointmenttooltip"] = (
    "Create an appointment for this animal",
    u"Crear una cita para esta Mascota"
    )
  dictionary["animaleditappointmenttooltip"] = (
    "Edit the selected appointment",
    u"Modificar la cita seleccionada"
    )
  dictionary["animalrefreshappointmentstooltip"] = (
    "Refresh the list of appointments",
    u"Actualizar la lita de citas"
    )
  dictionary["animaldeleteappointmenttooltip"] = (
    "Delete the selected appointment",
    u"Borrar la cita seleccionada"
    )
  dictionary["animalprintappointmenttooltip"] = (
    "Generate printable output for the selected appointment",
    u"Generar una Versión para Imprimir la cita seleccionada"
    )
  dictionary["animalvetformbutton"] = (
    ("Vet Form", "Edit the vet form for the selected appointment"),
    (u"Formulario Veterinario", u"Editar el Formulario Veterinario para la cita seleccionada")
    )
  dictionary["animalappointmentdetailslabel"] = (
    "Appointment Details",
    u"Detalles de la cita"
    )
  dictionary["animalvaccinationslabel"] = (
    "Vaccinations",
    u"Vacunaciones"
    )
  dictionary["animalsavebuttontooltip"] = (
    "Save any changes made to this animal record",
    u"Guardar los cambios realizados en la ficha de esta mascota"
    )
  dictionary["animalunsavedchangesmessage"] = (
    "This animal record has unsaved changes, are you sure you want to close?",
    u"Esta Mascota tiene datos sin guardar, ¿está seguro de salir?"
    )
  dictionary["animalconfirmdeleteappointmentmessage"] = (
    "Really delete appointment?",
    u"¿Está seguro de borrar la cita?"
    )
  dictionary["animalresetvaccinationentries"] = (
    "Reset vaccination entries",
    u"Reiniciar el historial de vacunaciones"
    )
  dictionary["animalvaccinelabel"] = (
    "Vaccine",
    u"Vacuna"
    )
  dictionary["animalgivenlabel"] = (
    "Given: ",
    u"Administrado: "
    )
  dictionary["animalnextlabel"] = (
    " Next: ",
    u"Próxima: "
    )
  dictionary["animaldeletevaccinationtooltip"] = (
    "Delete the selected vaccination",
    u"Borrar la vacuna seleccionada"
    )
  dictionary["animalsubmitvaccinationtooltip"] = (
    "Submit this vaccination",
    u"Agregar esta vacuna"
    )
  dictionary["animalconfirmdeletevaccinationmessage"] = (
    "Are you sure that you want to delete this vaccination?",
    u"¿Está seguro de borrar esta vacuna?"
    )
  dictionary["animalvaccinationbatchlabel"] = (
    " Batch: ",
    u" Número de lote:"
    )

  ##Appointments
  dictionary["appointmentappointmentforlabel"] = (
    "Appointment for",
    u"Cita para"
    )
  dictionary["appointmentoperationforlabel"] = (
    "Operation for",
    u"Cirugí­a de"
    )
  dictionary["appointmentgroomingforlabel"] = (
    "Grooming for",
    u"Peluquería de"
    )
  dictionary["appointmententervettooltip"] = (
    "If this appointment is for a specific vet, enter the vet's name here",
    u"Si esta cita es para un determinado Doctor/a, agregue el nombre del Doctor/a aquí­"
    )
  dictionary["appointmentrefreshtooltip"] = (
    "Refresh the list of appointments",
    u"Actualizar la lista de citas"
    )
  dictionary["appointmentreasonlabel"] = (
    "Reason For Appointment",
    u"Motivo de la cita"
    )
  dictionary["appointmenttimelabel"] = (
    "Appointment time",
    u"Hora de la cita"
    )
  dictionary["appointmentisopcheckbox"] = (
    ("Operation?", "Tick this box if you would like to book an operation"),
    (u"Cirugí­a?", u"Marque este cuadro para reservar una Cirugí­a")
    )
  dictionary["appointmentsubmittooltip"] = (
    "Submit this appointment",
    u"Guardar esta cita"
    )
  dictionary["appointmentdeletetooltip"] = (
    "Delete this appointment",
    u"Borrar esta cita"
    )
  dictionary["appointmentstatuslabel"] = (
    "Status",
    u"Estado o Situación"
    )
  dictionary["appointmentnotarrivedlabel"] = (
    "Not Arrived",
    u"No llegó"
    )
  dictionary["appointmentwaitinglabel"] = (
    "Waiting",
    u"Esperando"
    )
  dictionary["appointmentwithvetlabel"] = (
    "With Vet",
    u"Con el Doctor/a"
    )
  dictionary["appointmentdonelabel"] = (
    "Done",
    u"Realizado"
    )
  dictionary["appointmenteditownerbutton"] = (
    ("Edit Owner", "Edit client record"),
    (u"Editar Propietario", u"Editar la ficha del Propietario")
    )
  dictionary["appointmenteditanimalbutton"] = (
    ("Edit Animal", "Edit animal record"),
    (u"Editar Mascota", u"Editar la ficha de la Mascota")
    )
  dictionary["appointmentappointmentsforlabel"] = (
    "Appointments for",
    u"Citas para"
    )
  dictionary["appointmentoperationsforlabel"] = (
    "Operations for",
    u"Cirugías para"
    )
  dictionary["appointmentgroomingsforlabel"] = (
    "Groomings for",
    u"Peluquerías para"
    )
  dictionary["appointmenttimetooearlymessage"] = (
    "Appointment time is before the practice opens!",
    u"¡La hora de la cita es antes de la apertura de la Clínica!"
    )
  dictionary["appointmenttimetoolatemessage"] = (
    "Appointment time is after the practice closes!",
    u"¡La hora de la cita es posterior al cierre de la Clínica!"
    )
  dictionary["appointmentinvalidtimemessage"] = (
    "Invalid time - times must be HH:MM!",
    u"¡Hora Incorrecta - el formato de la hora es HH:MM!"
    )
  dictionary["appointmenttypetooltip"] = (
    "Choose the appointment type from the dropdown list",
    u"Selecciona el tipo de cita de la lista desplegable"
  )

  ##Client search panel
  dictionary["clientsearchpagetitle"] = (
    "Client Search",
    u"Búsqueda de Cliente"
    )
  dictionary["clientsearchstitlelabel"] = (
    "Clients",
    u"Clientes"
    )
  dictionary["clientsearchsurnamelabel"] = (
    "Surname",
    u"Apellido"
    )
  dictionary["clientsearchphonelabel"] = (
    "Phone",
    u"Teléfono"
    )
  dictionary["clientsearchaddresslabel"] = (
    "Address",
    u"Dirección"
    )
  dictionary["clientsearchpostcodelabel"] = (
    "Postcode",
    u"Código Postal"
    )
  dictionary["clientsearchemaillabel"] = (
    "Correo Electrónico",
    u"Correo Electrónico"
    )
  dictionary["clientsearchclearbutton"] = (
    ("Clear", "Clear all entries"),
    (u"Borrar", u"Borrar todas las entradas")
    )
  dictionary["clientsearchsearchbutton"] = (
    ("Search", "Perform the search"),
    (u"Buscar", u"Realizar la búsqueda")
    )
  dictionary["clientsearcheditclienttooltip"] = (
    "Edit the selected client record",
    u"Editar la ficha del cliente seleccionado"
    )
  dictionary["clientsearchdeleteclienttooltip"] = (
    "Delete the selected client record",
    u"Borrar la ficha del cliente seleccionado"
    )
  dictionary["clientsearchanimallabel"] = (
    "Animals",
    u"Mascotas"
    )
  dictionary["clientsearchanimalnamelabel"] = (
    "Name",
    u"Nombre"
    )
  dictionary["clientsearchanimalsexlabel"] = (
    "Sex",
    u"Sexo"
    )
  dictionary["clientsearchanimalspecieslabel"] = (
    "Species",
    u"Especie"
    )
  dictionary["clientsearchanimalbreedlabel"] = (
    "Breed",
    u"Raza"
    )
  dictionary["clientsearchanimalchipnolabel"] = (
    "Chip #",
    u"Tatuaje o chip "
    )
  dictionary["clientsearchanimalcommentslabel"] = (
    "Comments",
    u"Comentarios"
    )
  dictionary["clientsearcheditanimaltooltip"] = (
    "Edit the selected animal record",
    u"Editar la ficha de la Mascota seleccionada"
    )
  dictionary["clientsearchdeleteanimaltooltip"] = (
    "Delete the selected animal record",
    u"Borrar la ficha de la Mascota seleccionada"
    )
  dictionary["clientreceiptchangeloglabel"] = (
    "Receipt item - ",
    u"Recibo del Artí­culo - "
    )
  dictionary["clientreceiptdeletemessage"] = (
    "Really delete this receipt entry?",
    u"Â¿Realmente borra la entrada de este recibo?"
    )
  dictionary["clientclearpaymenttooltip"] = (
    "Empty the payment entry",
    u"Borrar el pago"
    )
  dictionary["clientpaymentlabel"] = (
    "Payment",
    u"Pago"
    )
  dictionary["clientsubmitpaymenttooltip"] = (
    "Submit Payment",
    u"Incorporar pago"
    )
  dictionary["clientpaymentinreceiptlabel"] = (
    "Payment",
    u"Pago"
    )

  ##Launch panels
  dictionary["launchcreateconffilemessage"] = (
    "Conf file not found! Create one now?",
    u"¡Archivo Conf no encontrado! ¿Desea crear uno ahora?"
    )
  dictionary["launchevettefoldermessage"] = (
    "Evette folder not found! Create it now?",
    u"¡Carpeta Evette no encontrada! ¿Desea crear una ahora?"
    )
  dictionary["launchnodatabaseservermessage"] = (
    "Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
    u"¡Imposible conectarse al servidor de datos! Por favor, verifique si esta instalado y funcionando. ¿Desea ajustar las configuraciones locales?"
    )
  dictionary["launchnoevettedatabasemessage"] = (
    "Unable to locate evette database! Would you like to create one now?",
    u"¡Imposible localizar la base de datos de evette! ¿Desea crearla ahora?"
    )
  dictionary["launchconffilecreatedmessage"] = (
    "Conf file created",
    u"Archivo Conf creado"
    )
  dictionary["launchevettefoldercreatedmessage"] = (
    "Evette folder created",
    u"Carpeta Evette creada"
    )
  dictionary["launchdbiplabel"] = (
    "DB IP",
    u"IP de la base de datos"
    )
  dictionary["launchdbuserlabel"] = (
    "DB User",
    u"Usuario de la base de datos"
    )
  dictionary["launchdbpasslabel"] = (
    "DB Pass",
    u"Contraseña de la base de datos"
    )
  dictionary["launchunabletocreatedatabasemessage"] = (
    "Unable to create database, please check your mysql server config!",
    u"¡Imposible crear Base de Datos, por favor compruebe la configuración de su servidor mysql!"
    )
  dictionary["launchdatabasecreatedmessage"] = (
    "Database created successfully!",
    u"¡Base de Datos creada exitosamente!"
    )
  dictionary["launchlogintooltip"] = (
    "Log in",
    u"Conectarse"
    )

  ##Lookups
  dictionary["lookupscolour"] = (
    "Colour Lookups",
    u"Colores de Pelaje"
    )
  dictionary["lookupcolour"] = (
    "Colour Lookup",
    u"Color de Pelaje"
    )
  dictionary["lookupsspecies"] = (
    "Species Lookups",
    u"Especies"
    )
  dictionary["lookupspecies"] = (
    "Species Lookup",
    u"Especie"
    )
  dictionary["lookupsbreed"] = (
    "Breed Lookups",
    u"Razas"
    )
  dictionary["lookupbreed"] = (
    "Breed Lookup",
    u"Raza"
    )
  dictionary["lookupsreason"] = (
    "Reason Lookups",
    u"Razones"
  )
  dictionary["lookupreason"] = (
    "Reason Lookup",
    u"Razón"
  )
  dictionary["lookupsrefreshtooltip"] = (
    "Refresh the list",
    u"Actualizar la lista"
    )
  dictionary["lookupsdeletetooltip"] = (
    "Delete the selected lookup",
    u"Borrar la configuración seleccionada"
    )
  dictionary["lookupssubmittooltip"] = (
    "Submit lookup",
    u"Incorporar configuración"
    )
  dictionary["lookupsduplicatemessage"] = (
    "That lookup already exists, it's pointless putting it in again!",
    u"¡Esta configuración ya existe, es inútil agregarla nuevamente!"
    )
  dictionary["lookupsnonamemessage"] = (
    "You must give a name for this lookup!",
    u"¡Debés nombrar esta configuración!"
    )
  dictionary["lookupsdeletemessage"] = (
    "Are you sure that you want to delete this lookup?",
    u"¿Realmente desea borrar esta configuración?"
    )

  ##Medication

  dictionary["medicationeditmedicationpagetitle"] = (
    "Edit Medication",
    u"Editar Medicamento"
    )
  dictionary["medicationrefreshtooltip"] = (
    "Edit Medication",
    u"Editar Medicamento"
    )
  dictionary["medicationeditconsumable"] = (
    "Edit Consumable",
    u"Editar Consumible"
  )
  dictionary["movementcantbezero"] = (
    "Movement quantity can not be zero.",
    u"La cantidad del movimiento no puede ser cero."
  )
  dictionary["medicationdeletetooltip"] = (
    "Delete the selected medication",
    u"Borrar el medicamento seleccionado"
    )
  dictionary["medicationbatchnolabel"] = (
    "Batch #",
    u"Lote #"
    )
  dictionary["medicationbatchmovementreporttooltip"] = (
    "Generate a report showing all movements of this batch",
    u"Generar un reporte con todos los movimientos de este lote"
    )
  dictionary["medicationstocklisttooltip"] = (
    "Print a list of your current stock",
    u"Imprimir una lista de sus existencias actuales"
    )
  dictionary["medicationmovementsoflabel"] = (
    "Movements of ",
    u"Movimientos de "
    )
  dictionary["medicationconfirmdeletemessage"] = (
    "Are you sure you want to delete ",
    u"¿Está seguro de borrar "
    )
  dictionary["medicationconfirmoverwritemessage"] = (
    "Are you sure you want to overwrite this medication?",
    u"¿Está seguro de querer sobreescribir este medicamento?"
    )
  dictionary["medicationmovementsofbatchnumberlabel"] = (
    "Movements of Batch Number ",
    u"Movimientos del Lote Número"
    )
  dictionary["medicationexpireslabel"] = (
    "Expires",
    u"Expira"
    )
  dictionary["medicationrefreshdetailstooltip"] = (
    "Refresh the details of this medication",
    u"Actualizar los detalles de este medicamento"
    )
  dictionary["medicationdeletemovementtooltip"] = (
    "Delete this medication movement",
    u"Borrar este cambio de medicamento"
    )
  dictionary["movementmovementlabel"] = (
    "Movement",
    u"Cambio"
    )
  dictionary["movementoverwritemovementmessage"] = (
    "Are you sure that you want to overwrite this movement?",
    u"¿Está seguro de sobreescribir este cambio?"
    )
  dictionary["movementconfirmdeletemovementmessage"] = (
    "Are you sure that you want to delete this movement?",
    u"¿Está seguro de borrar este cambio?"
    )
  dictionary["movementrefreshmovementsmessage"] = (
    "Refresh the details of this medication",
    u"Actualizar los detalles de este medicamento"
    )
  dictionary["movementresetsearchentriestooltip"] = (
    "Reset search entries",
    u"Reiniciar los criterios de búsqueda"
    )
  dictionary["medicationcurrentbatchlabel"] = (
    "Current Batch",
    u"Lote actual"
    )
  dictionary["medicationunitpricelabel"] = (
    "Unit Price",
    u"Precio Unitario"
    )

  ##Weekdays
  dictionary["monday"] = (
    "Monday",
    u"Lunes"
    )
  dictionary["tuesday"] = (
    "Tuesday",
    u"Martes"
    )
  dictionary["wednesday"] = (
    "Wednesday",
    u"Miércoles"
    )
  dictionary["thursday"] = (
    "Thursday",
    u"Jueves"
    )
  dictionary["friday"] = (
    "Friday",
    u"Viernes"
    )
  dictionary["saturday"] = (
    "Saturday",
    u"Sábado"
    )
  dictionary["sunday"] = (
    "Sunday",
    u"Domingo"
    )
  dictionary["daynames"] = (
    (dictionary["sunday"][0], dictionary["monday"][0], dictionary["tuesday"][0], dictionary["wednesday"][0], dictionary["thursday"][0], dictionary["friday"][0], dictionary["saturday"][0]),
    (dictionary["sunday"][1], dictionary["monday"][1], dictionary["tuesday"][1], dictionary["wednesday"][1], dictionary["thursday"][1], dictionary["friday"][1], dictionary["saturday"][1])
  )


  ##Procedures

  dictionary["editprocedurespagetitle"] = (
    "Edit Procedures",
    u"Editar Procedimientos"
    )
  dictionary["proceduresrefreshprocedurestooltip"] = (
    "Refresh the list of procedures",
    u"Actualizar la lista de Procedimientos"
    )
  dictionary["proceduresdeleteproceduretooltip"] = (
    "Delete the selected procedure",
    u"Borrar el Procedimiento seleccionado"
    )
  dictionary["proceduresunnamedproceduremessage"] = (
    "You must give this procedure a name!",
    u"¡Debés darle un nombre a este procedimiento!"
    )
  dictionary["proceduresoverwritemessage"] = (
    "Are you sure that you want to edit this procedure?",
    u"¿Está seguro de editar este Procedimiento?"
    )
  dictionary["proceduresdeletemessage"] = (
    "Are you sure that you want to delete this procedure?",
    u"¿Está seguro de borrar este Procedimiento?"
    )

  ##Random data

  dictionary["randomdatapagetitle"] = (
    "Random Data",
    u"Datos Aleatorioos"
    )
  dictionary["randomdatanoofclientslabel"] = (
    "No of clients",
    u"Cantidad de clientes"
    )
  dictionary["randomdatanoofanimalslabel"] = (
    "No of animals",
    u"Cantidad de animales"
    )
  dictionary["randomdatanoofappointmentslabel"] = (
    "No of appointments",
    u"Cantidad de citas"
    )
  dictionary["randomdatanoofoperationslabel"] = (
    "No of operations",
    u"Cantidad de cirugías"
    )
  dictionary["randomdatanoofmedicationslabel"] = (
    "No of medications",
    u"Cantidad de medicamentos"
    )
  dictionary["randomdataclientslabel"] = (
    "Clients",
    u"Clientes"
    )
  dictionary["randomdataanimalslabel"] = (
    "Animals",
    u"Mascotas"
    )
  dictionary["randomdataappointmentslabel"] = (
    "Appointments",
    u"Citas"
    )
  dictionary["randomdataoperationslabel"] = (
    "Operations",
    u"Cirugías"
    )
  dictionary["randomdatamedicationlabel"] = (
    "Medication",
    u"Medicamento"
    )
  dictionary["randomdatasubmittooltip"] = (
    "Create random data",
    u"Crear datos aleatorios"
    )

  ##Settings Panel

  dictionary["settingspracticenamelabel"] = (
    "Practice Name",
    u"Nombre de la Práctica Profesional"
    )
  dictionary["settingsopenfromlabel"] = (
    "Open from",
    u"Abierto desde las"
    )
  dictionary["settingsopentolabel"] = (
    "Open to",
    u"Abierto hasta las"
    )
  dictionary["settingsoperatingtimelabel"] = (
    "Operating time",
    u"Duración de la Cirugí­a"
    )
  dictionary["settingshtmlviewerlabel"] = (
    "HTML viewer",
    u"Visor HTML"
    )
  dictionary["settingsfindhtmlviewertooltip"] = (
    "HTML viewer",
    u"Visor HTML"
    )
  dictionary["settingslanguagelabel"] = (
    "Language",
    u"Lenguaje"
    )
  dictionary["settingshandlerotabydaylabel"] = (
    "Handle rota by day",
    u"Administrar turnos por día"
  )
  dictionary["settingshandlerotabydaytooltip"] = (
    "Handle rota by day, setting each time on the calendar. Unchecking this allows to set rota by user globally.",
    u"Administrar turnos por día, seteando horarios en el calendario. Desmarcando esto permite setear los turnos por usuario de forma global."
  )

  ##Staff settings

  dictionary["editvetformlabel"] = (
    "Edit Vet Form",
    u"Editar Formulario Veterinario"
    )
  dictionary["editfinanceslabel"] = (
    "Edit Finances",
    u"Editar Finanzas"
    )
  dictionary["showtoolbarlabel"] = (
    "Show Toolbar",
    u"Mostrar Barra de Herramientas"
    )
  dictionary["viewchangeloglabel"] = (
    "View Changelogs",
    u"Ver Registro de Cambios"
    )
  dictionary["editsettingslabel"] = (
    "Edit Settings",
    u"Editar Configuración"
    )
  dictionary["editrotalabel"] = (
    "Edit Rota",
    u"Editar Turnos"
    )
  dictionary["editstaffpagetitle"] = (
    "Edit Rota",
    u"Editar Turnos"
    )
  dictionary["staffmemberlabel"] = (
    "Staff Member",
    u"Miembro del Personal"
    )
  dictionary["deleteusertooltip"] = (
    "Delete the selected user",
    u"Borrar el usuario seleccionado"
    )
  dictionary["clientslabel"] = (
    "Clients",
    u"Clientes"
    )
  dictionary["animalslabel"] = (
    "Animals",
    u"Mascotas"
    )
  dictionary["appointmentslabel"] = (
    "Appointments",
    u"Citas"
    )
  dictionary["medicationlabel"] = (
    "Medication",
    u"Medicamento"
    )
  dictionary["procedureslabel"] = (
    "Clients",
    u"Clientes"
    )
  dictionary["lookupslabel"] = (
    "Lookups",
    u"Configuraciones"
    )
  dictionary["formslabel"] = (
    "Forms",
    u"Formularios"
    )
  dictionary["userslabel"] = (
    "Users",
    u"Usuarios"
    )
  dictionary["misclabel"] = (
    "Misc",
    u"Misceláneos"
    )
  dictionary["scheduleslabel"] = (
    "Schedules",
    u"Horarios"
  )
  dictionary["invalidscheduletime"] = (
    {'mon': 'Invalid monday schedules', 'tue': 'Invalid tuesday schedules', 'wed': 'Invalid wednesday schedules',
     'thu': 'Invalid thursday schedules', 'fri': 'Invalid friday schedules', 'sat': 'Invalid saturday schedules',
     'sun': 'Invalid sunday schedules'},
    {'mon': u"Horario inválido de lunes", 'tue': u"Horario inválido de martes", 'wed': u"Horario inválido de miércoles",
     'thu': u"Horario inválido de jueves", 'fri': u"Horario inválido de viernes", 'sat': u"Horario inválido de sábado",
     'sun': u"Horario inválido de domingo"}
  )
  dictionary["from"] = (
    "From",
    u"Desde"
  )
  dictionary["to"] = (
    "To",
    u"Hasta"
  )
  dictionary["tickalllabel"] = (
    "Tick All",
    u"Marcar todos"
    )
  dictionary["tickalltooltip"] = (
    "Give the user permission to use ALL areas of the system. Use with care!",
    u"¡Permitir al usuario el uso de TODAS las áreas del Sistema. Usar con cuidado!"
    )
  dictionary["useroverwritemessage"] = (
    "Are you sure that you want to overwrite this user?",
    u"¿Está seguro de sobreescribir este Usuario?"
    )
  dictionary["userdeletemessage"] = (
    "Are you sure that you want to delete this user?",
    u"¿Está seguro de borrar este Usuario?"
    )

  ##Edit Rota

  dictionary["editrotapagetitle"] = (
    "Edit Rota",
    u"Editar Turno"
    )
  dictionary["timeonlabel"] = (
    "Time On",
    u"Hora de Comienzo"
    )
  dictionary["timeofflabel"] = (
    "Time Off",
    u"Hora de Finalización"
    )
  dictionary["operatinglabel"] = (
    "Operating",
    u"En Cirugía"
    )
  dictionary["staffsummarylabel"] = (
    "Staff Summary",
    u"Esquema del Personal"
    )
  dictionary["dayplanlabel"] = (
    "Day Plan",
    u"Planificación del Día"
    )
  dictionary["novetnamemessage"] = (
    "You must enter a vets name!",
    u"Introduzca el Nombre del Dr/a"
    )
  dictionary["vetfinishedbeforestartingmessage"] = (
    "The vet cannot finish before starting!",
    u"¡El Doctor no puede terminar sin haber comenzado!"
    )
  dictionary["vettwoplacesatoncemessage"] = (
    "This person cannot be in two places at once!",
    u"¡Esta persona no puede estar en dos lugares al mismo tiempo!"
    )

  ##Vaccinations

  dictionary["vaccinationseditvaccinationspagetitle"] = (
    "Edit Vaccinations",
    u"Editar Vacunaciones"
    )
  dictionary["vaccinationsvaccinelabel"] = (
    "Vaccine",
    u"Vacuna"
    )
  dictionary["vaccinationsrefreshvaccinationstooltip"] = (
    "Refresh the list of vaccinations",
    u"Actualizar la lista de vacunaciones"
    )
  dictionary["vaccinationsdeletevaccinationstooltip"] = (
    "Delete the selected vaccination",
    u"Borrar la vacunación seleccionada"
    )
  dictionary["vaccinationsprintstocklisttooltip"] = (
    "Print a list of your current stock",
    u"Imprimir el listado de las existencias actuales"
    )
  dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
    "Are you sure you want to delete this vaccination?",
    u"¿Está seguro de borrar esta vacunación?"
    )
  dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
    "Are you sure you want to overwrite this vaccination?",
    u"¿Está seguro de sobreescribir esta vacunación?"
    )
  dictionary["vaccinationsrefreshmovementstooltip"] = (
    "Refresh the details of this vaccination",
    u"Actualizar las detalles de esta vacunación"
    )
  dictionary["vaccinationsdeletemovementtooltip"] = (
    "Delete this vaccination movement",
    u"Borrar esta vacunación"
    )
  dictionary["vaccinationsoverwritemovementmessage"] = (
    "Are you sure that you want to edit this movement?",
    u"¿Está seguro de editar el historial?"
    )
  dictionary["vaccinationsdeletemovementmessage"] = (
    "Are you sure that you want to delete this movement?",
    u"¿Está seguro de borrar esta entrada?"
    )


  ##Vet Form

  dictionary["vetformpagetitle"] = (
    "Vet Form",
    u"Formulario Veterinario"
    )
  dictionary["vetformotherappointmentslabel"] = (
    "Appointment History",
    u"Historial de Citas"
    )
  dictionary["vetformappointmentdetailslabel"] = (
    "Appointment Details",
    u"Detalles de Citas"
    )
  dictionary["vetformmedlabel"] = (
    "Med",
    u"Medicamento"
    )
  dictionary["vetformvacclabel"] = (
    "Vacc",
    u"Vacunaciones"
    )
  dictionary["vetformproclabel"] = (
    "Proc",
    u"Procedimientos"
    )
  dictionary["vetformmanlabel"] = (
    "Man",
    u"Manual??"
    )
  dictionary["vetformdeletereceipttooltip"] = (
    "Delete the selected item from the receipt",
    u"Borrar el artí­culo seleccionado de la receta"
    )
  dictionary["vetformdonetooltip"] = (
    "Mark this appointment as complete and close",
    u"Marcar esta cita como completa y terminada"
    )
  dictionary["vetformsavetooltip"] = (
    "Save any changes made to this vet form",
    u"Guardar los cambios hechos en este Formulario Veterinario"
    )
  dictionary["vetformreceiptitemlabel"] = (
    "Receipt Item",
    u"Artículo de la Receta"
    )
  dictionary["vetformdeletereceiptmessage"] = (
    "Are you sure you want to delete this receipt item?",
    u"¿Está seguro de borrar este artí­culo?"
    )
  dictionary["vetformmedicationclearcontainstooltip"] = (
    "Clear the \"Contains\" entry",
    u"Borrar la entrada \"Contiene\""
    )
  dictionary["vetformrefreshmedicationtooltip"] = (
    "Refresh the medication list",
    u"Actualizar la lista de medicamentos"
    )
  dictionary["vetformnoofunitstooltip"] = (
    "Enter the number of units that you are dispensing here",
    u"Introducir la posologí­a"
    )
  dictionary["vetforminstructionslabel"] = (
    "Instructions",
    u"Instrucciones"
    )
  dictionary["vetforminstructionstooltip"] = (
    "Enter instructions on how to administer this medication here",
    u"Introducir las instrucciones de cómo se debe administrar este medicamento"
    )
  dictionary["vetformprintlabeltooltip"] = (
    "Print a label for this medication",
    u"Imprimir una etiqueta para este medicamento"
    )
  dictionary["vetformbatchnotooltip"] = (
    "Enter the batch number here",
    u"Introducir el número de lote aquí­"
    )
  dictionary["vetformrefreshvaccinationtooltip"] = (
    "Refresh the vaccination list",
    u"Actualizar la lista de vacunaciones"
    )
  dictionary["vetformrefreshprocedurestooltip"] = (
    "Refresh the procedures list",
    u"Actualizar la lista de procedimientos"
    )
  dictionary["vetformnodescriptionmessage"] = (
    "You must give a description!",
    u"¡Debés introducir una descripción!"
    )

  ##View Appointments

  dictionary["appointmenttypelabel"] = (
    "Appointment type",
    u"Tipo de cita"
  )

  dictionary["viewappointmentspagetitle"] = (
    "View Appointments",
    u"Visualizar Citas"
    )
  dictionary["viewoperationspagetitle"] = (
    "View Operations",
    u"Visualizar Cirugías"
    )
  dictionary["viewgroomingspagetitle"] = (
    "View Groomings",
    u"Visualizar Peluquerías"
    )
  dictionary["viewappointmentsmarkwithvettooltip"] = (
    "Mark this appointment as with the vet",
    u"Marcar esta cita con un/a Doctor/a"
    )
  dictionary["viewappointmentschoosevettooltip"] = (
    "Choose a vet",
    u"Elegir un/a Doctor/a"
    )
  dictionary["viewappointmentsvetformtooltip"] = (
    "Carry out the vet visit for this appointment",
    u"Organizar la visita del Doctor/a para esta cita"
    )
  dictionary["viewappointmentsmarkarrivedtooltip"] = (
    "Mark this appointment as arrived",
    u"Marcar esta cita como presente"
    )
  dictionary["viewappointmentsmarkdonetooltip"] = (
    "Mark this appointment as done",
    u"Marcar esta cita como realizada"
    )
  dictionary["viewappointmentseditclientbuttonlabel"] = (
    "Edit Client",
    u"Editar Cliente"
    )
  dictionary["viewappointmentseditclientbuttontooltip"] = (
    "Edit this clients record (so they can pay their bill)",
    u"Editar la ficha del cliente (para que pueda pagar la factura)"
    )
  dictionary["viewappointmentsvetsonlabel"] = (
    "Vets On",
    u"Veterinarios/as presentes"
    )
  dictionary["viewappointmentsgroomersonlabel"] = (
    "Groomers On",
    u"Peluqueros/as presentes"
    )
  dictionary["appointmentsearchpagetitle"] = (
    "Appointment Search",
    u"Búsqueda de citas"
    )
  dictionary["appointmentsearchmenu"] = (
    ("Appointment Search", "Find an appointment"),
    (u"Búsqueda de citas", u"Buscar una cita")
    )
  dictionary["appointmentsearchanimalnamelabel"] = (
    "Animal Name",
    u"Nombre de la Mascota"
    )
  dictionary["reasonlabel"] = (
    "Reason",
    u"Motivo"
    )
  dictionary["viewoperationspagetitle"] = (
    "View Operations",
    u"Ver Cirugías"
    )
  dictionary["dateformat"] = (
    "DDMMYYYY",
    u"DDMMYYYY"
    )
  dictionary["currency"] = (
    "&pound;",
    "$"
    )
  dictionary["mailshotmenu"] = (
    ("Mail Shot", "Compile a list of clients to contact"),
    (u"Lista de Correo", u"Lista de Clientes para contactar")
    )
  dictionary["mailshotpagetitle"] = (
    "Mail Shot",
    u"Lista de correo"
    )
  dictionary["anyvaccine"] = (
    "Any Vaccine",
    u"Cualquier vacuna"
    )
  dictionary["anyspecies"] = (
    "Any Species",
    u"Caulquier Especie"
    )
  dictionary["deceasedlabel"] = (
    "Deceased",
    u"Fallecidos"
    )
  dictionary["causeofdeathlabel"] = (
    "Cause of Death",
    u"Causa de Muerte"
    )
  dictionary["includedeceasedlabel"] = (
    "Include Deceased",
    u"Incluir fallecidos"
    )
  dictionary["createvaccinationappointmentbutton"] = (
    ("Create Appointment", "Create an appointment for this vaccination"),
    (u"Crear Cita", u"Fijar una cita para esta vacunación")
    )
  dictionary["generatevaccinationcsvbutton"] = (
    ("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
    (u"Crear un archivo CSV", u"Crear y guardar un archivo CSV en el disco. Éste puede ser usado en la mayorí­a de los procesadores de texto para crear una lista de correo")
    )
  dictionary["csvsavedtolabel"] = (
    "CSV file saved to",
    u"Archivo CSV guardado en"
    )
  dictionary["versiontablenotfoundquestion"] = (
    "Version table not found, create it now?",
    u"No se ha encontrado la versión de tabla ¿crearla ahora?"
    )
  dictionary["versionupdatequestion1"] = (
    "You are attempting to run evette",
    u"¿Desea ejecutar Evette?"
    )
  dictionary["versionupdatequestion2"] = (
    "your database is version",
    u"La versión de su Base de Datos es"
    )
  dictionary["versionupdatequestion3"] = (
    "Would you like to upgrade your database?",
    u"¿Desea  actualizar la base de Datos de Evette?"
    )
  dictionary["resetdatabasequestion"] = (
    "Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
    u"¿Está seguro de querer borrar todas las Tablas? ¡SE PERDERÁN TODOS LOS DATOS!"
    )
  dictionary["alltablesresetmessage"] = (
    "All tables have been reset!",
    u"¡Todas las tablas fueron borradas!"
    )
  dictionary["addstafflabel"] = (
    "Add staff?",
    u"¿Agregar Personal?"
    )
  dictionary["vetslabel"] = (
    "Vets",
    u"Doctores"
    )
  dictionary["nurseslabel"] = (
    "Nurses",
    u"Enfermeros"
    )
  dictionary["otherslabel"] = (
    "Others",
    u"Otros"
    )
  dictionary["nextmonthtooltip"] = (
    "Show next month",
    u"Visualizar próximo mes"
    )
  dictionary["previousmonthtooltip"] = (
    "Show previous month",
    u"Visualizar mes anterior"
    )
  dictionary["backtocalendartooltip"] = (
    "Back to calendar",
    u"Volver al calendario"
    )
  dictionary["addstafftodailyrotatooltip"] = (
    "Add a member of staff to this days rota",
    u"Agregar personal al calendario de turnos"
    )
  dictionary["deleterotaitemtooltip"] = (
    "Delete this rota entry",
    u"Borrar este Turno"
    )
  dictionary["submitrotaitemtooltip"] = (
    "Submit this rota entry",
    u"Agregar este Turno"
    )
  dictionary["vetpositiontitle"] = (
    "Vet",
    u"Doctor/a"
    )
  dictionary["groomerpositiontitle"] = (
    "Groomer",
    u"Peluquero/a"
    )
  dictionary["vetnursepositiontitle"] = (
    "Nurse",
    u"Enfermero/a"
    )
  dictionary["managerpositiontitle"] = (
    "Manager",
    u"Encargado/a"
    )
  dictionary["errorlabel"] = (
    "Sorry, the following error has occured",
    u"Lo siento, ha ocurrido el siguiente error"
    )
  dictionary["editdiarytoolbar"] = (
    ("Edit Diary", "Edit the diary"),
    (u"Editar Diario", u"Editar el Diario")
    )
  dictionary["editdiarypagetitle"] = (
    "Edit Diary",
    u"Editar Diario"
    )
  dictionary["notesuptolabel"] = (
    "Up to",
    u"Hasta"
    )
  dictionary["subjectcontainslabel"] = (
    "Subject contains",
    u"Tema contiene"
    )
  dictionary["notecontainslabel"] = (
    "Note contains",
    u"Contenido de las Aclaraciones"
    )
  dictionary["showremovedlabel"] = (
    "Include removed",
    u"Incluir borrados"
    )
  dictionary["subjectlabel"] = (
    "Subject",
    u"Tema"
    )
  dictionary["notelabel"] = (
    "Note",
    u"nota"
    )
  dictionary["removedlabel"] = (
    "Removed",
    u"Borrado"
    )
  dictionary["linklabel"] = (
    "Link",
    u"Ví­nculo"
    )
  dictionary["clientlabel"] = (
    "Client",
    u"Cliente"
    )
  dictionary["animallabel"] = (
    "Animal",
    u"Mascota"
    )
  dictionary["opentargetrecordtooltip"] = (
    "Open the record linked to this diary note",
    u"Abra la ficha ligada a esta nota del Diario"
    )
  dictionary["diarynotelabel"] = (
    "Diary Note",
    u"nota del Diario"
    )
  dictionary["confirmdeletediarynotemessage"] = (
    "Are you sure that you want to delete this diary note?",
    u"¿Está seguro de borrar esta nota del Diario?"
    )
  dictionary["nolinklabel"] = (
    "No Link",
    u"No existe el Ví­nculo"
    )
  dictionary["createassociateddiarynotetooltip"] = (
    "Create a diary note associated with this record",
    u"Crear una nota en el Diario asociada con esta ficha"
    )
  dictionary["newdiarynotetooltip"] = (
    "Create a new diary note",
    u"Crear una nueva nota en el Diario"
    )
  dictionary["editdiarynotetooltip"] = (
    "Edit the selected diary note",
    u"Editar la nota seleccionada en el Diario"
    )
  dictionary["deletediarynotetooltip"] = (
    "Delete the selected diary note",
    u"Borrar la nota del Diario seleccionada"
    )
  dictionary["refreshdiarytooltip"] = (
    "Refresh the list of diary notes",
    u"Actualizar la lista notas del Diario"
    )
  dictionary["cleardiarytooltip"] = (
    "Clear the diary filters",
    u"Borrar los filtros del Diario"
    )
  dictionary["clientolderthanservermessage"] = (
    "You are trying to run an out-of-date client, please upgrade to continue",
    u"Usted está tratando de usar un servidor fuera de fecha, por favor, actualícelo para poder continuar"
    )
  dictionary["adddiarynotes"] = (
    "Add to diary",
    u"Agregar al Diario"
    )
  dictionary["editdiarynotes"] = (
    "Edit diary",
    u"Editar el Diario"
    )
  dictionary["deletediarynotes"] = (
    "Delete from diary",
    u"Borrar del Diario"
    )
  dictionary["diarylabel"] = (
    "Diary",
    u"Diario"
    )
  dictionary["viewlicensemenu"] = (
    ("View License", "View the license for this software."),
    (u"Ver Licencia", u"Ver la licencia de este software")
    )
  dictionary["licenselabel"] = (
    "License",
    u"Licencia"
    )
  dictionary["aboutlabel"] = (
    "About",
    u"Acerca de"
    )
  dictionary["attachedfileslabel"] = (
    "Attached Files",
    u"Archivos adjuntos"
    )
  dictionary["deleteattachedfileconfirm"] = (
    "Are you sure that you want to delete this file?",
    u"¿Está seguro de borrar este archivo?"
    )
  dictionary["addnewmediatooltip"] = (
    "Add a new external file to this record",
    u"Agregar un archivo externo nuevo a esta ficha"
    )
  dictionary["replacemediatooltip"] = (
    "Update the description of the selected file",
    u"Actualizar la descripción del archivo seleccionado"
    )
  dictionary["deletemediatooltip"] = (
    "Delete the selected file",
    u"Borrar el archivo seleccionado"
    )
  dictionary["savemediatooltip"] = (
    "Save the selected file to disk",
    u"Guardar el archivo seleccionado al disco"
    )
  dictionary["fileassociationspagetitle"] = (
    "File Associations",
    u"Asociaciones de archivos"
    )
  dictionary["extensionlabel"] = (
    "Extension",
    u"Extensión"
    )
  dictionary["programlabel"] = (
    "Program",
    u"Programa"
    )
  dictionary["fileassociationexistsmessage"] = (
    "There is already a program associated with this file extension!",
    u"Ya hay un programa asociado con esta extensión de archivo"
    )
  dictionary["deleteassociationconfirm"] = (
    "Are you sure that you want to delete this file association?",
    u"¿Está seguro de borrar esta asociación de archivo?"
    )
  dictionary["noprogramassociatedmessage"] = (
    "There is no program associated with this file type!\nTo associate a program with this file type, choose \"File Associations\" from the \"Settings Menu\"",
    u"¡No hay un programa asociado con este tipo de archivo!\nPara asociar un programa a este tipo de archivo, elija \"Asociación de Archivos\" desde el \"Menú de Configuración\""
    )
  dictionary["mediatoolargemessage"] = (
    "This file is too large to attach!",
    u"Este archivo es muy grande para adjuntarlo"
    )
  dictionary["weightpanelpagetitle"] = (
    "Weight",
    u"Peso"
    )
  dictionary["deleteweighttooltip"] = (
    "Delete the selected weight",
    u"Borrar el peso seleccionado"
    )
  dictionary["deleteweightconfirm"] = (
    "Are you sure that you want to delete this weight?",
    u"¿Está seguro de borrar este peso?"
    )
  dictionary["samelabel"] = (
    "Same",
    u"Igual"
    )
  dictionary["reorderlabel"] = (
    "Minimum",
    u"Mínimo"
    )
  dictionary["runninglowlabel"] = (
    "Running Low?",
    u"Pocos?"
    )
  dictionary["diarymenu"] = (
    "&Diary",
    u"Agenda"
    )
  dictionary["fileaccosiationmenu"] = (
    ("File Associations", "Edit the external applications associated with attached files"),
    (u"Asociaciones de Archivos", u"Editar las aplicaciones externas asociadas con los archivos adjuntos")
    )
  dictionary["clientanimalsearchtooltip"] = (
    "If you wish to filter the animals by name, enter the name here",
    u"Si desea realizar la búsqueda de las Mascotas por su nombre, escriba el nombre aquí­"
    )
  dictionary["browseappointmentsmenu"] = (
    ( "Browse Appointments", "Browse all appointments" ),
    ( u"Calendario de Citas", u"Mirar todas las Citas" )
    )
  dictionary["browseappointmentspagetitle"] = (
    "Browse Appointments",
    u"Calendario de Citas"
    )
  dictionary["appointmentlabel"] = (
    "appointment",
    u"cita"
    )
  dictionary["operationlabel"] = (
    "operation",
    u"cirugía"
    )
  dictionary["groominglabel"] = (
    "grooming",
    u"peluquería"
    )
  dictionary["januarylabel"] = (
    "January",
    u"Enero"
    )
  dictionary["februarylabel"] = (
    "February",
    u"Febrero"
    )
  dictionary["marchlabel"] = (
    "March",
    u"Marzo"
    )
  dictionary["aprillabel"] = (
    "April",
    u"Abril"
    )
  dictionary["maylabel"] = (
    "May",
    u"Mayo"
    )
  dictionary["junelabel"] = (
    "June",
    u"Junio"
    )
  dictionary["julylabel"] = (
    "July",
    u"Julio"
    )
  dictionary["augustlabel"] = (
    "August",
    u"Agosto"
    )
  dictionary["septemberlabel"] = (
    "September",
    u"Septiembre"
    )
  dictionary["octoberlabel"] = (
    "October",
    u"Octubre"
    )
  dictionary["novemberlabel"] = (
    "November",
    u"Noviembre"
    )
  dictionary["decemberlabel"] = (
    "December",
    u"Diciembre"
    )
  dictionary["monthnames"] = (
    (dictionary["januarylabel"][0], dictionary["februarylabel"][0], dictionary["marchlabel"][0], dictionary["aprillabel"][0], dictionary["maylabel"][0], dictionary["junelabel"][0], dictionary["julylabel"][0], dictionary["augustlabel"][0], dictionary["septemberlabel"][0], dictionary["octoberlabel"][0], dictionary["novemberlabel"][0], dictionary["decemberlabel"][0]),
    (dictionary["januarylabel"][1], dictionary["februarylabel"][1], dictionary["marchlabel"][1], dictionary["aprillabel"][1], dictionary["maylabel"][1], dictionary["junelabel"][1], dictionary["julylabel"][1], dictionary["augustlabel"][1], dictionary["septemberlabel"][1], dictionary["octoberlabel"][1], dictionary["novemberlabel"][1], dictionary["decemberlabel"][1])
  )
  dictionary["readfileassociationhelpmessage"] = (
    "To learn about file associations - visit the help section.",
    u"Para saber más sobre asociaciones de archivos, visite la sección de ayuda"
    )
  dictionary["websitelabel"] = (
    "Website",
    u"Sitio Web"
    )
  dictionary["generateinvoicelabel"] = (
    "Generate a printable invoice for this client",
    u"Generar una factura imprimible para este cliente"
    )
  #######################1.2.1#############################
  dictionary["animalformsmenu"] = (
    ("Animal Forms", "Create or edit forms that be generated using an animal's details"),
    (u"Formulario Mascota", u"Crear o editar formularios a partir de las caracterí­sticas de la Mascota")
    )
  dictionary["clientformsmenu"] = (
    ("Client Forms", "Create or edit forms that be generated using an client's details"),
    (u"Formularios de Cliente", u"Crear o editar formularios a partir de los datos del Cliente")
    )
  dictionary["animalformspagetitle"] = (
    "Animal Forms",
    u"Formularios de Mascotas"
    )
  dictionary["clientformspagetitle"] = (
    "Client Forms",
    u"Formularios de Clientes"
    )
  dictionary["previewlabel"] = (
    "Preview",
    u"Anterior"
    )
  dictionary["wordkeyslabel"] = (
    "Wordkeys",
    u"Palabra Clave"
    )
  dictionary["invoiceformsmenu"] = (
    ("Invoice Forms", "Edit the invoice templates"),
    (u"Formulario Factura", u"Editar los modelos de Factura")
    )
  dictionary["editinvoicepagetitle"] = (
    "Edit Invoices",
    u"Editar Factura"
    )
  dictionary["medicationformsmenu"] = (
    ("Medication Forms", "Edit the medication templates"),
    (u"Formularios de Medicamentos", u"Editar las plantillas de medicamentos")
    )
  dictionary["editmedicationtformspagetitle"] = (
    "Medication Forms",
    u"Formularios de Medicamentos"
    )
  dictionary["invoicespagetitle"] = (
    "Invoices",
    u"Facturas"
    )
  dictionary["newinvoicetooltip"] = (
    "Create a new invoice",
    u"Crear una nueva Factura"
    )
  dictionary["editinvoicetooltip"] = (
    "Edit the selected invoice",
    u"Editar la factura seleccionada"
    )
  dictionary["deleteinvoicetooltip"] = (
    "Delete the selected invoice",
    u"Borrar la factura seleccionad"
    )
  dictionary["invoiceoverlapmessage"] = (
    "Invoices are not allowed to overlap, please adjust the dates",
    u"Las Facturas no pueden superponerse, por favor revise las fechas"
    )
  dictionary["clientgenerateformtooltip"] = (
    "Generate a form using this clients details",
    u"Generar un formulario usando los datos de estos clientes"
    )
  dictionary["randomdatawarningmessage"] = (
    "Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
    u"Nota: Deberá cerrar Evette cuando este proceso haya finalizado, \nPor favor inicie Evette otra vez para ver los resultados"
    )
  dictionary["invoiceidlabel"] = (
    "Invoice ID",
    u"Número de Factura"
    )
  dictionary["paidlabel"] = (
    "paid",
    u"Pagado"
    )
  dictionary["unpaidlabel"] = (
    "unpaid",
    u"No Pago"
    )
  dictionary["invoiceidchoicetooltip"] = (
    "Choose an invoice ID to mark an invoice as paid.",
    u"Identifique la factura para marcala como pagada"
    )
  dictionary["editpaymentinvoicetooltip"] = (
    "Edit the amount paid on the selected invoice.",
    u"Escriba la cantidad pagada en la factura seleccionada"
    )
  dictionary["editinvoicepaymenttitle"] = (
    "Edit payment",
    u"Modificar el pago"
    )
  dictionary["editanimaltooltip"] = (
    "Edit Animal",
    u"Editar la Mascota"
    )
  ###################1.2.2#####################
  dictionary["stocklabel"] = (
    "Stock",
    u"Existencias"
    )
  dictionary["editstockmenu"] = (
    ("Edit Stock", "Edit Stock"),
    ("Editar existencias", "Editar existencias")
    )
  dictionary["batchsearchmenu"] = (
    ("Batch Search", "Show movements for a specific batch number"),
    ("Búsqueda de Lote", "Mostrar los movimientos para un número de lote especí­fico")
    )
  dictionary["batchbreakdowntooltip"] = (
    "View a breakdown of the current stock by batch number",
    u"Ver el fallo en el las existencias actuales por número de lote"
    )
  dictionary["editmovementlabel"] = (
    "Edit Movement",
    u"Editar movimiento"
    )
  dictionary["createmovementlabel"] = (
    "Create Movement",
    u"Crear Movimiento"
    )
  dictionary["consumablelabel"] = (
    "Consumable",
    u"Consumible"
    )
  dictionary["shoplabel"] = (
    "Shop",
    u"Tienda"
    )
  dictionary["procedurelabel"] = (
    "Procedure",
    u"Procedimiento"
    )
  dictionary["manuallabel"] = (
    "Manual",
    u"Manual"
    )
  dictionary["prescribemedicationlabel"] = (
    "Prescribe Medication",
    u"Prescribir Medicamento"
    )
  dictionary["quantitylabel"] = (
    "Quantity",
    u"Cantidad"
    )
  dictionary["quantityerrormessage"] = (
    "Invalid quantity",
    u"Cantidad Inválida"
    )
  dictionary["viewinvoicetooltip"] = (
    "View Invoice",
    u"Ver Factura"
    )
  dictionary["diagnosislabel"] = (
    "Diagnosis",
    u"Diagnóstico"
    )
  dictionary["createreceiptitemtooltip"] = (
    "Create a receipt item",
    u"Crear un recibo para este artículo"
    )
############################## 1.2.3 ###############################################
  dictionary["editkennelsmenu"] = (
    ("Edit Kennels", "Edit kennels available"),
    (u"Editar Caniles", u"Editar Caniles Disponibles")
    )
  dictionary["viewkennelsmenu"] = (
    ("View Kennels", "View Kennels"),
    (u"Ver Caniles", u"Ver Caniles")
    )
  dictionary["kennelsmenu"] = (
    "&Kennels",
    u"&Caniles"
    )
  dictionary["kennelblocktitlelabel"] = (
    "Caniles",
    u"Caniles"
    )
  dictionary["kennelstitlelabel"] = (
    "Kennels",
    u"Caniles"
    )
  dictionary["editkennelblocktitle"] = (
    "Edit kennel block",
    u"Modificar Caniles"
    )
  dictionary["deletekennelblockconfirmation"] = (
    "Are you sure that you want to delete this kennel block?",
    u"¿Está seguro de borrar este canil?"
    )
  dictionary["deletekennelconfirmation"] = (
    "Are you sure that you want to delete this kennel?",
    u"¿Está seguro de borrar este canil?"
    )
  dictionary["editkenneltitle"] = (
    "Edit kennel",
    u"Editar Canil"
    )
  dictionary["stayinglabel"] = (
    "Staying",
    u"Hospadaje"
    )
  dictionary["occupiedlabel"] = (
    "occupied",
    u"Ocupado"
    )
  dictionary["vacantlabel"] = (
    "vacant",
    u"Libre"
    )
  dictionary["changeownershiptooltip"] = (
    "Transfer ownership of this animal",
    u"Cambiar el Dueño de esta Mascota"
    )
  dictionary["choosenewownerdialogtitle"] = (
    "Choose new owner",
    u"Seleccionar nuevo Dueñ"
    )
  dictionary["doubleclicktoselecttooltip"] = (
    "Double click to select",
    u"Doble click para seleccionar"
    )
  dictionary["importasmanimaltooltip"] = (
    "Create an animal record from an ASM record",
    u"Crear una ficha de la mascota para una base ASM"
    )
  dictionary["chooseananimaltitle"] = (
    "Choose an animal",
    u"Elegir una mascota"
    )
  dictionary["clientrefnolabel"] = (
    "Reference Number",
    u"Número de referencia"
    )
  dictionary["toomanyresultsmessage"] = (
    "Your search produced too many results to display, please narrow down your search",
    u"Su búsqueda provocó demasiados resultados para ser mostrados, por favor restrinja su búsqueda"
    )
  dictionary["idlelabel"] = (
    "Idle",
    u"En espera"
    )
  dictionary["connectinglabel"] = (
    "Connecting",
    u"Conectando"
    )
  dictionary["connectedlabel"] = (
    "Connected",
    u"Conectado"
    )
  dictionary["errorlabel"] = (
    "Error",
    u"Error"
    )
  dictionary["usernamepassworderrormessage"] = (
    "Unsuccessful Login",
    u"Conexión Fallida"
    )
  dictionary["successfulloginmessage"] = (
    "Successful Login",
    u"Conexión exitosa"
    )
  dictionary["creatingevettefolder"] = (
    "Creating Evette folder",
    u"Creando carpeta Evette"
    )
  dictionary["evettedatabasecreatedmessage"] = (
    "Created Evette database",
    u"Creando base de datos Evette"
    )
  dictionary["errorcreatingdatabasemessage"] = (
    "Error creating Evette database",
    u"Error al Crear base de datos Evette"
    )
  dictionary["asmimportmenu"] = (
    ("ASM Import", "Import an animal from ASM"),
    (u"Importar desde ASM", u"Importar los datos de una mascota desde ASM")
    )
  dictionary["errorobtainingownermessage"] = (
    "Unable to find owner",
    u"No se pudo encontrar al dueño"
    )
  dictionary["alreadyimportedmessage"] = (
    "This animal has already been imported. Would you like to view it?",
    u"Este animal ya se ha importado. ¿Desea abrir la ficha?"
    )
  dictionary["addweighttooltip"] = (
    "Add Weight",
    u"Agregar el Peso"
    )
  dictionary["editweightlabel"] = (
    "Edit Weight",
    )
  dictionary["adduserlabel"] = (
    "Add User",
    u"Agregar Usuario"
    )
  dictionary["edituserlabel"] = (
    "Edit User",
    u"Editar Usuario"
    )
  dictionary["editreasonsmenu"] = (
    ("Edit Reasons", "Edit common appointment reasons"),
    (u"Editar Razones", u"Editar las razones comunes de las citas")
    )
  dictionary["doubleclickforreasonstooltip"] = (
    "Double click for a choice of common appointment reasons",
    u"Doble click para abrir la Seleccion de razones comunes para citas"
    )
  dictionary["filemenu"] = (
    "File",
    u"Archivo"
    )
  dictionary["fileexitmenu"] = (
    ("Exit", "Exit Evette"),
    (u"Salir", u"Salir de Evette")
    )
  dictionary["fileclosewindowsmenu"] = (
    ("Close All Panels", "Close all open panels"),
    (u"Cerrar Todos los Paneles", u"Cerrar Todos los Paneles abiertos")
    )
  dictionary["confirmcloseallwindowsmessage"] = (
    ("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
    (u"¿Está seguro de Cerrar Todos los Paneles abiertos? Los datos no guardados se perderán.")
    )
  dictionary["locationlabel"] = (
    "Location",
    u"Ubicación"
    )
  dictionary["editprocedurelabel"] = (
    "Edit Procedure",
    u"Modificar Procedimientos"
    )
############################## 1.2.4 ###############################################
  dictionary["addlookuptooltip"] = (
    "Create a new lookup",
    u"Efectuar una Nueva Búsqueda"
    )
  dictionary["malelabel"] = (
    "Male",
    u"Macho"
    )
  dictionary["femalelabel"] = (
    "Female",
    u"Hembra"
    )
  dictionary["unknownlabel"] = (
    "Unknown",
    u"Desconocido"
    )
  dictionary["dayslabel"] = (
    "days",
    u"días"
    )
  dictionary["weekslabel"] = (
    "weeks",
    u"semanas"
    )
  dictionary["monthslabel"] = (
    "months",
    u"meses"
    )
  dictionary["yearslabel"] = (
    "years",
    u"años"
    )
  dictionary["invaliddobtooltip"] = (
    "Invalid DOB",
    u"Fecha de Nacimiento inválida"
    )
  dictionary["addkennelblocktooltip"] = (
    "Create a new kennel block",
    u"Crear un nuevo canil"
    )
  dictionary["addkenneltooltip"] = (
    "Create a new kennel",
    u"Crear un nuevo sector de caniles"
    )
############################## 1.2.5 ###############################################
  dictionary["asmclientimportmenu"] = (
    ("ASM Client Import", "Import a client from ASM"),
    (u"Importar cliente desde ASM", u"Importar Cliente desde ASM")
    )
  dictionary["chooseclientlabel"] = (
    "Choose client",
    u"Elegir Cliente"
    )
  dictionary["datectrltooltip"] = (
    "Double click to choose from a calendar",
    u"Doble Click para seleccionar desde el calendario"
    )
  dictionary["choosedatetitle"] = (
    "Choose a date",
    u"Elegir la fecha"
    )
  dictionary["editappointmentlabel"] = (
    "Edit Appointment",
    u"Editar Cita"
    )
  dictionary["agelabel"] = (
    "Age",
    u"Edad"
    )
  dictionary["addvaccinationtooltip"] = (
    "Add Vaccination",
    u"Agregar vacunación"
    )
  dictionary["printtooltip"] = (
    "Print",
    u"Imprimir"
    )
############################## 1.2.6 ###############################################
  dictionary["filealteredmessage"] = (
    "Another user has altered this file since you opened it. Please close this record and try again.",
    u"Otro usuario ha modificado este archivo desde que usted lo abrió. Por favor cierre esta ficha e inténtelo nuevamente "
    )
  dictionary["asmreflabel"] = (
    "ASM Ref",
    u"ASM Ref"
    )
  dictionary["deselectlabel"] = (
    "Deselect",
    u"Desmarcar"
    )
  dictionary["createappointmentlabel"] = (
    "Create Appointment",
    u"Crear cita"
    )
  dictionary["multiplepanellabel"] = (
    "Allow multiple panels open",
    u"Permitir múltiples paneles abiertos"
    )
  dictionary["filealteredchoice"] = (
    "Another user has altered this file since you opened it. Would you like to force through your changes?",
    u"Otro usuario ha modificado este archivo desde que usted lo abrió. ¿Desea que los cambios de Ud. prevalezcan?"
    )
  dictionary["latelabel"] = (
    "Late",
    u"Tarde"
    )
  dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
    "mins",
    u"min"
    )
  dictionary["microchiplabel"] = (
    "Microchip",
    u"Microchip"
    )
  dictionary["microchippedlabel"] = (
    "Microchip implanted",
    u"Implantación de Microchip"
    )
  dictionary["costpricelabel"] = (
    "Cost Price",
    u"Precio de Costo"
    )
  dictionary["viewvetnoteslabel"] = (
    "View Vet Notes",
    u"Ver Notas Veterinarias"
    )
  dictionary["appointmentsummarylistboxtooltip"] = (
    "Right click to view available vets\nDouble click to choose time slot",
    u"Click Derecho para ver Veterinarios disponibles\nDoble click para seleccionar la franja horaria"
    )
############################## 1.2.7 ###############################################
  dictionary["shopsalemenuitem"] = (
    "Shop Sale",
    u"Venta de Salón"
    )
  dictionary["shopitemstitle"] = (
    "Shop Items",
    u"Artículos del Salón"
    )
  dictionary["basketlabel"] = (
    "Basket",
    u"Carrito"
    )
  dictionary["putbacktooltip"] = (
    "Put back",
    u"Devolver"
    )
  dictionary["addtobaskettooltip"] = (
    "Add to basket",
    u"Agregar al Carrito"
    )
  dictionary["clientmergetooltip"] = (
    "Merge another client into this one",
    u"Unificar otro cliente con este cliente"
    )
  dictionary["clientsmergedmessage"] = (
    "Clients merged",
    u"Clientes unificados"
    )
  dictionary["subtractlabel"] = (
    "Subtract",
    u"Sustraer"
    )
  dictionary["editmarkupmenu"] = (
    ("Define Markup Rules", "Define Markup Rules"),
    (u"Definir criterios para calcular precios", u"Definir reglas para calcular precios")
    )
  dictionary["multiplybylabel"] = (
    "Multiply by",
    u"Multiplicar por"
    )
  dictionary["roundtolabel"] = (
    "Round up to",
    u"Redondear a "
    )
  dictionary["costpriceentrytooltip"] = (
    "This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
    u"Este valor no está incluido en su configuración"
    )
  dictionary["invalidpricemessage"] = (
    "Invalid Price!",
    u"Precio inválido"
    )
  dictionary["priceinpenniestooltip"] = (
    "Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
    u"Por favor ingrese los redondeos con centavos ej. \"50\" para redondear a los siguientes 50 centavos;  \"100\" para redondear al próximo peso."
    )
  dictionary["customerpricelabel"] = (
    "Customer Price",
    u"Precio al Público"
    )
  dictionary["submitsettingstooltip"] = (
    "Submit settings",
    u"Guardar Configuración"
    )
  dictionary["applymarkuptostocktooltip"] = (
    "Apply the current markup settings to all stock.",
    u"Aplicar esta regla de precios a todo el stock"
    )
  dictionary["markupappliedtoallmessage"] = (
    "Markup applied to all prices",
    u"Regla de precios aplicada a todo el stock"
    )
  dictionary["automarkupconfirmmessage"] = (
    "Continuing will alter all of your public prices, are you sure that you want to continue?",
    u"Continuar con esta acción modificará todos los precios al público. ¿Está seguro de continuar?"
    )
  dictionary["unitpricentrytooltip"] = (
    "Type \"a\" to autogenerate a price from markup rules.",
    u"Escriba \"a\" para generar el precio a partir de las reglas"
    )
  dictionary["costpricentrytooltip"] = (
    "Type \"c\" for help calculating the cost price.",
    u"Escriba \"c\" para obtener ayuda en el cálculo de los precios de costo"
    )
  dictionary["calculatecostpricetitle"] = (
    "Calculate Cost Price",
    u"Calcular precio de costo"
    )
  dictionary["packpricelabel"] = (
    "Price per pack",
    u"Precio por bulto"
    )
  dictionary["unitsperpacklabel"] = (
    "Units per pack",
    u"Unidades por bulto"
    )
############################## 1.2.8 ###############################################
  dictionary["phonenumbertooltip"] = (
    "CTRL + P to toggle public availability.",
    u"CTRL + P para cambiar la visibilidad al público"
    )
  dictionary["lostanimallabel"] = (
    "Lost Animal",
    u"Mascota Perdida"
    )
  dictionary["foundanimallabel"] = (
    "Found Animal",
    u"Mascota Encontrada"
    )
  dictionary["lostandfoundmenu"] = (
    ("Lost and Found", "View/Edit Lost and Found"),
    (u"Perdidos y Encontrados", u"Ver/Editar Perdidos y Encontrados")
    )
  dictionary["lostlabel"] = (
    "Lost",
    u"Perdido"
    )
  dictionary["foundlabel"] = (
    "Found",
    u"Encontrado"
    )
  dictionary["datelostlabel"] = (
    "Date Lost",
    u"Fecha de desaparición"
    )
  dictionary["datefoundlabel"] = (
    "Date Found",
    u"Encontrado el día..."
    )
  dictionary["furlengthlabel"] = (
    "Fur Length",
    u"Largo del pelo"
    )
  dictionary["longlabel"] = (
    "Long",
    u"Largo"
    )
  dictionary["shortlabel"] = (
    "Short",
    u"Corto"
    )
  dictionary["fluffylabel"] = (
    "Fluffy",
    u"Esponjoso (acolchado)"
    )
  dictionary["hairlesslabel"] = (
    "Hairless",
    u"Pelado"
    )
  dictionary["sizelabel"] = (
    "Size",
    u"Tamaño"
    )
  dictionary["largelabel"] = (
    "Large",
    u"Grande"
    )
  dictionary["mediumlabel"] = (
    "Medium"
    u"Mediano"
    )
  dictionary["smalllabel"] = (
    "Small",
    u"Chico"
    )
  dictionary["juvenilelabel"] = (
    "Juvenile",
    u"Joven"
    )
  dictionary["adultlabel"] = (
    "Adult",
    u"Adulto"
    )
  dictionary["elderlylabel"] = (
    "Elderly",
    u"Anciano"
    )
  dictionary["temperamentlabel"] = (
    "Temperament",
    u"Carácter"
    )
  dictionary["friendlylabel"] = (
    "Friendly",
    u"Amistoso"
    )
  dictionary["timidlabel"] = (
    "Timid",
    u"Tímido"
    )
  dictionary["aggressivelabel"] = (
    "Aggressive",
    u"Agresivo"
    )
  dictionary["collarlabel"] = (
    "Collar",
    u"Collar"
    )
  dictionary["collardescriptiontooltip"] = (
    "Collar description",
    u"Descripción del Collar"
    )
  dictionary["arealabel"] = (
    "Area",
    u"Barrio"
    )
  dictionary["areatooltip"] = (
    "Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
    u"Introduzca barrios y/o códigos postales, ciudades y/o estados separados por espacios"
    )
  dictionary["datecompletelabel"] = (
    "Date complete",
    u"Fecha Completa"
    )
  dictionary["savetooltip"] = (
    "Save",
    u"Guardar"
    )
  dictionary["contacttooltip"] = (
    "Contact",
    u"Contacto"
    )
  dictionary["completelabel"] = (
    "Complete",
    u"Completo"
    )
  dictionary["idlabel"] = (
    "ID",
    u"Identificación"
    )
  dictionary["rightclickformenutooltip"] = (
    "Right click for available options.",
    u"Click derecho para opciones"
    )
  dictionary["lostandfoundsearchtooltip"] = (
    "Search for a match",
    u"Buscar coincidencias"
    )
  dictionary["searchuptolabel"] = (
    "Search ceiling",
    u"Límite superior de la búsqueda"
    )
  dictionary["searchfromlabel"] = (
    "Search floor",
    u"Límite inferior de la búsqueda"
    )
  dictionary["alreadyonlostandfoundmessage"] = (
    "This animal is already on the lost and found!",
    u"¡Esa Mascota ya está en Perdidos y Encontrados!"
    )
  dictionary["includecompletelabel"] = (
    "Include complete?",
    u"Incluir completos?"
    )
  dictionary["closelabel"] = (
    "Close",
    u"Cerrar"
    )
  dictionary["scorelabel"] = (
    "Score",
    u"Puntaje"
    )
  dictionary["lostandfoundsearchresultspagetitle"] = (
    "Lost and Found Search Results",
    u"Resultado de la búsqueda en Perdidos y Encontrados"
    )
  dictionary["systemlabel"] = (
    "System",
    u"Sistema"
    )
  dictionary["versionlabel"] = (
    "Version",
    u"Versión"
    )
############################## 1.3 ###############################################
  dictionary["addlostmenu"] = (
    ("Add Lost", "Add a lost animal"),
    (u"Agregar Perdido", u"Agregar una mascota perdida")
    )
  dictionary["addfoundmenu"] = (
    ("Add Found", "Add a found animal"),
    (u"Agregar Encontrado", u"Agregar una mascota encontrada")
    )
  dictionary["alllabel"] = (
    "All",
    u"Todos"
    )
  dictionary["refreshlabel"] = (
    "Refresh",
    u"Actualizar"
    )
  dictionary["filteranimalslabel"] = (
    "Filter Animals",
    u"Filtrar Mascotas"
    )
  dictionary["markaspaidlabel"] = (
    "Mark as paid?",
    u"¿Marcar como pagado?"
    )
############################## 1.3.1 ###############################################
  dictionary["asmshelterlabel"] = (
    "ASM Shelter",
    u"Refugio ASM"
    )
  dictionary["asmsheltertooltip"] = (
    "If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
    u"Si usás el Sistema de Organización de Refugios de Animales podés marcar un cliente como \"El Refugio\" y te permitirá importar registros de Mascotas que no tienen dueño desde ASM."
    )
  dictionary["appointmentrefreshlabel"] = (
    "Appointment Refresh Interval",
    u"Intervalos de Actualizar de Citas"
    )
############################## 1.3.2 ###############################################
  dictionary["asmvaccinationlabel"] = (
    "ASM Vaccination",
    u"Vacunaciones ASM"
    )
  dictionary["asmvaccinationtooltip"] = (
    "Choose which ASM vaccine you would like Evette to use when updating animal records.",
    u"Elegir la vacuna ASM que Evette usará al actualizar la historia clínica de una Mascota"
    )
  dictionary["asmerrormessage"] = (
    "Unable to update ASM record!",
    u"No se pudo actualizar el registro ASM"
    )
  dictionary["asmsynctooltip"] = (
    "Sync with ASM record",
    u"Sincronizar con el registro ASM"
    )
  dictionary["fieldlabel"] = (
    "Field",
    u"Campo"
    )
  dictionary["asmsyncbuttontooltip"] = (
    "Sync this field on Evette and ASM records",
    u"Sincronizar este campo en Evette y el registro ASM"
    )
  dictionary["synctoasmlabel"] = (
    "Sync to ASM",
    u"Sincronizar a ASM"
    )
  dictionary["synctoevettelabel"] = (
    "Sync to Evette",
    u"Sincronizar a Evette"
    )
  dictionary["asmconnectionerrormessage"] = (
    "Unable to connect to ASM.",
    u"No se pudo conectar a ASM"
    )
  dictionary["asmdeathreasonlabel"] = (
    "Record updated via ASM.",
    u"Registro Actualizado vía ASM"
    )
  dictionary["evettedeathreasonlabel"] = (
    "Record updated via Evette.",
    u"Registro actualizado vía Evette"
    )
  dictionary["importnewasmownermenuitem"] = (
    "Import new ASM owner",
    u"Importar un nuevo dueño de ASM"
    )
  dictionary["updateownermenuitem"] = (
    "Update current owner",
    u"Actualizar el dueño"
    )
  dictionary["1.3.2updatemessage"] = (
    "Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
    u"Nota: cuando ejecutes los clientes de Evette luego de este upgrade necesitarás reconfigurar la base de datos."
    )
  dictionary["tabbetweenentriestooltip"] = (
    "You can switch between the user and password entries with the TAB key.",
    u"Para cambiar entre las entradas de Usuario y Password, presionar TAB"
    )
  dictionary["dischargelabel"] = (
    "Discharge",
    u"Dar de alta"
    )
  dictionary["overnightstaylabel"] = (
    "Overnight Stay",
    u"Alojamiento nocturno"
    )
  dictionary["animalstayedmessage"] = (
    "This animal has stayed overnight, creating a new vet form.",
    u"Esta Mascota ha permanecido durante la noche, y se ha creado un nuevo formulario veterinraio."
    )
  dictionary["prescriptionfeelabel"] = (
    "Prescription Fee",
    u"Arancel de prescripción de medicamentos"
    )
  dictionary["ontimelabel"] = (
    "On time",
    u"A tiempo"
    )
  dictionary["dnalabel"] = (
    "Did not arrive",
    u"No llegó"
    )
  dictionary["viewlabel"] = (
    "View",
    u"Ver"
    )
  dictionary["renamelabel"] = (
    "Rename",
    u"Renombrar"
    )
  dictionary["filterlabel"] = (
    "Filter",
    u"Filtrar"
    )
  dictionary["programbrowsertooltip"] = (
    "Browse to find an appropriate program.",
    u"Navegar para encontrar el programa apropiado"
    )
  dictionary["agelabel"] = (
    "Age",
    u"Edad"
    )
  dictionary["batchbreakdownlabel"] = (
    "Batch No Breakdown",
    u"Desglose de lote"
    )
  dictionary["returntoshelterlabel"] = (
    "Return to shelter",
    u"Regresar al refugio"
    )
  dictionary["possibleduplicateownermessage"] = (
    "This owner may already be known to the system. Would you like to view the list of similar clients?",
    u"Este dueño podría estar ya en el sistema. ¿Desea ver una lista de los clientes similares?"
    )
  dictionary["asmimportlabel"] = (
    "Imported from ASM",
    u"Importado de ASM"
    )
  
  dictionary["today"] = (
    "Today",
    u"Hoy"
  )
  dictionary["day"] = (
    "Day",
    u"Día"
  )
  dictionary["days"] = (
    "Days",
    u"Días"
  )
  dictionary["dayago"] = (
    "Day ago",
    u"Día atrás"
  )
  dictionary["daysago"] = (
    "Days ago",
    u"Días atrás"
  )
  dictionary["in"] = (
    "In",
    u"En"
  )
  
  dictionary['attachmenttitlelabel'] = (
    "Title",
    u"Título"
  )
  dictionary['attachmentdatelabel'] = (
    "Date",
    u"Fecha"
  )
  dictionary['attachmentsizelabel'] = (
    "Size",
    u"Tamaño"
  )
  
  dictionary["startupsizelabel"] = (
    "App Startup Size",
    u"Tamaño inicial de la aplicación"
  )
  dictionary["startupsizetooltip"] = (
    "App Startup Size. If invalid or empty, app starts maximized.",
    u"Tamaño inicial de la aplicación. Si es inválido o vacío, la applicación inicia maximizada."
  )

  return dictionary
