#!/usr/bin/python
# -*- coding: UTF-8 -*-


#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####French####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Utilisateur"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Mot de passe"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Soumettre"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Total"
		)
	dictionary["fromlabel"] = (
		"From",
		u"De"
		)
	dictionary["tolabel"] = (
		"To",
		u"À"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Prix"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Description"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Oui"
		)
	dictionary["nolabel"] = (
		"No",
		u"Non"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Edition"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Suppression"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"Recherche"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"Remise à zero"
		)
	dictionary["movelabel"] = (
		"Move",
		u"Deplacer"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"Unite"
		)
	dictionary["onlabel"] = (
		"on",
		u"Sur"
		)
	dictionary["namelabel"] = (
		"Name",
		u"Nom"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"Logiciel gratuit de gestion d'une clinique vétérinaire"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"En éditant, vous pouvez modifier l'en-tête"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"Crée par"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Heure"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Operations"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"En cours d'operation"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"Consultation"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Vétérinaire"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Profils de l'animal"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Données du propriétaire"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Reçeu"
		)
	dictionary["problemlabel"] = (
		"Problem",
		u"Problême"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"Notes"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"Plan"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"L'utilisateur à été supprimé"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Changer données"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Position"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Date"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Heure non valide"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Contenus"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Prochaine execution"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Aucun"
		)
	
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"Clients"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"Rendez-vous"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"Traitements"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"Procedures"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"Antecedents"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"Formulaires"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"Personnel"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"Parametres"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"Aide"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Entier"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"sterilisé-castré"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Nouveau Client", u"Créer un nouveau client")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Rechercher Clients", u"Trouver les données d'un client ou d'un animal")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"Voir les rendez-vous", u"Rendez-vous du jour")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"Voir les chirurgies", u"Chirurgie du jour")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Éditer Utilisateur", u"Créer et éditer un utilisateur Evette")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Éditer Planning", u"Éditer un planning")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Éditer traitements", u"Éditer traitements")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Éditer vaccins", u"Éditer vaccins")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Éditer procédures", u"Éditer procédures")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Éditer couleurs", u"Éditer couleurs")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Éditer Races", u"Éditer Races")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Éditer Éspeces", u"Éditer Éspeces")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Éditer formulaires", u"Éditer formulaires")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Éditer parametres", u"Éditer parametres unique à cette clinique")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Données aléatoire", u"Generer des données tests")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Réinicialiser Données", u"Réinicialisation complet de la base de données Evette")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Aide", u"Aide sur Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"À propos de", u"Information sur le programme")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u"Ajouter un client", u"Créer une fiche de nouveau client")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u"Rechercher client", u"Trouver un client ou un animal")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u"Rendez-vous du jour", u"Voir les rendez-vous du jour")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u"Chirurgie du jour", u"Voir les chirurgies du jour")
		)
	
	##Client Panel

	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Nouveau client"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Titre"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"Prénom"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"Nom"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"Code postal"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Téléphone fixe"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Portable"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Téléphone professionnel"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"Email"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Commentaires"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Animaux"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Créer une nouvelle fiche: animal"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Éditer la fiche courante: animal"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Supprimer la fiche courante: animal"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Rafraîchir la liste des animaux"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Prendre un rendez-vous pour l'animal selectionné"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"État de paiement"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Facture detaillée"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"Sauvegarder les changements de données client"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Cette fiche client n'a pas été sauvegardée, êtes-vous sûre de vouloir quitter? "
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Confirmer suppression animal"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Rafraîchir facture"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u"Factures récentes", u"Choix de l'interval de date entre les differentes factures")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Désélectionner facture courante et vider les prix et descriptions"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Soumettre les modifications de la facture séléctionnée"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Supprimer la facture séléctionnée"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Nouvel animal"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Propriétaire"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Éditer cette fiche propriétaire"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Nom"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Sexe"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Espèces"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Race"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Couleurs"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Date de naissance"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"N° de puce ou tatouage"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Commentaire"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"Cocher si l'animal est stérilisé ou castré"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Imprimer un document récapitulatif de l'animal"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Imprimer formulaires utilisant les données de l'animal"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Rendez-vous"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Prendre un rendez-vous pour cet animal"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Éditer le rendez-vous séléctionne"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Rafraîchir la liste de rendez-vous"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Supprimer le rendez-vous séléctionné"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Imprimer le rendez-vous séléctionné"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Formulaire Vétérinaire", u"Éditer le Formulaire Vétérinaire de ce rendez-vous")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Détails du rendez-vous"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Vaccins"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Sauvegarder tout changement dans les données de l'animal"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Cette fiche animal n'a pas été sauvegardée, êtes-vous sûr de vouloir fermer le fichier?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Êtes-vous sûr de supprimer ce rendez-vous"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Réinicialiser l'historique vaccinal"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"Vaccin"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Administré le : "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u" Prochain vaccin prévu le : "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Supprimer le vaccin séléctionné"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Soumettre cette vaccination"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Êtes-vous sûr de vouloir supprimer cette vaccination"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Ne de lot : "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Rendez-vous pour"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Chirurgie pour"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Si ce rendez-vous est pour un vétérinaire en particulier, entrez son nom ici"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Rafraîchir la liste des rendez-vous"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Raison du rendez-vous"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"L'heure du rendez-vous"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"Chirurgie?", u"Cocher la case pour réserver une chirurgie")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Soumettre le rendez-vous"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Supprimer ce rendez-vous"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Statuts"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"Pas arrivé"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"En attente"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Avec le Dr "
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Fait"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Éditer Propriétaire", u"Éditer le fichier client")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Éditer Animal", u"Éditer le fichier animal")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Dendez-vous pour"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Chirurgie pour"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"Ce rendez-vous est avant l'ouverture de la clinique"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"Ce rendez-vous est aprés la fermeture de la clinique"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Format de l'heure invalide, il doit être en HH:MM!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Rechercher Client"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Clients"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"Nom"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Téléphone"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"Code Postal"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"Email"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Vider", u"Vider toutes les données")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Rechercher", u"Faire une recherche")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		"Éditer les données du client séléctionné"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Supprimer les données du client séléctionné"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Animal"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Nom"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Sexe"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Espèce"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"Race"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"N° de puce ou de tatouage"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Commentaires"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Éditer les données de l'animal séléctionné"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Effacer les données de l'animal séléctionné"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Reçu"
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Êtes-vous sûr de vouloir supprimer les données reçu?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Vider les données paiement"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Paiement"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Soumettre paiement"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Paiement"
		)
	
	##Launch panels 
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Fichier Conf introuvable! Voulez-vous en créer un?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Dossier Evette introuvable! Voulez-vous en créer un?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Impossible de se connecter à la base de donnée du serveur! Verifiez qu'elle est installée et active. Voulez-vous ajuster vos données locales?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"Impossible de localiser la base de donnée Evette! Voulez-vous en créer une?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Fichier conf crée"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Dossier Evette crée"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"IP BD"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Utilisateur de BD"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Mots de passe de la BD"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Impossible de créer une base de donnée, verifiez la configuration de votre serveur mysql!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Création de la base de donnée avec succes!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Log in"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Éditer Librairie Couleur"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Éditer Librairie Especes"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Éditer Librairie Race"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Rafraîchir la liste"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Supprimer la librairie séléctionnée"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Soumettre Librairie"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"Cette librairie existe déja"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Nommer cette librairie"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Étes-vous sûr de vouloir supprimer cette librairie"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Éditer traitement"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Edit Medication",
		u"Éditer traitement"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Supprimer le traitement séléctionné"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"N° de lot #"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Générer un rapport montrant tous les mouvements de ce N° de lot"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Imprimer votre stock courant"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Changements de"
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"Étes-vous sûr de vouloir supprimer?"
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Étes-vous sûr de vouloir modifier le traitement?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Mouvement du N° de lot"
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Expire"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Rafraîchir les details du traitement"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Supprimer ce changement de traitement"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Changement"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Étes-vous sûr de vouloir modifier l'hitorique thérapeutique?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Étes-vous sûr de vouloir supprimer l'historique thérapeutique?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Rafraîchir les details du traitement"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Réinitialiser les critères de recherches"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"N° du lot courant"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Prix à l'unite"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"Lundi"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"Mardi"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Mercredi"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"Jeudi"
		)
	dictionary["friday"] = (
		"Friday",
		u"Vendredi"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Samedi"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Dimanche"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Éditer Procédures"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Rafraîchir la liste des procédures"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Supprimer la procédure séléctionnée"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"Donnez un nom à la procédure"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"Étes-vous sûr de vouloir éditer cette procédure?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"Étes-vous sûr de vouloir supprimer cette procédure?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Donnée aléatoire"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"N° clients"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"N° de l'animal"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"N° du rendez-vous"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"N° de chirurgies"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"N° du traitements"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Clients"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Animaux"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"Rendez-vous"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Chirurgies"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Traitements"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Créér des données aléatoires"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Nom de la clinique"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Ouvert de "
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Ouvert jusqu'à"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Temps de la chirurgie"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"Visionneur HTML"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"Visionneur HTML"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Langage"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Éditer Formulaire Vétérinaire"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Éditer Finances"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Montrer la barre de tâche"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"Voir les traces des modifications"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Éditer Parametres"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Éditer Rotation"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Éditer Rotation"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"Membres du personnel"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Supprimer l'utilisateur séléctionné"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Clients"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Animaux"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Rendez-vous"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Traitements"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Clients"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Librairies"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"Formulaires"
		)
	dictionary["userslabel"] = (
		"Users",
		u"Utilisateurs"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"Divers"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"Cocher tout"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"Donné à l'utilisateur TOUTES les permissions. Soyer Prudant!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"Étes-vous sûr de vouloir modifier cet utilisateur"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"Étes-vous sûr de vouloir supprimer cet utilisateur"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Éditer Rotation"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Heure de debut"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"Heure de fin"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Opération en cours"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Aperçu du personnel"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Planning du jour"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Vous devez entrer le nom du vétérinaire"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"Le vétérinaire ne peut pas terminer avant de commencer"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"Cette personne ne peut pas être à 2 endroits à la fois"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"Éditer  Vaccinations"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"Vaccins"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Rafraîchir la liste de vaccinations"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"Supprimer la vaccination séléctionnée"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Imprimer la liste du stock courant"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"Étes-vous sûr de vouloir supprimer cette vaccination?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"Étes-vous sûr de vouloir modifier cette vaccination?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"Rafraîchir les details de cette vaccination"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"Supprimer cet historique de vaccination"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"Étes-vous sûr de vouloir éditer cet historique"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Étes-vous sûr de vouloir supprimer cet historique?"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"Formulaire vétérinaire"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Historique des rendez-vous"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Détails des rendez-vous"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"Traitement"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"Vaccins"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"Procédures"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"Personne???"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"Supprimer cette selection du reçu"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"Marquer ce rendez-vous : complet et terminé"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"Sauvegarder tout changement sur ce formulaire"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"Reçu"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"Étes-vous sûr de vouloir supprimer ce reçu"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"Effacer ce \"Contenus\""
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"Rafraîchir la liste de traitements"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"Entrer la posologie"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"Instructions"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"Voie d'administration"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"Imprimer une étiquette pour ce medicament"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"Entrer le N° du lot ici"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"Rafraîchir la liste de vaccination"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"Rafraîchir la liste de procédures"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"Donner une description"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Voir les rendez-vous"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Voir Chirurgies"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"Marquer ce rendez-vous avec un vétérinaire"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Choisir un vétérinaire"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Organiser la visite du vétérinaire pour ce rendez-vous"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Marquer ce rendez-vous comme arrive"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Marquer ce rendez-vous comme fait"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Éditer Client"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Éditer le dossier clients (ainsi il pourra payer la facture)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"Vétérinaires presents"
		)
	
	
	######################## NEW #################################
	
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Rechercher un rendez-vous"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Rechercher un rendez-vous", u"Trouver un rendez-vous")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Nom de l'animal"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Raison"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Voir Chirurgies"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		"DA "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Mailing", u"Compiler une liste de clients à contacter")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Mailing"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Tous les vaccins"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Toutes les espèces"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Décédé"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Cause du décés"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Inclure les décédés"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Créér un rendez-vous", u"Créér un rendez-vous pour cette vaccination")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"Créér un fichier CSV", u"Créér et sauvegarder un fichier CSV sur le disque pour un mailing sur Word")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"Fichier CSV sauvegardé sur "
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Table : Version introuvable, voulez-vous la créér"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"Voulez-vous ouvrir Evette"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"La version de votre base de donnée est"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Voulez-vous mettre à jour votre base de donnée"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"Etes-vous sûr de vouloir réinitialiser toutes les tables? TOUTES LES DONNÉES VONT ETRE PERDUES!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"Toutes les tables ont été réinitialisées"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Rajouter du personnel?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Vets"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"ASV"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Autres"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Montrer le mois suivant"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Montrer le mois précédent"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Retour au calendrier"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Rajouter un membre du personnel dans ce jour de rotation"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Supprimer cette nouvelle rotation"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Soumettre cette nouvelle rotation"
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"Vétérinaire"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"ASV"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"Manager"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"Erreur"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Éditer Agenda", u"Éditer l'Agenda")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Éditer Agenda"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Jusqu'à"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Contenus du sujet"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Contenus de notes"
		)
	dictionary["showremovedlabel"] = (
		"Include removed",
		u"Inclusion enlevée"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Sujet"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Note"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Enlever"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Lien"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Client"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Animal"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Ouvrir l'enregistrement correspondant à cette note d'agenda"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Note d'agenda"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"Étes-vous sûr de vouloir supprimer cette note d'agenda"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		"Pas de liens"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Créér une note d'agenda associée à cet enregistrement"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Créér une nouvelle note d'agenda"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Éditer la note d'agenda séléctionnée"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Supprimer la note d'agenda séléctionnée"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Rafraîchir la liste des notes d'agenda"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Effacer les filtres d'agenda"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade to continue",
		u"Vous voulez utiliser un client trop ancien, merci de mettre à jour pour continuer"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Rajouter dans l'Agenda"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Éditer Agenda"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Supprimer de l'Agenda"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Agenda"
		)
	#################################################################################################
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Voir License", u"Voir la license de ce programme")
		)
	dictionary["licenselabel"] = (
		"License",
		u"License"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"À propos de"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Fichiers Attachés"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Étes-vous sûr de vouloir supprimer ce fichier"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Rajouter un nouveau fichier à ce dossier"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Mettre à jour la description du fichier séléctionné"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Supprimer le fichier séléctionné"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Sauvergader le fichier séléctionné sur le disque"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Fichier associé"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Extension"
		)
	dictionary["programlabel"] = (
		("Program"),
		("Programme")
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Il y a déja un programme associé à ce type d'extension de fichier!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Étes-vous sûr de vouloir supprimer les dossiers attachés"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		u"Il n'y a pas de programme associé à ce type de fichier!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Ce dossier est trop grand pour être attacher!"
		)
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Poids"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Supprimer le poids sélectionné"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"Etes-vous sûr de supprimer ce poids?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Idem"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Minimum"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"A court de?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Agenda"
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Fichier associé", u"Éditer les associations des fichiers attachés")
		)
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Si vous souhaitez filtrer les animaux par nom , entrer le nom ici"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Parcourir les Rendez-vous", u"Parcourir tous les rendez-vous" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Parcourir les Rendez-vous"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"rendez-vous"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Janvier"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Février"
		)
	dictionary["marchlabel"] = (
		"March",
		u"Mars"
		)
	dictionary["aprillabel"] = (
		"April",
		u"Avril"
		)
	dictionary["maylabel"] = (
		"May",
		u"Mai"
		)
	dictionary["junelabel"] = (
		"June",
		u"Juin"
		)
	dictionary["julylabel"] = (
		"July",
		u"Juillet"
		)
	dictionary["augustlabel"] = (
		"August",
		u"Août"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"Septembre"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Octobre"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"Novembre"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"Décembre"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"Pour en savoir plus sur les associations de fichiers - visitez la section d'aide."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"Site Web"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Générer une version imprimable facture pour ce client"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Fiches Animal", u"Create or edit forms that be generated using an animal's details")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Fiches Client", u"Create or edit forms that be generated using an client's details")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Fiches Animal"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Fiches Client"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Aperçu"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Mots clés"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Formulaire de Facture", u"Edit the invoice templates")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Éditer factures"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Fiches traitement", u"Edit the medication templates")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Fiches traitement"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Factures"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Créer Nouvelle Facture"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Éditer la facture séléctionée"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Suprimer la facture séléctionée"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Les factures ne sont pas autorisés à se chevauchent, s'il vous plaît ajuster les dates"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Générer un formulaire en utilisant les details de ce client"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Note: Evette devra fermer quand ce processus est achevé,\ns'il vous plaît re-lancer evette après pour voir le résultat."
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"ID de la facture"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"Payé"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"Non Payé"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Sélectioner un ID de facture pour la marquer comme payée."
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Modifier le montant payé sur la facture sélectionnée."
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Modifier paiement"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Editer Animal"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Stock"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		(u"Modifier paiement", "Modifier paiement")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("Recherche par N° de lots", "Mentrer les mouvements pour un lot spécifique")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"Voir un breakdown du stock actuel par numéro de lot"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Modifier Mouvement"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Créer Mouvement"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Consommable"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Boutique"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Procédure"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Manuel"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Prescrire des médicaments"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Quantité"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Quantité non valide"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"Voir facture"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnostic"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Créer un point réception"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		("Modifier les Niches", "Editer les niches disponible")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		("Voir les Niches", "Voir les Niches")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		"&Niches"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		"Bloc de Niche"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		"Niches"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		"Modifier le Bloc de niche"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		"êtes-vous sûr de vouloir supprimer ce bloc de niche?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		"êtes-vous sûr de vouloir supprimer cette niche?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		"Modifier niche"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		"Rester"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		"occupés"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		"vacants"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		"Transférer la propriété de cet animal"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		"Choisissez nouveau propriétaire"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		"Double-cliquez pour sélectionner"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		"Crée aun record animal depuis un record ASM"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		"Choisissez un animal"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		"Numéro de référence"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		"Il y'a trop de résultats à afficher, s’il vous plaît affiner votre recherche"
		)
	dictionary["idlelabel"] = (
		"Idle",
		"Idle"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		"Connexion"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		"Connecté"
		)
	dictionary["errorlabel"] = (
		"Error",
		"Erreur"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		"Échec de Connection"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		"Connexion réussi"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		"Créer Evette dossier"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		"base de données Evette Créée"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		"Erreur lors de la création de bases de données Evette"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		("ASM Import", "Importer an animal depuis ASM")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		"Impossible de trouver le propriétaire"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		"Cet animal a déjà été importé. Voulez-vous le voir?"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		"Ajouter Poids"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		"Modifier Poids"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		"Ajouter un utilisateur"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		"Modifier l'utilisateur"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		("Modifier Raisons", "Editer raison commune de RDV")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		"Appointment Reason Lookups"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		"Double-clique pour le choix d'une raison commune de RDV"
		)
	dictionary["filemenu"] = (
		"File",
		"Fichier"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		("Quiter", "Quiter Evette")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		("Fermer tous les panneaux", "Fermer tous les panneaux ouvert")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		("Êtes-vous sûrs de vouloir fermer tous les panneaux ouverts? Toute données non enregistré seront perdues.")
		)
	dictionary["locationlabel"] = (
		"Location",
		"Emplacement"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		"Modifier procédure"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Créer une nouvelle recherche"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Mâle"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Femelle"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"Inconnu"
		)
	dictionary["dayslabel"] = (
		"days",
		u"jours"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"semaines"
		)
	dictionary["monthslabel"] = (
		"months",
		u"mois"
		)
	dictionary["yearslabel"] = (
		"years",
		u"année"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"Date de naissance incorrecte"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Create a new kennel block"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Create a new kennel"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"Importation de client ASM", u"Importer un client depuis ASM")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Choisissez client"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Double-clique pour choisir depuit le calendrier"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Choisissez une date"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"Modifier rendez-vous"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Âge"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Ajouter vaccination"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Imprimer"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Un autre utilisateur a modifié ce fichier depuis que vous l'avez ouvert. S’il vous plaît fermer ce fichier et essayer à nouveau."
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM Ref"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Désélectionner"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Créer rendez-vous"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Permettez l'ouvertur de plusieurs panneaux"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Un autre utilisateur a modifié ce fichier depuis que vous l'avez ouvert. Souhaitez-vous ajouter les Modifications?"
		)
	dictionary["latelabel"] = (
		"Late",
		u"En retard"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"mn"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Tatouage"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Microchip implantés"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Prix d'achat"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"Voir notes du vétérinaire"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Cliquez avec le bouton droit pour voir les vétérinaires \nDouble-clique pour choisir une plage horaire"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
