#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####New Language####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"New Language"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"New Language"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"New Language"
		)
	dictionary["totallabel"] = (
		"Total",
		u"New Language"
		)
	dictionary["fromlabel"] = (
		"From",
		u"New Language"
		)
	dictionary["tolabel"] = (
		"To",
		u"New Language"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"New Language"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"New Language"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"New Language"
		)
	dictionary["nolabel"] = (
		"No",
		u"New Language"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"New Language"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"New Language"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"New Language"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"New Language"
		)
	dictionary["movelabel"] = (
		"Move",
		u"New Language"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"New Language"
		)
	dictionary["onlabel"] = (
		"on",
		u"New Language"
		)
	dictionary["namelabel"] = (
		"Name",
		u"New Language"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"New Language"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"New Language"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"New Language"
		)
	dictionary["timelabel"] = (
		"Time",
		u"New Language"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"New Language"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"New Language"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"New Language"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"New Language"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"New Language"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"New Language"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"New Language"
		)
	dictionary["problemlabel"] = (
		"Diagnosis",
		u"New Language"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"New Language"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"New Language"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"New Language"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"New Language"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"New Language"
		)
	dictionary["datelabel"] = (
		"Date",
		u"New Language"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"New Language"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"New Language"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"New Language"
		)
	dictionary["nonelabel"] = (
		"None",
		u"New Language"
		)
	
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"New Language"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"New Language"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"New Language"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"New Language"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"New Language"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"New Language"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"New Language"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"New Language"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"New Language"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"New Language"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"New Language"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"New Language", u"New Language")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"New Language", u"New Language")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"New Language", u"New Language")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"New Language", u"New Language")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"New Language", u"New Language")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"New Language", u"New Language")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"New Language", u"New Language")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"New Language", u"New Language")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"New Language", u"New Language")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"New Language", u"New Language")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"New Language", u"New Language")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"New Language", u"New Language")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"New Language", u"New Language")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"New Language", u"New Language")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"New Language", u"New Language")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"New Language", u"New Language")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"New Language", u"New Language")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"New Language", u"New Language")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u"New Language", u"New Language")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u"New Language", u"New Language")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u"New Language", u"New Language")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u"New Language", u"New Language")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"New Language"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"New Language"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"New Language"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"New Language"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"New Language"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"New Language"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"New Language"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"New Language"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"New Language"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"New Language"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"New Language"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"New Language"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"New Language"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"New Language"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"New Language"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"New Language"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"New Language"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"New Language"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Bill",
		u"New Language"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"New Language"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"New Language"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"New Language"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"New Language"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u"New Language", u"New Language")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"New Language"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"New Language"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"New Language"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"New Language"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"New Language"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"New Language"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"New Language"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"New Language"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"New Language"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"New Language"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"New Language"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"New Language"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"New Language"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"New Language"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"New Language"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"New Language"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"New Language"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"New Language"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"New Language"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"New Language"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"New Language"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"New Language"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"New Language"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"New Language", u"New Language")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"New Language"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"New Language"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"New Language"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"New Language"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"New Language"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"New Language"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"New Language"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"New Language"
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u"New Language"
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"New Language"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"New Language"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"New Language"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u"New Language"
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"New Language"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"New Language"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"New Language"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"New Language"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"New Language"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"New Language"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"New Language", u"New Language")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"New Language"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"New Language"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"New Language"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"New Language"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"New Language"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"New Language"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"New Language"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"New Language", u"New Language")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"New Language", u"New Language")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"New Language"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"New Language"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"New Language"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"New Language"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"New Language"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"New Language"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"New Language"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"New Language"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"New Language"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"New Language"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"New Language"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"New Language"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"New Language", u"New Language")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"New Language", u"New Language")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"New Language"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"New Language"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"New Language"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"New Language"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"New Language"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"New Language"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"New Language"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"New Language"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"New Language"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"New Language"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"New Language"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"New Language"
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"New Language"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"New Language"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"New Language"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"New Language"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"New Language"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"New Language"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"New Language"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"New Language"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"New Language"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"New Language"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"New Language"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"New Language"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"New Language"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"New Language"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"New Language"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"New Language"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"New Language"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"New Language"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"New Language"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"New Language"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"New Language"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"New Language"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"New Language"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"New Language"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"New Language"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"New Language"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"New Language"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Refresh Medication List",
		u"New Language"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"New Language"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"New Language"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"New Language"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"New Language"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"New Language"
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"New Language"
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"New Language"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"New Language"
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"New Language"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"New Language"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"New Language"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"New Language"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"New Language"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"New Language"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"New Language"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"New Language"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"New Language"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"New Language"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"New Language"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"New Language"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"New Language"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"New Language"
		)
	dictionary["friday"] = (
		"Friday",
		u"New Language"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"New Language"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"New Language"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"New Language"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"New Language"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"New Language"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"New Language"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"New Language"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"New Language"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"New Language"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"New Language"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"New Language"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"New Language"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"New Language"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"New Language"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"New Language"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"New Language"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"New Language"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"New Language"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"New Language"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"New Language"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"New Language"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"New Language"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"New Language"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"New Language"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"New Language"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"New Language"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"New Language"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"New Language"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"New Language"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"New Language"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"New Language"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"New Language"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"New Language"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Staff",
		u"New Language"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"New Language"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"New Language"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"New Language"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"New Language"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"New Language"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"New Language"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"New Language"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"New Language"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"New Language"
		)
	dictionary["userslabel"] = (
		"Users",
		u"New Language"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"New Language"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"New Language"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"New Language"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"New Language"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"New Language"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"New Language"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"New Language"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"New Language"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"New Language"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"New Language"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"New Language"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"New Language"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"New Language"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"New Language"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"New Language"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"New Language"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"New Language"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"New Language"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"New Language"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"New Language"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"New Language"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"New Language"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"New Language"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"New Language"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"New Language"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"New Language"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"New Language"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"New Language"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"New Language"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"New Language"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"New Language"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"New Language"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"New Language"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"New Language"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"New Language"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"New Language"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"New Language"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"New Language"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"New Language"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"New Language"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"New Language"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"New Language"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"New Language"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"New Language"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"New Language"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"New Language"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"New Language"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"New Language"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"New Language"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"New Language"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"New Language"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"New Language"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"New Language"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"New Language"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"New Language"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"New Language"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"New Language"
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"New Language"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"New Language", u"New Language")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"New Language"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"New Language"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"New Language"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		u"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		u"New Language"
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"New Language", u"New Language")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"New Language"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"New Language"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"New Language"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"New Language"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"New Language"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"New Language"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"New Language", u"New Language")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"New Language", u"New Language")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"New Language"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"New Language"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"New Language"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"New Language"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"New Language"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"New Language"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"New Language"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"New Language"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"New Language"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"New Language"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"New Language"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"New Language"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"New Language"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"New Language"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"New Language"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"New Language"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"New Language"
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"New Language"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"New Language"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"New Language"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"New Language"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"New Language", u"New Language")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"New Language"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"New Language"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"New Language"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"New Language"
		)
	dictionary["showremovedlabel"] = (
		"Include removed",
		u"New Language"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"New Language"
		)
	dictionary["notelabel"] = (
		"Note",
		u"New Language"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"New Language"
		)
	dictionary["linklabel"] = (
		"Link",
		u"New Language"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"New Language"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"New Language"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"New Language"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"New Language"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"New Language"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"New Language"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"New Language"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"New Language"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"New Language"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"New Language"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"New Language"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"New Language"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade to continue",
		u"New Language"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"New Language"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"New Language"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"New Language"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"New Language"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"New Language", u"New Language")
		)
	dictionary["licenselabel"] = (
		"License",
		u"New Language"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"New Language"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"New Language"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"New Language"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"New Language"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"New Language"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"New Language"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"New Language"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"New Language"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"New Language"
		)
	dictionary["programlabel"] = (
		"Program",
		u"New Language"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"New Language"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"New Language"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!\nTo associate a program with this file type, choose \"File Associations\" from the \"Settings Menu\"",
		u"New Language"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"New Language"
		)
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"New Language"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"New Language"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"New Language"
		)
	dictionary["samelabel"] = (
		"Same",
		u"New Language"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"New Language"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"New Language"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"New Language"
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"New Language", u"New Language")
		)
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"New Language"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"New Language", u"New Language" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"New Language"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"New Language"
		)
	dictionary["januarylabel"] = (
		"January",
		u"New Language"
		)
	dictionary["februarylabel"] = (
		"February",
		u"New Language"
		)
	dictionary["marchlabel"] = (
		"March",
		u"New Language"
		)
	dictionary["aprillabel"] = (
		"April",
		u"New Language"
		)
	dictionary["maylabel"] = (
		"May",
		u"New Language"
		)
	dictionary["junelabel"] = (
		"June",
		u"New Language"
		)
	dictionary["julylabel"] = (
		"July",
		u"New Language"
		)
	dictionary["augustlabel"] = (
		"August",
		u"New Language"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"New Language"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"New Language"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"New Language"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"New Language"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"New Language"
		)
	dictionary["websitelabel"] = (
		"Website",
		u"New Language"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"New Language"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"New Language", u"New Language")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"New Language", u"New Language")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"New Language"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"New Language"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"New Language"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"New Language"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"New Language"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"New Language"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"New Language"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"New Language"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"New Language"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"New Language"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"New Language"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"New Language"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"New Language"
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"New Language"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"New Language"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"New Language"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"New Language"
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"New Language"
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"New Language"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"New Language"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"New Language"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("New Language", "New Language")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("New Language", "New Language")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"New Language"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"New Language"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"New Language"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"New Language"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"New Language"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"New Language"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"New Language"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"New Language"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"New Language"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"New Language"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"New Language"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"New Language"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"New Language"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"New Language", u"New Language")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"New Language", u"New Language")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"New Language"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		u"New Language"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"New Language"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"New Language"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"New Language"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"New Language"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"New Language"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"New Language"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"New Language"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"New Language"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"New Language"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"New Language"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"New Language"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"New Language"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"New Language"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"New Language"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"New Language"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"New Language"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"New Language"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"New Language"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"New Language"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"New Language"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"New Language"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"New Language"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"New Language"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"New Language"
		)
	dictionary["asmimportmenu"] = (
		("ASM Animal Import", "Import an animal from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"New Language"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"New Language"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"New Language"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"New Language"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"New Language"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"New Language"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"New Language", u"New Language")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"New Language"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"New Language"
		)
	dictionary["filemenu"] = (
		"File",
		u"New Language"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"New Language", u"New Language")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"New Language", u"New Language")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"New Language")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"New Language"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"New Language"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"New Language"
		)
	dictionary["malelabel"] = (
		"Male",
		u"New Language"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"New Language"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"New Language"
		)
	dictionary["dayslabel"] = (
		"days",
		u"New Language"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"New Language"
		)
	dictionary["monthslabel"] = (
		"months",
		u"New Language"
		)
	dictionary["yearslabel"] = (
		"years",
		u"New Language"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"New Language"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"New Language"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"New Language"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"New Language"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"New Language"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"New Language"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"New Language"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"New Language"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"New Language"
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"New Language"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"New Language"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"New Language"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"New Language"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"New Language"
		)
	dictionary["latelabel"] = (
		"Late",
		u"New Language"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"New Language"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"New Language"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"New Language"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"New Language"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"New Language"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"New Language"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
