#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Español####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Nombre de Usuario"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Contraseña"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Acceder"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Total"
		)
	dictionary["fromlabel"] = (
		"From",
		u"De"
		)
	dictionary["tolabel"] = (
		"To",
		u"A"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Precio"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Descripción"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Si"
		)
	dictionary["nolabel"] = (
		"No",
		u"No"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Editar"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Borrar"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"Buscar"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"Reiniciar"
		)
	dictionary["movelabel"] = (
		"Move",
		u"Mover"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"Unidad"
		)
	dictionary["onlabel"] = (
		"on",
		u"en"
		)
	dictionary["namelabel"] = (
		"Name",
		u"Nombre"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"Programa total de Gestion de una Clínica Veterinaria gratuito y libre"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"Puede cambiar este encabezado editándolo como usted prefiera"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"Generado por"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Hora"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Cirugias"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Operando"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"En consulta"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Veterinario/a"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Características de la mascota"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Datos del Dueño"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Recibo"
		)
	dictionary["problemlabel"] = (
		"Problem",
		u"Motivo de Consulta"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"Aclaraciones"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"Procedimiento"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Borrar Usuario"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Cambiar Datos"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Posición"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Fecha"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Hora no valida"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Contenido"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Próxima consulta"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Ninguna"
		)
	
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"Clientes"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"Citas"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"Tratamientos"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"Procedimientos"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"Antecedentes"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"Formularios"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"Personal"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"Parámetros"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"Ayuda"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Entero"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Esterilizado-Castrado"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Cliente Nuevo", u"Crea una nueva Ficha de Cliente")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Buscar Cliente", u"Busca los datos de un Cliente o Mascota")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"Ver Citas", u"Ver las citas del dia")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"Ver Cirugias", u"Ver cirugias del dia")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Editar Usuarios", u"Agregar y Modificar Usuarios de Evette")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Editar Turnos", u"Editar y modificar el calendario de turnos")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Editar Tratamientos", u"Editar Tratamientos")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Editar Vacunaciones", u"Editar Vacunaciones")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Editar Procedimientos", u"Editar Procedimientos")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Editar Color", u"Editar Color")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Editar Razas", u"Editar Razas")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Editar Especies", u"Editar Especies")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Editar Formulario", u"Editar Formulario")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Editar Configuracion", u"Editar configuraciones unicamente para esta Clínica")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Datos Aleatorios", u"Generacion de datos aleatorios para comparar con")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Reiniciar Base de Datos", u"Reiniciar totalmente la información de Evette")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Ayuda", u"Ayuda acerca de Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Acerca", u"Información acerca de Evette")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u" Agregar Cliente ", u"Crear la Ficha de un cliente nuevo")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u" Buscar Cliente ", u"Búsqueda de Clientes y Mascotas")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u" Citas Diarias ", u"Ver las citas del dia")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u" Cirugias Diarias ", u"Ver las cirugias del dia")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Nuevo Cliente"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Título"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"Nombre"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"Apellido"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Domicilio"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"Código Postal"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Teléfono"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Celular"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Teléfono del Trabajo"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"Correo Electrónico"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Comentarios"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Mascotas"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Agregar una Mascota Nueva"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Editar la ficha de la Mascota seleccionada"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Borrar la ficha de la mascota seleccionada"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Actualizar la lista de Mascotas"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Crear una cita para la Mascota seleccionada"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Estado del Paciente"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Factura detallada"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"Guardar los datos del Cliente"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Este cliente tiene datos sin guardar, ¿está usted seguro de salir?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"¿Realmente quiere borrar los datos de la Mascota?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Actualizar Factura"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u"Facturas Recientes", u"Elija el intervalo de fechas entre las diferentes facturas")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Desseleccionar la factura actual y borrar los precios y descripciones de los artículos"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Agregar los cambios de la factura seleccionada"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Borrar la factura seleccionada"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Nueva Mascota"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Dueño"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Editar la ficha de la mascota"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Nombre"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Sexo"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Especie"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Raza"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Color"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Fecha de Nacimiento"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Tatuaje o Chip"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Comentarios"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"Marcar si el animal es esterilizado o castrado"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Imprimir la ficha entera de la Mascota"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Generar un formulario usando los datos de la Mascota"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Citas"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Crear una cita para esta Mascota"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Modificar la cita seleccionada"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Actualizar las citas"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Borrar la cita seleccionada"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Imprimir la cita seleccionada"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Formulario Veterinario", u"Editar el Formulario Veterinario para la cita seleccionada")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Detalles de la cita"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Vacunaciones"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Guardar los cambios realizados en la ficha de esta mascota"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Esta Mascota tiene datos sin guardar, ¿está usted seguro de salir?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"¿Está Usted seguro de borrar la cita?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Reiniciar la historia vacinal"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"Vacuna"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Administrado por "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u"Próxima vacuna el "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Borrar la vacuna seleccionada"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Agregar esta vacuna"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"¿Está Usted seguro de borrar esta vacuna?"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Número de lote: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Cita para"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Cirugía de"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Si esta cita es para un determinado veterinario/a, agregue el nombre del veterinario/a aquí"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Actualizar las citas"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Motivo de la cita"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Hora de la cita"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"¿Cirugía?", u"Marque este cuadro para reservar una cirugía")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Agregar esta cita"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Borrar esta cita"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Estado o Situación"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"No vino"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Esperando"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Con el Veterinario/a"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Realizado"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Editar Propietario", u"Editar la ficha del Propietario")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Editar Mascota", u"Editar la ficha de la Mascota")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Citas para"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Cirugias para"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"¡¡La hora de la cita es antes del inicio de la consulta!!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"¡¡La hora de la cita es posterior al fin de la consulta!!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"¡¡Hora Incorrecta - el formato de la hora es HH:MM!!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Búsqueda de Cliente"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Clientes"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"Nombre"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Teléfono"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Dirección"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"Código Postal"
		)
	dictionary["clientsearchemaillabel"] = (
		"Correo Electrónico",
		u"New Language"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Borrar", u"Borrar todas las entradas")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Buscar", u"Realice la búsqueda")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"Editar la ficha del cliente seleccionado"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Suprima la ficha del cliente seleccionado"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Mascotas"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Nombre"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Sexo"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Especie"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"Raza"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Tatuaje o chip "
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Comentarios"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Editar la ficha de la Mascota seleccionada"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Borrar la ficha de la Mascota seleccionada"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Recibo Artículo - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"¿Realmente borra la entrada de este recibo?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Borrar el ingreso de pago"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Pago"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Incorporar pago"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Pago"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"¡Archivo Conf no encontrado! ¿Desea crear uno ahora?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"¡Carpeta Evette no encontrada! ¿Desea crear una ahora?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"¡¡Imposible conectarse al servidor de datos!! Haga el favor de comprobar si esta instalado y funcionando. ¿Desea Usted realizar las configuraciones locales?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"¡¡Imposible localizar la base de datos de Evette!! ¿Desea Usted crearla ahora?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Archivo Conf creado"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Carpeta Evette creada"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"IP BD"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Usuario BD"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Contraseña BD"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"¡¡Imposible crear Base de Datos, por favor compruebe la configuración de su servidor mysql!!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"¡¡Base de Datos creada exitosamente!!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Conectado"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Editar Libreria de coloraciones"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Editar libreria de Especies"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Editar libreria de Razas"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Actualizar la lista"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Borrar la libreria seleccionada"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Incorporar libreria"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"¡¡Esta libreria ya existe, es inutil ponerla nuevamente!!"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Nombre esta libreria"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"¿Realmente esta seguro de borrar esta libreria?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Editar Tratamiento"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Edit Medication",
		u"Editar Tratamiento"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Borrar el tratamiento seleccionado"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Numero de Lote"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Generar reporte mostrando todos los movimientos de este número de lote"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Imprima una lista de sus actuales existencias"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Movimientos de "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"¿Está seguro de Borrarlo?"
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"¿Está seguro de querer reecribir este tratamiento"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Movimientos del lote numero "
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Expira"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Actualize los detalles de este tratamiento"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Borre este cambio de tratamiento"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Cambiando"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"¿Está Usted seguro de modificar la historia terapéutica?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"¿Está Usted seguro de borrar la historia terapéutica?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Actualice los detalles del tratamiento"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Reiniciar los criterios de búsqueda"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Número de lote actual"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Precio Unitario"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"Lunes"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"Martes"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Miercoles"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"Jueves"
		)
	dictionary["friday"] = (
		"Friday",
		u"Viernes"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Sábado"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Domingo"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Editar Procedimientos"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Actualizar la lista de Procedimientos"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Borrar el Procedimiento seleccionado"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"De un Nombre a este Procedimiento"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"¿Esta seguro de querer editar este Procedimiento?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"¿Esta seguro de querer borrar este Procedimiento?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Datos Aleatorioos"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"No hay Clientes para atender"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"No hay Mascotas para atender"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"No hay mas citas pendientes"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"No quedan cirugias sin realizar"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"No hay tratamientos pendientes"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Clientes"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Mascotas"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"citas"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Cirugias"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Tratamientos"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Crear datos aleatorios"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Nombre de la Clínica"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Abierto desde las"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Abierto hast las"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Duración de la cirugía"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"Visor HTML"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"Visor HTML"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Lenguaje"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Editar Formulario Veterinario"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Editar Finanzas"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Mostrar Barra de Herramientas"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"Ver Cambios"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Editar configuración"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Editar Turnos"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Editar Turnos"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"Mienbros del Personal"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Borrar el seleccionador de usuario"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Clientes"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Mascotas"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Citas"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Tratamiento"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Clientes"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Librerias"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"Formularios"
		)
	dictionary["userslabel"] = (
		"Users",
		u"Usuarios"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"Miscelaneos"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"Marcar todos"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"¡¡Permitir al usuario el uso de TODAS las areas del Systema. Usar con cuidado!!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"¿Está Usted seguro de sobreescribir este Usuario?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"¿Está Usted seguro de sobreescribir este Usuario?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Editar Turno"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Hora de Comienzo"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"Hora de Finalización"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"En cirugia"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Esquema del Personal"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Planificación Diaria"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Introduzca el Nombre del Veterinario"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"!¡El Veterinario no puede terminar sin haber comenzado¡¡"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"¡¡Esta persona no puede estar en dos lugares al mismo tiempo!!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"Editar Vacunaciones"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"Vacuna"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Actualizar la lista de vacunaciones"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"Borrar la vacunación seleccionada"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Imprimir el listado de las existencias actuales"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"¿Está seguro de borrar esta vacunación?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"¿Está seguro de reescribir esta vacunación?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"Actualizar las detalles de esta vacunación"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"Borrar la historia de esta vacunación"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"¿Está seguro de querer editar el historial"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"¿Está seguro de querer borrar este historial?"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"Formulario Veterinario"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Histórial de Citas"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Detalles de Citas"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"Tratamientos"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"Vacunaciones"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"Procedimientos"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"New Language"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"Borrar el artículo seleccionado de la receta"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"Marcar esta cita como completa y terminada"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"Guardar los cambios hechos en este Formulario Veterinario"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"Artículo de la Receta"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"¿Está seguro de querer borrar este artículo?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"Borrar el \"Contiene\"entrada"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"Actualizar la lista de Tratamientos"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"Introducir la posología"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"Instrucciones"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"Introducir las instrucciones de como se debe administrar esta medicación"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"Imprimir una etiqueta para este medicamento"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"Introducir el número de lote aquí"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"Actualizar la lista de Vacunaciones"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"Actualizar la lista de procedimientos"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"¡Debe de poner una descripción!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Visualizar citas"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Visualizar cirugias"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"Marcar esta cita con un veterinario/a"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Elegir un Veterinario/a"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Organizar la visita del Veterinario/a para esta cita"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Marcar esta cita como presente"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Marcar esta cita como realizada"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Editar Cliente"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Editar la ficha del cliente (así el podra pagar la factura)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"Veterinarios presentes"
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Búsqueda de citas"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Búsqueda de citas", u"Buscar una cita")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Nombre de la Mascota"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Motivo"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Ver Cirugias"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		u"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		"$"
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Lista de Correo", u"Lista de Clientes para contactar")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Lista de correo"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Todas las vacunaciones"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Todas las Especies"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Fallecidos"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Causa de Muerte"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Incluir fallecidos"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Crear Citas", u"Fijar una cita para esta vacunación")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"Crear un archivo CSV", u"Crear y guardar un archivo CSV en disco. Este puede ser usado en la mayoría de los procesadores de texto para crear una lista de correo")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"Archivo CSV guardado en"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Falta la (Versión cuadro) ¿crearla ahora?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"¿Desea ejecutar Evette?"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"La versión de su Base de Datos es"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Desea Ud Actualizar la base de Datos de Evette"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"¿Está seguro de querer borrar todas las Tablas? SE PERDERÁN TODOS SUS DATOS "
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"TODAS las tablas fueron borradas"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"¿Agregar Personal?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Veterinarios/as"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Nerses"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Otros"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Visualizar próximo mes"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Visualizar mes anterior"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Retornar al calendario"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Agregar un mienbro del personal al calendario de turnos"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Borrar este Turno"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Agregar este Turno"
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"Veterinario/a"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"Nerse"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"Encargado"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"Lo siento, el error siguiente ha ocurrido"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Escribir Diario", u"Escribir el Diario")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Editar Diario"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Hasta"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Tema del Contenido"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Contenido de las Aclaraciones"
		)
	dictionary["showremovedlabel"] = (
		"Include removed",
		u"Contenido borrado"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Tema"
		)
	dictionary["notelabel"] = (
		"Note",
		u"lnota"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Borrado"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Vínculo"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Cliente"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Mascota"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Abra la ficha ligada a esta lnota de la Agenda"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"lnota de la Agenda"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"¿Está seguro de borrar esta lnota de la Agenda?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"No existe Vínculo"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Crear una lnota en la agenda asociada con esta ficha"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Crear una nueva nota en la agenda"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Editar la nota de la agenda seleccionada"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Borrar la nota de la agenda seleccionada"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Actualizar la lista de la nota de la agenda"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Borrar los filtros de la agenda"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade to continue",
		u"Usted está tratando de usar un servidor fuera de fecha, haga el favor de actualizarlo para poder continuar"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Agregar a la agenda"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Editar agenda"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Borrar de la agenda"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Agenda"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Ver Licencia", u"Ver la licencia de este software")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Licencia"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Acerca"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Archivos agregados"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"¿Está seguro de borrar este archivo?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Agregar un archivo externo nuevo a esta ficha"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Actualice la descripción del archivo seleccionado"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Borrar el archivo seleccionado"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Guardar el archivo seleccionado al disco"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Asociaciones de archivos"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Extensión"
		)
	dictionary["programlabel"] = (
		"Program",
		u"Programa"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Ya hay un programa asociado con esta extensión de archivo"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"¿Está Usted seguro de borrar esta asociación de archivo?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!\nTo associate a program with this file type, choose \"File Associations\" from the \"Settings Menu\"",
		u"¡No hay un programa asociado con este tipo de archivo!\nPara asociar un programa a este tipo de archivo, elija \"Asociacion de Archivos\" desde el \"Menú de Configuración\""
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Este archivo es muy grande para agregarlo"
		)
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Peso"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Borrar el peso seleccionado"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"¿Esta seguro de borrar este peso?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Igual"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Minimo"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"New Language"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Agenda"
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Asociaciones de Archivos", u"Corrija las aplicaciones externas asociadas con los archivos adjunto")
		)
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Si Usted desea realizar la búsqueda de las Mascotas por su nombre, ponga su nombre aquí"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Mirar Citas", u"Mirar todas las Citas" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Mirar Citas"
		)
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Si Usted desea realizar la búsqueda de las Mascotas por su nombre, ponga su nombre aquí"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Mirar Citas", u"Mirar todas las Citas" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Mirar Citas"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"Citas"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Eneroe"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Febrero"
		)
	dictionary["marchlabel"] = (
		"March",
		u"Marzo"
		)
	dictionary["aprillabel"] = (
		"April",
		u"Abril"
		)
	dictionary["maylabel"] = (
		"May",
		u"Mayo"
		)
	dictionary["junelabel"] = (
		"June",
		u"Junio"
		)
	dictionary["julylabel"] = (
		"July",
		u"Julio"
		)
	dictionary["augustlabel"] = (
		"August",
		u"Agosto"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"Setiembre"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Octubre"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"Noviembre"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"Diciembre"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"Para aprender sobre asociaciones de archivos - visite la sección de ayuda"
		)
	dictionary["websitelabel"] = (
		"Website",
		u"Web site"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Generar una factura impresa para este cliente"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Formulario Mascota", u"Crear o editar un modelo impreso que será producido usando las características de la Mascota")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Formulario Cliente", u"Crear o editar un modelo impreso que será producido usando los datos del Cliente")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Formulario Mascota"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Formulario Cliente"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Anterior"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Palabra Clave"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Formulario Factura", u"Editar los modelos de Factura")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Editar Factura"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Formulario ", u"New Language")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Formulario Medicamentos"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Facturas"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Crear una nueva Factura"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Editar la factura seleccionada"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Borrar la factura seleccionad"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Factura no pueden superponerce, por favor revise las fechas"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Genere un formulario usando los datos de este cliente"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Nota: Evette debe ser cerradocuando este proceso sea completado, \nPor favor inicie Evette otra vez para ver los resultados"
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"Número Factura"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"Pagado"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"No Pago"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Identifique la factura para marcar la factura como pagada"
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Escriba la cantidad pagada en la factura seleccionada"
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Modifique el pago"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Corrija la Mascota"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Existencias"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("Editar existencias", "Editar existencias")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("Búsqueda de Lote", "Muestre los movimientos para un número de lote específico")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"Ocurrió una interrupción en la acción que se llevaba a cabo con el número de lote de las existencias"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Editar movimiento"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Crear Movimiento"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Consumible"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Tienda"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Procedimiento"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Manual"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Prescribir Medicación"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Cantidad"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Cantidad Inválida"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"Ver Factura"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnóstico"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Crear un articulo en el recibo"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"Modificar Perreras", u"Puede Modificar Perreras")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"Ver Perreras", u"Ver Perreras")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"&Perreras"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Caniles",
		u""
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"Perreras"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"Modificar Caniles"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"¿Está seguro de querer borrar este canil?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"¿Está seguro de querer borrar esta perrera?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"Modificar Perrera"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"Hospadaje"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"Ocupado"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"Vacante"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"Cambiar Dueño de mascota"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"Seleccionar nuevo Dueño"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"Doble click para seleccionar"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"Crear una ficha de la mascota para una base ASM"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"Elija una mascota"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"Numero de referencia"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"Su busqueda provocó demasiados resultados para ser mostrados, por favor haga más específica su búsqueda"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"En espera"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"Conectando"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"Conectado"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"Error"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"Conexión Fracasada"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"Conexión exitosa"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"Creando carpeta Evette"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"Creando base de datos Evette"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"Error al Crear base de datos Evette"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"Importación desde ASM", u"Importación de datos de una mascota desde ASM")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"No se pudo encontrar al dueño"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"Este animal ya se ha importado. ¿Quiere Usted comprobarlo?"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"Agrege el Peso"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"Modificar el Peso"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"Agregar Usuario"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"Modificar Usuario"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"Modificar Razones", u"Modificar las razones comunes de las citas")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"Búsqueda de las razones de la cita"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"Seleccione con doble click la razón de la cita"
		)
	dictionary["filemenu"] = (
		"File",
		u"Archivo"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"Salir", u"Salir de Evette")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"Cerrar Todos los Paneles", u"Cerrar Todos los Paneles abiertos")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"¿Está seguro de Cerrar Todos los Paneles abiertos? LOS DATOS NO SALVADOS SE PERDERÁN")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"Localización"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"Modificar Procedimientos"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Efectuar una Nueva Búsqueda"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Macho"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Hembra"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"No determinado"
		)
	dictionary["dayslabel"] = (
		"days",
		u"días"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"semanas"
		)
	dictionary["monthslabel"] = (
		"months",
		u"meses"
		)
	dictionary["yearslabel"] = (
		"years",
		u"años"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"Fecha de Nacimiento inválida"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Crear un nuevo canil"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Crear una nueva perrera"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"Importar cliente desde ASM", u"Importar Cliente desde ASM")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Elegir Cliente"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Doble Click para seleccionar desde el calendario"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Elegir la fecha"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Edad"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Agregar vacunaci�n"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Imprimir"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Otro usuario a alterado este archivo desde que usted lo abri�. Por favor cierre esta ficha e int�ntelo nuevamente "
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM Ref"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Desmarcar"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Crear cita"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Permitir m�ltiples paneles abiertos"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Otro usuario a alterado este archivo desde que usted lo abri�. �Desea forzar la realizaci�n de sus cambios?"
		)
	dictionary["latelabel"] = (
		"Late",
		u"Despu�s"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"min"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Microchip"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Implantaci�n de Microchip"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Precio Costo"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"Ver Notas Veterinarias"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Bot�n Derecho para ver veterinarios disponibles\nDoble_click para seleccionar la franja horaria"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
