#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Lithuanian (Lietuvių)####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Vartotojas"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Slaptažodis"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Submit"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Total"
		)
	dictionary["fromlabel"] = (
		"From",
		"Nuo"
		)
	dictionary["tolabel"] = (
		"To",
		u""
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Kaina"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		"Decsription"
		)
	dictionary["yeslabel"] = (
		"Yes",
		"Taip"
		)
	dictionary["nolabel"] = (
		"No",
		"Ne"
		)
	dictionary["editlabel"] = (
		"Edit",
		"Redaguoti"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Šalinti"
		)
	dictionary["searchlabel"] = (
		"Search",
		"Rasti"
		)
	dictionary["resetlabel"] = (
		"Reset",
		"Perkrauti"
		)
	dictionary["movelabel"] = (
		"Move",
		"Kelti"
		)
	dictionary["unitlabel"] = (
		"Unit",
		"Vienetas"
		)
	dictionary["onlabel"] = (
		"on",
		"on"
		)
	dictionary["namelabel"] = (
		"Name",
		"Vardas"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"The complete open-source veterinary practice management package"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"You can change this header to anything you like by editing"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		"Sugeneruoti"
		)
	dictionary["timelabel"] = (
		"Time",
		"Laikas"
		)
	dictionary["operationslabel"] = (
		"Operations",
		"Operacijos"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		"Operating"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		"Konsultacija"
		)
	dictionary["vetlabel"] = (
		"Vet",
		"Vet"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Gyvūno aprašas"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Apie šeimininką"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Išrašas"
		)
	dictionary["problemlabel"] = (
		"Problem",
		"Problema"
		)
	dictionary["noteslabel"] = (
		"Notes",
		"Pastabos"
		)
	dictionary["planlabel"] = (
		"Plan",
		"Planas"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Vartotojas ištrintas"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Keisti Log-ą"
		)
	dictionary["positionlabel"] = (
		"Position",
		"Pozicija"
		)
	dictionary["datelabel"] = (
		"Date",
		"Data"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		"Neteisingas laikas"
		)
	dictionary["containslabel"] = (
		"Contains",
		"Contains"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		"Next Due"
		)
	dictionary["nonelabel"] = (
		"None",
		"Joks"
		)
	
	##Menus
	
	dictionary["clientmenu"] = (
		"&Clients",
		"&Klientai"
		)
	dictionary["appointmentsmenu"] = (
		"&Appointments",
		"&Paskyrimai"
		)
	dictionary["medicationmenu"] = (
		"&Medication",
		"&Vaistai"
		)
	dictionary["proceduresmenu"] = (
		"&Procedures",
		u"&Procedūros"
		)
	dictionary["lookupsmenu"] = (
		"&Lookups",
		"&Lookups"
		)
	dictionary["formsmenu"] = (
		"&Forms",
		"&Formos"
		)
	dictionary["staffmenu"] = (
		"&Staff",
		u"&Budėjimai"
		)
	dictionary["settingsmenu"] = (
		"Se&ttings",
		"Nustatymai"
		)
	dictionary["helpmenu"] = (
		"&Help",
		"&Pagalba"
		)
	dictionary["entirelabel"] = (
		"Entire",
		"Entire"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Sterilizuota"
		)
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Įrašyti klientą", u"Naujo kliento įrašas")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Surasti klientą", u"Surasti kliento ir gyvūno įrašus")
		)
	dictionary["viewappointmentsmenu"] = (
		("Todays Appointments", "View todays appointments"),
		(u"Šiandienos paskyrimai", u"Žiūrėti šiandienos paskyrimus")
		)
	dictionary["viewoperationsmenu"] = (
		("Todays Operations", "View todays operations"),
		(u"Šiandienos operacijos", u"Žiūrėti šiandienos operacijas")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Redaguoti vartotoją", u"Įrašyti ir redaguoti Evette vartotojus")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Redaguoti etatus", u"Redaguoti etatą")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Redaguoti vaistus", u"Redaguoti vaistus")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Edit Vaccinations", u"Edit Vaccinations")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Redaguoti procedūras", u"Redaguoti procedūras")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Redaguoti spalvą", u"Redaguoti spalvą")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Redaguoti veisles", u"Redaguoti veisles")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Redaguoti rūšis", u"Redaguoti rūšis")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Redaguoti formas", u"Redaguoti formas")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Redaguoti nustatymus", u"Edit settings unique to this practice")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Random Data", u"Generate random sample data to experiment with")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Reset Database", u"Completely reset the Evette database. Be careful!")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Pagalba", u"Get help on using Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Apie", u"Informacija apie Evette")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u" Įrašyti klientą ", u"Naujas kliento įrašas")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u" Surasti klientą ", u"Find clients and their animals")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u" Šiandienos paskyrimai ", u"Žiūrėti šiandienos paskyrimus")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u" Šiandienos operacijos ", u"Žiūrėti šiandienos operacijas")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Naujas klientas"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Titulas"
		)
	dictionary["clientforenameslabel"] = (
		"First Name",
		u"Vardas"
		)
	dictionary["clientsurnamelabel"] = (
		"Last Name",
		u"Pavardė"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Adresas"
		)
	dictionary["clientpostcodelabel"] = (
		"Post Code",
		u"Paštas"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Namų tel."
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Mobilus tel."
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Darbo tel."
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"El. paštas"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Įrašyti naują gyvūną"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Redaguoti gyvūno įrašą"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Naikinti gyvūno įrašą"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Atnaujinti gyvūnų įrašą"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Įrašyti gyvūnui paskyrimą"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Balansas"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Detali kaina"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"išsaugoti kliento įrašo pakeitimus"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"This client record has unsaved changes, are you sure you want to close?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Trinti gyvūną?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Refresh bill"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u" Recent Items", u"Adjust the date range of the bill items displayed")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Unselect the current bill item and clear the price and description entries"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Submit changes to the selected bill item"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Delete the selected bill item"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Naujas gyvūnas"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Savininkas"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Redaguoti gyvūno savininką"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Vardas"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Lytis"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Rūšis"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Veislė"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Spalva"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Gimimo data"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Integrinio grandyno Nr."
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["animalneuteredtooltip"] = (
		"Check if the animal is neutered",
		u"Žymėti gyvūnas neatpažintas"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Generate printable output of this entire animal record"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Generate a form using this animals details"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Paskyrimai"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Create an appointment for this animal"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Edit the selected appointment"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Refresh the list of appointments"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Trinti pasirinktą paskyrimą"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Generate printable output for the selected appointment"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Vet Formos", u"Edit the vet form for the selected appointment")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Paskyrimų detalės"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Vakcinacijos"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Save any changes made to this animal record"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"This animal record has unsaved changes, are you sure you want to close?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Really delete appointment?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Reset vaccination entries"
		)
	dictionary["animalvaccinelabel"] = (
		" Vaccine: ",
		u" Vakcina: "
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Galioja: "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u" Sekanti: "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Delete the selected vaccination"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Submit this vaccination"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Are you sure that you want to delete this vaccination?"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Ser.Nr.: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Appointment for"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Operation for"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"If this appointment is for a specific vet, enter the vet's name here"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Refresh the list of appointments"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Reason For Appointment"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Appointment time"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Check this box if you would like to book an operation"),
		(u"Operation?", u"Check this box if you would like to book an operation")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Submit this appointment"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Delete this appointment"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Status"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"Neatvyko"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Laukti"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Su Vet"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Baigti"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Redaguoti savininką", u"Redaguoti kliento įrašą")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Edit Animal", u"Edit animal record")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Appointments for"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Operations for"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"Appointment time is before the practice opens!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"Appointment time is after the practice closes!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Invalid time - times must be HH:MM!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Rasti klientą"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Last Name",
		u"Vardas"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Tel.Nr."
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Adresas"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Post Code",
		u"Paštas"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"El. paštas"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Valyti", u"Valyti viską")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Rasti", u"Perform the search")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"Edit the selected client record"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Delete the selected client record"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Vardas"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Lytis"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Rūšis"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		"Veislė"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Integrinio grandyno Nr."
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Komentarai"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Edit the selected animal record"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Delete the selected animal record"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Receipt item - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Really delete this receipt entry?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Empty the payment entry"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Užmokestis"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Pateikite užmokestį"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Užmokestis"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Configuration file not found! Create one now?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Evette folder not found! Create it now?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"Unable to locate Evette database! Would you like to create one now?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Configuration file created"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Evette folder created"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"Database IP Address"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Database User"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Database Password"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Unable to create database, please check your MySQL server configuration!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Database created successfully!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Log in"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Edit Color Lookups"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Edit Species Lookups"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Edit Breed Lookups"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Refresh the list"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Delete the selected lookup"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Submit lookup"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"That lookup already exists, it's pointless putting it in again!"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"You must give a name for this lookup!"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Are you sure that you want to delete this lookup?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Redaguoti vaistus"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Refresh Medication List",
		u"Atnaujinti vaistų sąrašą"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Trinti vaistą"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Serijos Nr."
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Generate a report showing all movements of this batch"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Print a list of your current stock"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Movements of "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"Are you sure you want to delete "
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Are you sure you want to overwrite this medication?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Movements of Batch Number "
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Galioja"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Refresh the details of this medication"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Delete this medication movement"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Apyvarta"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Are you sure that you want to overwrite this movement?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Are you sure that you want to delete this movement?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Refresh the details of this medication"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Reset search entries"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Einamoji partija"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Vieneto kaina"
		)
	
	##Weekdays
	
	dictionary["monday"] = (
		"Monday",
		"Pirmadienis"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		"Antradienis"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Trečiadienis"
		)
	dictionary["thursday"] = (
		"Thursday",
		"Ketvirtadienis"
		)
	dictionary["friday"] = (
		"Friday",
		"Penktadienis"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Šeštadienis"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Sekmadienis"
		)
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Radaguoti procedūras"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Refresh the list of procedures"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		"Delete the selected procedure"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		"You must give this procedure a name!"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		"Are you sure that you want to edit this procedure?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		"Are you sure that you want to delete this procedure?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		"Atsitiktiniai duomenys"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		"Klientų Nr."
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"Gyvūnų Nr."
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"Paskyrimų Nr."
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"Operacijų Nr."
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"Vaistų Nr."
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Klientai"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		"Paskyrimai"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		"Operacijos"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		"Vaistai"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Generuoti atsitiktinius duomenis"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Dirbančio vardas"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		"Darbas nuo"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		"Dirba iki"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		"Darbo laikas"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"HTML peržiūra"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"HTML peržiūra"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Lietuvių"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		"Redaguoti Vet Formas"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		"Redaguoti finansus"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Rodyti įrankinę"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		"View Changelogs"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		"Redaguoti nustatymus"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		"Personalo narys"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		"Delete the selected user"
		)
	dictionary["clientslabel"] = (
		"Clients",
		"Klientai"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Gyvūnai"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		"Paskyrimai"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		"Vaistai"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		"Klientai"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		"Lookups"
		)
	dictionary["formslabel"] = (
		"Forms",
		"Formos"
		)
	dictionary["userslabel"] = (
		"Users",
		"Vartotojai"
		)
	dictionary["misclabel"] = (
		"Misc",
		"Misc"
		)
	dictionary["tickalllabel"] = (
		"Check All",
		u"Žymėti viską"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		"Give the user permission to use ALL areas of the system. Use with care!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		"Are you sure that you want to overwrite this user?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		"Are you sure that you want to delete this user?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Redaguoti budėjimus"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		"Laikas nuo"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		"Laikas iki"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		"Dirba (Operating)"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Darbuotojų reziumė"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		"Dienos planas"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		"You must enter a vets name!"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		"The vet cannot finish before starting!"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This vet cannot be in two places at once!",
		"This vet cannot be in two places at once!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		"Redaguoti vakcinacijas"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		"Vakcinos"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Atnaujinti vakcinacijų sąrašą"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		"Delete the selected vaccination"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		"Print a list of your current stock"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		"Are you sure you want to delete this vaccination?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		"Are you sure you want to overwrite this vaccination?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		"Refresh the details of this vaccination"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		"Delete this vaccination movement"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		"Are you sure that you want to edit this movement?"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		"Are you sure that you want to delete this movement?"
		)
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		"Vet Formos"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Paskyrimų istorija"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Paskyrimų detalės"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		"Vaist"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		"Vakc"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		"Proc"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		"Rank"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		"Delete the selected item from the receipt"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		"Mark this appointment as complete and close"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		"Save any changes made to this vet form"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		"Receipt Item"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		"Are you sure you want to delete this receipt item?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		"Clear the \"Contains\" entry"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		"Refresh the medication list"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		"Enter the number of units that you are dispensing here"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		"Instructions"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		"Enter instructions on how to administer this medication here"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		"Print a label for this medication"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		"Enter the batch number here"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		"Refresh the vaccination list"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		"Refresh the procedures list"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		"You must give a description!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Žiūrėti paskyrimus"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Žiūrėti operacijas"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		"Mark this appointment as with the vet"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		"Rintis vet.gyd."
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		"Carry out the vet visit for this appointment"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		"Mark this appointment as arrived"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		"Mark this appointment as done"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		"Redaguoti klientą"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		"Edit this clients record (so they can pay their bill)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		"Vet.gyd."
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Paskyrimo paieška"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Paskyrimo paieška", u"Suraskite paskyrimą")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Gyvūno vardas"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Priežastis"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Žiūrėti operacijas"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"YYYYMMDD"
		)
	dictionary["currency"] = (
		"&pound;",
		"Lt "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Pašto išsiuntimas", u"Compile a list of clients to contact")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Mail View OperationsShot"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Bet kokia vakcina"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Bet kokia rūšis"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		"Negyvas"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Mirties priežastis"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Įtraukti negyvus"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		("Create Appointment", "Create an appointment for this vaccination")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"CSV file saved to"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Version table not found, create it now?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"ou are attempting to run evette"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"your database is version"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		"Would you like to upgrade your database?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		"All tables have been reset!"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Pridėti darbuotojus?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Vet.gyd."
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Seselės"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Kiti"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Kitas mėnuo"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Buvęs mėnuo"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		"Atgal į kalendorių"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		"Add a member of staff to this days rota"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		"Delete this rota entry"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		"Submit this rota entry"
		)
	dictionary["vetpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet
		"Vet",
		"Vet"
		)
	dictionary["vetnursepositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet nurse
		"Nurse",
		u"Seselės"
		)
	dictionary["managerpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a manager
		"Manager",
		u"Ūkvedys"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		"Sorry, the following error has occured"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Redaguoti dienoraštį", u"Redaguoti dienoraštį")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Redaguoti dienoraštį"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		"Iki"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Temoje paminėta"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Pastaboje paminėta"
		)
	dictionary["showremovedlabel"] = (
		"Include removed?",
		u"Įrašyti ištrintus?"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Tema"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Pastabos"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Kada ištrinti"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Sąsaja"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Klientas"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Gyvūnas"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Open the record linked to this diary note"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Dienoraščio pastabos"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		"Are you sure that you want to delete this diary note?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		"Be temos"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		"Create a diary note associated with this record"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		"Create a new diary note"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		"Edit the selected diary note"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		"Delete the selected diary note"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		"Refresh the list of diary notes"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		"Clear the diary filters"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade then try again",
		"You are trying to run an out-of-date client, please upgrade then try again"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Įrašyti į dienoraštį"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Redaguoti dienoraštį"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Trinti iš dienoraščio"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Dienoraštis"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Licencija", u"View the license for this software.")
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		("File Associations", "Edit the external applications associated with attached files")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Licencija"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Apie"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Pridėti failai"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		"Are you sure that you want to delete this file?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		"Add a new external file to this record"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		"Update the description of the selected file"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		"Delete the selected file"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		"Save the selected file to disk"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		"File Associations"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Ištęsimas"
		)
	dictionary["programlabel"] = (
		"Program",
		"Programa"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		"There is already a program associated with this file extension!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		"Are you sure that you want to delete this file association?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		"There is no program associated with this file type!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		"This file is too large to attach!"
		)
	############################## 1.1.9 ###############################################
	
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		"Svoris"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		"Delete the selected weight"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		"Are you sure that you want to delete this weight?"
		)
	dictionary["samelabel"] = (
		"Same",
		"Tas pats"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		"Minimalus"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"Senka ištekliai?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Dienoraštis"
		)
	
	############################## 1.2 ###############################################
	
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"If you wish to filter the animals by name, enter the name here"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		(u"Peržiūrėti paskyrimus", u"Peržiūrėti paskyrimus" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		"Browse Appointments"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"paskyrimas"
		)
	dictionary["januarylabel"] = (
		"January",
		"January"
		)
	dictionary["februarylabel"] = (
		"February",
		"February"
		)
	dictionary["marchlabel"] = (
		"March",
		"March"
		)
	dictionary["aprillabel"] = (
		"April",
		"April"
		)
	dictionary["maylabel"] = (
		"May",
		"May"
		)
	dictionary["junelabel"] = (
		"June",
		"June"
		)
	dictionary["julylabel"] = (
		"July",
		"July"
		)
	dictionary["augustlabel"] = (
		"August",
		"August"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"September"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"October"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"November"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"December"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		"To learn about file associations - visit the help section."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"Website"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Generate a printable invoice for this client"
		)
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Animal Forms", u"Create or edit forms that be generated using an animal's details")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Client Forms", u"Create or edit forms that be generated using an client's details")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Animal Forms"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Client Forms"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Preview"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Wordkeys"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Invoice Forms", u"Edit the invoice templates")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Edit Invoices"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Medication Forms", u"Edit the medication templates")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Medication Forms"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Sąskaitos (invoices)"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Create a new invoice"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Edit the selected invoice"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Delete the selected invoice"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Invoices are not allowed to overlap, please adjust the dates"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Generate a form using this clients details"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results."
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"Sąskaitos Nr."
		)
	dictionary["paidlabel"] = (
		"paid",
		u"Apmokėta"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"Neapmokėta"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Choose an invoice ID to mark an invoice as paid."
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Edit the amount paid on the selected invoice."
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Edit payment"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Edit Animal"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Sandėlys"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		(u"Sandėlys", u"Sandėlys")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		(u"Partijos paieška", u"Show movements for a specific batch number")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"View a breakdown of the current stock by batch number"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Redaguoti apyvartą"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Nauja apyvarta"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Vartojamas"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Parduotuvė"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Procedūra"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Manualas"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Nurodykite vaistą"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Kiekis"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Neteisingas kiekis"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"Žiūrėti sąskaitą"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnozė"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Sukurti kvitą"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"Redaguoti patalpas gyvūnams", u"Edit kennels available")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"View Kennels", u"View Kennels")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"&Patalpos gyvūnams"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		"Kennel Blocks"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"Patalpos gyvūnams"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"Edit kennel block"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"Are you sure that you want to delete this kennel block?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"Are you sure that you want to delete this kennel?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"Edit kennel"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"Buvimas"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"užimtas"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"neužimtas"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"Šio gyvūno perkėlimo nuosavybė"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"Rinktis naują savininką"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"Double click to select"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"Create an animal record from an ASM record"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"Choose an animal"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"Reference Number"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"Your search produced too many results to display, please narrow down your search"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"Neturintis darbo"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"Jungiasi"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"Prisijungęs"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"Klaida"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"Unsuccessful Login"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"Successful Login"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"Sukuriama Evette byla"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"Sukuriama Evette duombazė"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"Error creating Evette database"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"ASM Import", "Import an animal from ASM")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"Unable to find owner"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"This animal has already been imported. Would you like to view it?"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"Įrašyti svorį"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"Redaguoti svorį"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"Įrašyti vartotoją"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"Redaguoti vartotoją"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"Redaguoti priežastis",u" Suredaguokite bendras paskyrimo priežastis")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"Appointment Reason Lookups"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"Double click for a choice of common appointment reasons"
		)
	dictionary["filemenu"] = (
		"File",
		u"Byla"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"Išeiti", u"Išeiti iš Evette")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"Uždaryti visus skirtukus", u"Uždaryti visus atvertus skirtukus")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"Are you sure that you want to close all open panels? Any unsaved data will be lost.")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"Vieta"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"Redaguoti procedūras"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Create a new lookup"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Patinas"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Patelė"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"Nenustatyta"
		)
	dictionary["dayslabel"] = (
		"days",
		u"dienos"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"savaitės"
		)
	dictionary["monthslabel"] = (
		"months",
		u"mėnesiai"
		)
	dictionary["yearslabel"] = (
		"years",
		u"metai"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"neteisingas gimtadienis"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Sukurkite naują patalpų gyvūnams bloką"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Sukurkite naują vadą"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"ASM Client Import", u"Import a client from ASM")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Rinktis klientą"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Double click to choose from a calendar"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Rinktis datą"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"Redaguoti paskyrimą"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Amžius"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Įrašyti vakcinaciją"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Spausdinti"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Kitas vartotojas pakeitė šią rinkmeną kadangi jūs atidarėte ją. Prašom uždaryti šį įrašą ir pabandyti dar kartą."
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM Ref"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Deselect"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Įrašyti paskyrimą"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Allow multiple panels open"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Another user has altered this file since you opened it. Would you like to force through your changes?"
		)
	dictionary["latelabel"] = (
		"Late",
		u"Vėlai"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"mins"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Microchipas"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Microchipas implantuotas"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Savikaina"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"Žiūrėti vet. pastabas"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Right click to view available vets\nDouble click to choose time slot"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"Shop išpardavimas"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"Shop Dalykai"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"Krepšys"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"Atidėtas"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"Į krepšį"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"Sujunkite kitą klientą į šį"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"Klientų sujungimas"
		)
	dictionary["addlabel"] = (
		"Add",
		u"Įdėti"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"Išimti"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"Apibrėžkite antkainio taisykles", u"Apibrėžkite antkainio taisykles")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"Padauginti iš"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"Santrauka į"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"Ši vertė nėra įtraukta į jūsų nustatymus, ji turi čia tiesiog leisti jums išmėginti jūsų nustatymus ant kai kurių tikrų skaičių."
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"Neteisinga kaina!"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"Please enter price in cents eg. \"50\" to round to the nearest 50 cents, \"100\" to round to the nearest dollar."
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"Kliento kaina"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"Pateikite nustatymus"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"Pritaikykite einamuosius antkainio nustatymus visai akcijai."
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"Antkainis, pritaikytas visoms kainoms"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"Tęsimas pakeis visas jūsų viešas kainas, yra jūs tikras, kad jūs norite tęsti?"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u" Surinkite \"a\" kad sukurtumėte kainą nuo antkainio taisyklių."
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"Surinkite \"c\" pagalbai, apskaičiuojančiai savikainą."
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"Apskaičiuokite savikainą"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"Kaina už paką"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"Vienetai pako"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"CTRL + P to toggle public availability."
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"Dingę gyvūnai"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"Rasti gyvūnai"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"Radinių biuras", u"Žiūrėti/Redaguoti radinių biurą")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"Dingę"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"Rasti"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"Dingimo data"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"Suradimo data"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"Kailio ilgis"
		)
	dictionary["longlabel"] = (
		"Long",
		u"Ilgas"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"Trumpas"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"Pūkuotas"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"Plikas"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"Dydis"
		)
	dictionary["largelabel"] = (
		"Large",
		u"Didelis"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"Vidutinis"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"Mažas"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"Jauniklis"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"Suaugęs"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"Pagyvenęs"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"Temperament"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"Friendly"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"Bailus"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"Agresyvus"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"Spalva"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"Spalvos apibūdinimas"
		)
	dictionary["arealabel"] = (
		"Area",
		u"Rajonas"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"Please put in likely areas by zipcode if possible as well as the city/state, separated by spaces."
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"Įrašo data"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"Įšsaugoti"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"Kontaktai"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"Užbaigta"
		)
	dictionary["idlabel"] = (
		"ID",
		u"ID"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"Right click for available options."
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"Search for a match"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"Search ceiling"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"Search floor"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"This animal is already on the lost and found!"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"Include complete?"
		)
	dictionary["closelabel"] = (
		"Close",
		u"Uždaryti"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"Rezultatas"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"Radinių biuro radiniai"
		)
	dictionary["systemlabel"] = (
		"System",
		u"Systema"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"Versija"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"Įrašyti dingusį", u"Įrašyti dingusį gyvūną")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"Įrašyti surastą", u"Įrašyti surastą gyvūną")
		)
	dictionary["alllabel"] = (
		"All",
		u"Visi"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"Atnaujinti"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"Gyvūnų filtravimas"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"ASM Shelter"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"Paskyrimo atnaujinimo intervalas"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	
	return dictionary
