#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Hungarian####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Felhasználónév"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Jelszó"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Elfogad"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Összes"
		)
	dictionary["fromlabel"] = (
		"From",
		u"Tól"
		)
	dictionary["tolabel"] = (
		"To",
		u"Ig"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Ár"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Leírás"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Igen"
		)
	dictionary["nolabel"] = (
		"No",
		u"Nem"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Szerkesztés"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Törlés"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"Keresés"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"Visszaállít"
		)
	dictionary["movelabel"] = (
		"Move",
		u"Mozgat"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"Egység"
		)
	dictionary["onlabel"] = (
		"on",
		u"on"
		)
	dictionary["namelabel"] = (
		"Name",
		u"Név"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"A teljesen INGYENES állatorvosi rendelő menedzser csomag"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"Ezt a címet megváltoztathatja a szerkesztéssel"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"Készítette"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Idő"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Műtétek"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Műtő"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"Tanácsadó"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Állatorvos"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Állat adatai"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Tulajdonos adatai"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Recept"
		)
	dictionary["problemlabel"] = (
		"Diagnosis",
		u"Diagnózis"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"Megjegyzés"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"Terv"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Felhasználó által törölt"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Változásnapló"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Állapot"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Dátum"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Érvénytelen idő"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Tartalmaz"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Következő"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Nincs"
		)
	
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"Kliensek"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"Találkozók"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"Gyógyszerek"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"Eljárások"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"Kikeresés"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"Űrlapok"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"Személyzet"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"Beállítások"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"Segítség"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Csődör"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Ivartalanított"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Új kliens", u"Új kliens bejegyzés készítése")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Kliens keresés", u"Kliens és bejegyzett állat keresés")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"Találkozók megtekintése", u"Mai találkozók")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"Műtétek megtekintése", u"Mai műtétek")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Felhasználók szerkesztése", u"Evette felhasználó szerkesztése és hozzáadása")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Névsor szerkesztése", u"Névsor nevek szerkesztése")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Gyógyszerek szerkesztése", u"Gyógyszerek szerkesztése")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Oltások szerkesztése", u"Oltások szerkesztése")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Eljárások szerkesztése", u"Eljárások szerkesztése")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Színek szerkesztése", u"Színek szerkesztése")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Fajták szerkesztése", u"Fajták szerkesztése")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Típusok szerkesztése", u"Típusok szerkesztése")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Űrlapok szerkesztése", u"Űrlapok szerkesztése")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Beállítások szerkesztése", u"Beállítások szerkesztése")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Véletlenszerű adatok", u"Véletlenszerű adatok generálása a tapasztalatok alapján")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Adatbázis visszaállítás", u"Evette adatbázis teljes visszaállítása alaphelyzetbe")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Segítség", u"Itt kaphat segítséget az Evette használatához")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Névjegy", u"Információk a programról")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u"Új kliens", u"Új kliens bejegyzés készítése")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u"Kliens keresés", u"Kliensek és állatok keresése")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u"Mai találkozók", u"Mai találkozók megtekintése")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u"Mai műtétek", u"Mai műtétek megtekintése")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Új kliens"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Titulus"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"Keresztnév"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"Vezetéknév"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Cím"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"Irányítószám"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Otthoni telefon"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Mobil telefon"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Munkahelyi telefon"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"Email"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Megjegyzések"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Állatok"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Új állat bejegyzése"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Kijelölt állat szerkesztése"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Kijelölt állat törlése"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Állatok listájának frissítése"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Új találkozó bejegyzése a kijelölt állattal"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Egyenleg"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Bill",
		u"Számla"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"Kliens bejegyzések mentése"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Ez a kliens nem mentett bejegyzéseket tartalmaz, biztosan be akarja zárni?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Biztos törli az állatot?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Számla frissítése"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u"Friss számlák", u"Dátum tartomány beállítása a megjelenített számláknak")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"A számla kijelölésének megszüntetése, az ár és a leírás törlése"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Változások elfogadása a kijelölt számlán"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Kijelölt számla törlése"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Új állat"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Tulajdonos"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Állat tulajdonos szerkesztése"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Név"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Nem"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Típus"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Fajta"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Szín"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Születési dátum"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Chip #"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Megjegyzések"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"Pipázza be ha az állat ivartalanított"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Nyomatható eredmény generálása erről az állat bejegyzésről"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Űrlap generálása ennek az állatnak az adataival"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Találkozók"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Találkozó bejegyzése ezzel az állattal"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Kijelölt találkozó szerkesztése"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Találkozó listájának frissítése"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Kijelölt találkozó törlése"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Nyomtatható eredmény generálása erről a találkozóról"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Állatorvosi űrlap", u"Az állatorvosi űrlap szerkesztése a kijelölt találkozónak")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Találkozó részletei"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Oltások"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Minden módosítás mentése"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Ez az állat nem mentett bejegyzéseket tartalmaz, biztosan be akarja zárni?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Biztos törli a találkozót?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Oltás bejegyzések visszaállítása"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"Oltás"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Felvéve"
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u"Következő"
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Kijelölt oltás törlése"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Az oltás bejegyzése"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Biztos abban, hogy törli az oltást"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u"Egy tétel"
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Találkozó a(az)"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Műtét a(az)"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Amennyiben ez a találkozó az adott állatorvosé, akkor adja meg a nevét"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Találkozók listájának frissítése"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Indok a találkozóra"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Találkozó ideje"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"Műtét?", u"Jelölje be, ha műtét szeretne előjegyezni")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Találkozó rögzítése"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Találkozó törlése"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Állapot"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Még nem érkezett meg",
		u""
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Várakozás"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Az állatorvossal"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Kész"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Tulajdonos szerkesztése", u"Kliens bejegyzés szerkesztése")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Állat szerkesztése", u"Állat bejegyzés szerkesztése")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Találkozók a(az)"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Műtétek a(az)"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"A találkozó ideje a rendelés ideje előtt van!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"A találkozó ideje a rendelés ideje után van!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Érvénytelen idő - az időnek ÓÓ:PP-nek kell lenni"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Kliens keresés"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Kliensek"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"Vezetéknév"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Telefonszám"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Cím"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"Irányítószám"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"Email"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Törlés", u"Összes bejegyzés törlése")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Keresés", u"Keresés végrehajtása")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"A kijelölt kliens bejegyzés szerkesztése"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"A kijelölt kliens bejegyzés törlése"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Állatok"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Név"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Nem"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Típus"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"Fajta"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Chip #"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Megjegyzések"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"A kijelölt állat bejegyzés szerkesztése"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"A kijelölt állat bejegyzés törlése"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Recept"
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Valóban törölni szeretné ezt a recept bejegyzést?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Fizetési bejegyzés kiürítése"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Fizetés"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Fizetés elfogadása"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Fizetés"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Beállítások fájl nem található! Létrehozza most?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Evette könyvtár nem található! Létrehozza most?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Nem lehet kapcsolódni az adatbázis szerverhez! Kérem ellenőrizze, hogy telepítve van e és, hogy fut e. Szeretné most beállítani a helyi beállításokat?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"Nem találni az evette adatbázist! Létrehozza most?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Beállítások fájl elkészült"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Evette könyvtár létrehozva"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"Adatbázis IP"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Adatbázis felhasználó"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Adatbázis jelszó"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Nem lehet létrehozni az adatbázist, kérem ellenőrizze a mysql beállításokat!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Adatbázis sikeresen létrehozva!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Bejelentkezés"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Szín keresés szerkesztése"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Típus keresés szerkesztése "
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Fajta keresés szerkesztése"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Lista frissítése"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Kijelölt keresés törlése"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Keresés elfogadása"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"Ez a keresés már létezik"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Adjon nevet ennek a keresésnek!"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Biztos, hogy törli ezt a keresést?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Gyógyszer szerkesztése"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Refresh Medication List",
		u"Gyógyszer lista frissítése"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Kijelölt gyógyszer törlése"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Köteg #"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Jelentés készítése erről a kötegről minden szállítással"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Lista nyomtatása az aktuális raktárkészletről"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Szállítás a(az)"
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"Biztosan törli?"
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Biztosan felülírja ezt a gyógyszert?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Szállítás a köteg számmal"
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Szavatossági idő"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Gyógyszer adatainak frissítése"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Gyógyszer szállításának törlése"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Szállítás"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Valóban felül szeretné írni a szállítást?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Bitzos törölni szeretné a szállítást?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Gyógyszer adatainak frissítése"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Keresési bejegyzések visszaállítása"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Aktuális köteg"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Egység ár"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"Hétfő"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"Kedd"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Szerda"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"Csütörtök"
		)
	dictionary["friday"] = (
		"Friday",
		u"Pétek"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Szombat"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Vasárnap"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Eljárások szerkesztése"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Eljárások listájának szerkesztése"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Kijelölt eljárás törlése"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"Adjon nevet ennek az eljárásnak"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"Biztosan szeretné szerkeszteni ezt az eljárást?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"Biztosan törölni szeretné ezt az eljárást?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Véletlenszerű adatok"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"Nincs a kliensekben"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"Nincs az állatokban"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"Nincs a találkozókban"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"Nincs a műtétekben"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"Nincs a gyógyszerekben"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Kliensek"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Állatok"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"Találkozók"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Műtétek"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Gyógyszerek"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Véletlenszerű adatok létrehozása"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Rendelő neve"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Nyitás"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Zárás"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Működési idő"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"HTML néző"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"HTML néző"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Nyelv"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Állatorvos form szerkesztése"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Pénzügy szerkesztése"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Eszköztár mutatása"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"Változásnapló nézete"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Beállítások szerkesztése"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Sorrendszerkesztés"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Névsor szerkesztése"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"Személyzet"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Kijelölt felhasználó törlése"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Kliensek"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Állatok"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Találkozók"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Gyógyszerek"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Kliensek"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Keresések"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"Űrlapok"
		)
	dictionary["userslabel"] = (
		"Users",
		u"Felhasználók"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"Egyéb"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"Összes jelölése"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"Add meg a felhasználó jogot, hogy az ÖSSZES területet használhassa a rendszerből. Ovatosan használja!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"Biztosan felül akarja írni ezt a felhasználót?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"Biztosan törli ezt a felhasználót?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Névsor szerkesztése"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Bekapcsolás"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"Kikapcsolás"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Működés"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Személyzetösszegzés"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Napi terv"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Meg kell adnia az állatorvos nevét!"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"Az állatorvos nem tud fejezni mielőtt kezdene!"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"Ez az ember nem tud egyszerre két helyen lenni!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"Oltások szerkesztése"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"Oltás"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Oltások listájának frissítése"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"A kijelölt oltás törlése"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Lista nyomtatása az aktuális raktárkészletről"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"Biztos, hogy törli az oltást?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"Biztos, hogy felülírja az oltást?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"Oltások adatainak frissítése"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"Oltás szállításának törlése"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"Biztosan szerkeszti ezt a szállítást?"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Biztosan törli ezt a szállítást?"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"Állatorvosi űrlap"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Találkozó történelem"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Találkozó adatok"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"Gyógyszer"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"Oltás"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"Eljárás"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"Ember"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"A kijelölt recept törlése"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"Találkozó sikeressé jelölése és zárása"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"Minden változás mentése"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"Recept"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"Biztos, hogy törli ezt a receptet?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"Törli a \"Contains\" bejegyzést"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"Gyógyszerek listájának frissítése"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"Adja meg a szétosztás számát"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"Utasítások"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"Adja meg az utasításokat a gyógyszer szedésének"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"Címke nyomtatása ennek a gyógyszernek"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"Adja meg a köteg számát"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"Oltások listájának frissítése"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"Eljárások listájának frissítése"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"Meg kell adnia a leírást!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Találkozók megtekintése"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Műtétek megtekintése"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"A találkozó az állatorvossal jelölése"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Állatorvos választása"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Az állatorvos alkalmazása erre a találkozóra"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Találkozó létrejött"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Találkozó kész"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Kliens szerkesztése"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Kliens bejegyzés szerkesztése (ez alapján fogja megkapni a számlát)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"Állatorvosok bekapcsolva"
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Találkozó keresés"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Találkozó keresés", u"Találkozó keresése")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Állat neve"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Eredmény"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Műtétek megtekintése"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		u"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		"$"
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Körlevelek", u"Kliens kapcsolatok listát készít")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Körlevelek"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Valamilyen oltás"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Valamilyen fajta"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Elpusztult"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Elpusztulás oka"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Beleszámítja az elpusztulást"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Találkozó létrehozása", u"Találkozó létrehozása erre az oltásra")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"CSV fájl létrehozása", u"CSV fájl létrehozása és mentése a lemezre. Ezt bármilyen szöveg feldolgozóval létrehozhatja a körlevelet")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"CSV fájl mentése másként"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Verzió tábla nem található, létrehozza most?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"Megkísérli futattni az evette-t"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"az adatbázis verziója"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Frissíteni szeretné az adatbázist?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"Biztos abban, hogy az összes táblát visszaállítja? MINDEN ADAT ELVESZIK!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"Minden tábla visszaállítva"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Alkalmazott hozzáadása"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Állatorvosok"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Nővérek"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Egyéb"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Következő hónap"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Előző hónap"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Vissza a naptárhoz"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Személyzeti tag hozzáadása az adott nap névsorához"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Névsor bejegyzés törlése"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Névsor bejegyzés elfogadása"
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"Állatorvos"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"Nővér"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"Menedzser"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"A következő hiba történt"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Naplószerkesztés", u"A napló szerkesztése")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Napló szerkesztése"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Up to"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Téma tartalmazza"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Jegyzet tartalmazza"
		)
	dictionary["showremovedlabel"] = (
		"Include removed",
		u"Tartalmazza az eltávolítottat"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Tárgy"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Jegyzet"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Eltávolított"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Hivatkozás"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Kliens"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Állat"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"A naplóbejegyzés által hivatkozott bejegyzés megnyitása"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Napló bejegyzés"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"Biztos abban, hogy törli a naplóbejegyzést?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"Nincs hivatkozás"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Napló bejegyzés létrehozása ezzel a bejegyzéssel"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Új naplóbejegyzés létrehozása"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Kijelölt naplóbejegyzés szerkesztése"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Kijelölt naplóbejegyzés törlése"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Napló bejegyzések lista frissítése"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Napló szűrők törlése"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade to continue",
		u"A futatott kliens elavult, kérem, frissítse a folytatáshoz"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Hozzáadás a naplóhoz"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Napló szerkesztése"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Törlés a naplóból"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Napló"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Licensz megtekintése", u"A szoftver licenszének megtekintése")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Licensz"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Névjegy"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Hozzárendelt fájlok"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Biztos, hogy törli ezt a fájlt?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Külső fájl hozzáadása ehhez e bejegyzéshez"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Kijelölt fájl leírásának frissítése"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Kijelölt fájl törlése"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Kijelölt fájl mentése a lemezre"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Fájl hozzárendelések"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Kiterjesztés"
		)
	dictionary["programlabel"] = (
		"Program",
		u"Program"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Ez a kiterjesztés már hozzá van rendelve más programhoz!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Biztos, hogy törli ezt a fájl kiterjesztést?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!\nTo associate a program with this file type, choose \"File Associations\" from the \"Settings Menu\"",
		u"Ehhez a fájltípushoz nincs program hozzárendelve!\nProgram hozzárendeléséhez válassza a \"Fájl kiterjesztések\" bejegyzést a \"Beállítások menü\"" 
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Ez a fájl túl nagy a csatoláshoz!"
		)
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Súly"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Kijelölt súly törlése"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"Biztos, hogy törli ezt a súlyt?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Ugyanaz"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Minimum"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"Alacsony"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Napló"
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Fájl hozzárendelések", u"Külső programok hozzárendelésének szerkesztése")
		)
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Ha szeretné az állatok nevét szűrni, akkor irja be a nevet"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Találkozók böngészése", u"Összes találkozó böngészése" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Találkozók böngészése"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"találkozó"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Január"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Február"
		)
	dictionary["marchlabel"] = (
		"March",
		u"Március"
		)
	dictionary["aprillabel"] = (
		"April",
		u"Április"
		)
	dictionary["maylabel"] = (
		"May",
		u"Május"
		)
	dictionary["junelabel"] = (
		"June",
		u"Június"
		)
	dictionary["julylabel"] = (
		"July",
		u"Július"
		)
	dictionary["augustlabel"] = (
		"August",
		u"Agusztus"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"Szeptember"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Október"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"November"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"December"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"A fájl hozzárendelések tanulmányozásához tekintse meg a súgót."
		)
	dictionary["websitelabel"] = (
		"Website",
		u"Weboldal"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Nyomtatható számla generálása ennek a kliensnek"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Állat űrlapok", u"Űrlap létrehozása és szerkesztése az állat adataival")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Kliens űrlap", u"Űrlap létrehozása és szerkesztése a kliens adataival")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Állat űrlapok"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Kliens űrlapok"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Előnézet"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Szókulcs"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Számla űrlapok", u"Számla sablonok szerkesztése")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Számlák szerkesztése"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Gyógyszer űrlapok", u"Gyógyszer űrlapok szerkesztése")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Gyógyszer űrlapok"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Számlák"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Számla létrehozása"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Kijelölt számla szerkesztése"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Kijelölt számla törlése"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Számlánál nem megengedett az átfedés, kérem, állítsa be a dátumot"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Űrlap létrehozás a kliens adataival"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Megjegyzés: A változások érvénybelépéséhez,\nkérem indítsa újra a programot."
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"Számla ID"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"fizetve"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"nincs fizetve"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Válasszon számla ID-t a számla fizetetté jelöléséhez"
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Fizetési össeg szerkesztése"
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Fizetés szerkesztése"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Állat szerkesztése"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Raktár"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("Raktár szerkesztése", "Raktár szerkesztése")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("Kötegelt keresés", "Szállítások mutatása a megadott köteg számmal")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"Leltár megtekintése a köteg számának segítségével"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Szállítások szerkesztése"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Szállítás létrehozása"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Felhasználható"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Vásárlás"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Eljárás"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Kézi"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Gyógyszerrendelés"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Mennyiség"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Érvénytelen mennyiség"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"Számla megtekintése"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnózis"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Recept készítése"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"Kennelek szerkesztése", u"Kennelek szerkesztése")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"Kennelek megtekintése", u"Kennelek megtekintése")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"&Kennelek"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		u"Kennel blokkok"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"Kennelek"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"Kennel blokk szerkesztése"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"Biztos, hogy törli a kennel blokkot?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"Biztos, hogy törli a kennelt?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"Kennel szerkesztése"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"Leállítás"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"elfoglalt"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"megüresedett"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"Állat tulajdonjogának átruházása"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"Válasszon új gazdát"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"Dupla kattintás a kijelöléshez"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"Állat bejegyzés készítése az ASM bejegyzésből"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"Válasszon állatot"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"Referencia szám"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"A keresés túl sok eredményt hozott, kérem, szűkítse le a keresést"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"Üres"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"Kapcsolódik"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"Kapcsolódva"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"Hiba"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"Sikertelen bejelentkezés"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"Sikeres bejelentkezés"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"Evette mappa létrehozása"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"Evette adatbázis létrehozása"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"Hiba az Evette adatbázis létehozásakor"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"ASM importálás", u"Állat importálása az ASM-ből")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"Nem találni a tulajdonost"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"Az állat már importálva van. Szeretné megtekinteni"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"Súly hozzáadása"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"Súly szerkesztése"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"Felhasználó hozzáadása"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"Felhasználó szerkesztése"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"Indok szerkesztése", u"Közös találkozók indokainak szerkesztése")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"Találkozó indokok kikeresése"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"Dupla kattintás a találkozó indokának választásához"
		)
	dictionary["filemenu"] = (
		"File",
		u"Fájl"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"Kilépés", u"Kilépés az Evette-ből")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"Összes panel bezárása", u"Összes nyitott panel bezárása")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"Biztos, hogy bezárja az összes nyitott panelt? Minden nem mentett adat elveszik.")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"Hely"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"Eljárás szerkesztése"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Kikeresés létrehozása"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Hím"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Nőstény"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"Ismeretlen"
		)
	dictionary["dayslabel"] = (
		"days",
		u"napok"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"hetek"
		)
	dictionary["monthslabel"] = (
		"months",
		u"hónapok"
		)
	dictionary["yearslabel"] = (
		"years",
		u"évek"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"Érvénytelen születési dátum"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Kennel blokk létrehozása"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Kennel létrehozása"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"ASM kliens importálása", u"Kliens importálása az ASM-ből")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Kliens kiválasztása"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Dupla kattintás a naptárból"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Dátum kiválasztása"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"Találkozó szerkesztése"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Életkor"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Oltás hozzáadása"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Nyomtatás"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"New Language"
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"New Language"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"New Language"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"New Language"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"New Language"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"New Language"
		)
	dictionary["latelabel"] = (
		"Late",
		u"New Language"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"New Language"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"New Language"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"New Language"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"New Language"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"New Language"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"New Language"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
