#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Irish####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		"Username"
		)
	dictionary["passwordlabel"] = (
		"Password",
		"Password"
		)
	dictionary["submitlabel"] = (
		"Submit",
		"Submit"
		)
	dictionary["totallabel"] = (
		"Total",
		"Total"
		)
	dictionary["fromlabel"] = (
		"From",
		"From"
		)
	dictionary["tolabel"] = (
		"To",
		"To"
		)
	dictionary["pricelabel"] = (
		"Price",
		"Price"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		"Decsription"
		)
	dictionary["yeslabel"] = (
		"Yes",
		"Yes"
		)
	dictionary["nolabel"] = (
		"No",
		"No"
		)
	dictionary["editlabel"] = (
		"Edit",
		"Edit"
		)
	dictionary["deletelabel"] = (
		"Delete",
		"Delete"
		)
	dictionary["searchlabel"] = (
		"Search",
		"Search"
		)
	dictionary["resetlabel"] = (
		"Reset",
		"Reset"
		)
	dictionary["movelabel"] = (
		"Move",
		"Move"
		)
	dictionary["unitlabel"] = (
		"Unit",
		"Unit"
		)
	dictionary["onlabel"] = (
		"on",
		"on"
		)
	dictionary["namelabel"] = (
		"Name",
		"Name"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		"The complete open-source veterinary practice management package"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		"You can change this header to anything you like by editing"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		"Generated by"
		)
	dictionary["timelabel"] = (
		"Time",
		"Time"
		)
	dictionary["operationslabel"] = (
		"Operations",
		"Operations"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		"Operating"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		"Consulting"
		)
	dictionary["vetlabel"] = (
		"Vet",
		"Vet"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		"Animal Details"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		"Owner Details"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		"Receipt"
		)
	dictionary["problemlabel"] = (
		"Problem",
		"Problem"
		)
	dictionary["noteslabel"] = (
		"Notes",
		"Notes"
		)
	dictionary["planlabel"] = (
		"Plan",
		"Plan"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		"User Deleted"
		)
	dictionary["changelog"] = (
		"Change Log",
		"Change Log"
		)
	dictionary["positionlabel"] = (
		"Position",
		"Position"
		)
	dictionary["datelabel"] = (
		"Date",
		"Date"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		"Invalid Time"
		)
	dictionary["containslabel"] = (
		"Contains",
		"Contains"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		"Next Due"
		)
	dictionary["nonelabel"] = (
		"None",
		"None"
		)
	
	##Menus
	
	dictionary["clientmenu"] = (
		"&Clients",
		"&Clients"
		)
	dictionary["appointmentsmenu"] = (
		"&Appointments",
		"&Appointments"
		)
	dictionary["medicationmenu"] = (
		"&Medication",
		"&Medication"
		)
	dictionary["proceduresmenu"] = (
		"&Procedures",
		"&Procedures"
		)
	dictionary["lookupsmenu"] = (
		"&Lookups",
		"&Lookups"
		)
	dictionary["formsmenu"] = (
		"&Forms",
		"&Forms"
		)
	dictionary["staffmenu"] = (
		"&Staff",
		"&Staff"
		)
	dictionary["settingsmenu"] = (
		"Se&ttings",
		"Se&ttings"
		)
	dictionary["helpmenu"] = (
		"&Help",
		"&Help"
		)
	dictionary["entirelabel"] = (
		"Entire",
		"Entire"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		"Neutered"
		)
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		("Add Client", "Create a new client record")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		("Find Clients", "Find client and animal records")
		)
	dictionary["viewappointmentsmenu"] = (
		("Todays Appointments", "View todays appointments"),
		("Todays Appointments", "View todays appointments")
		)
	dictionary["viewoperationsmenu"] = (
		("Todays Operations", "View todays operations"),
		("Todays Operations", "View todays operations")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		("Edit Users", "Add and edit Evette users")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		("Edit Rota", "Edit the rota")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		("Edit Medication", "Edit Medication")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		("Edit Vaccinations", "Edit Vaccinations")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		("Edit Procedures", "Edit Procedures")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		("Edit Colours", "Edit Colours")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		("Edit Breeds", "Edit Breeds")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		("Edit Species", "Edit Species")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		("Edit Forms", "Edit Forms")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		("Edit Settings", "Edit settings unique to this practice")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		("Random Data", "Generate random sample data to experiment with")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		("Reset Database", "Completely reset the Evette database. Be careful!")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		("Help", "Get help on using Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		("About", "Information about Evette")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(" Add Client ", "Create a new client record")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(" Client Search ", "Find clients and their animals")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(" Todays Appointments ", "View todays appointments")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(" Todays Operations ", "View todays operations")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		"New Client"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		"Title"
		)
	dictionary["clientforenameslabel"] = (
		"First Name",
		"First Names"
		)
	dictionary["clientsurnamelabel"] = (
		"Last Name",
		"Last Name"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		"Address"
		)
	dictionary["clientpostcodelabel"] = (
		"Post Code",
		"Post Code"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		"Home Phone"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		"Mobile Phone"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		"Work Phone"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		"Email"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		"Comments"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		"Animals"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		"Create a new animal"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		"Edit the selected animal record"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		"Delete the selected animal record"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		"Refresh the list of animals"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		"Create an appointment for the selected animal"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		"Balance"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		"Detailed Bill"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		"Save changes to client record"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		"This client record has unsaved changes, are you sure you want to close?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		"Really delete animal?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		"Refresh bill"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(" Recent Items", "Adjust the date range of the bill items displayed")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		"Unselect the current bill item and clear the price and description entries"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		"Submit changes to the selected bill item"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		"Delete the selected bill item"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		"New Animal"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		"Owner"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		"Edit this animals owner"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		"Name"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		"Sex"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		"Species"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		"Breed"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		"Colour"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		"DOB"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		"Chip #"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		"Comments"
		)
	dictionary["animalneuteredtooltip"] = (
		"Check if the animal is neutered",
		"Check if the animal is neutered"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		"Generate printable output of this entire animal record"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		"Generate a form using this animals details"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		"Appointments"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		"Create an appointment for this animal"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		"Edit the selected appointment"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		"Refresh the list of appointments"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		"Delete the selected appointment"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		"Generate printable output for the selected appointment"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		("Vet Form", "Edit the vet form for the selected appointment")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		"Appointment Details"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		"Vaccinations"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		"Save any changes made to this animal record"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		"This animal record has unsaved changes, are you sure you want to close?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		"Really delete appointment?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		"Reset vaccination entries"
		)
	dictionary["animalvaccinelabel"] = (
		" Vaccine: ",
		" Vaccine: "
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		"Given: "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		" Next: "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		"Delete the selected vaccination"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		"Submit this vaccination"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		"Are you sure that you want to delete this vaccination?"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		" Batch: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		"Appointment for"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		"Operation for"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		"If this appointment is for a specific vet, enter the vet's name here"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		"Refresh the list of appointments"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		"Reason For Appointment"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		"Appointment time"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Check this box if you would like to book an operation"),
		("Operation?", "Check this box if you would like to book an operation")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		"Submit this appointment"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		"Delete this appointment"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		"Status"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		"Not Arrived"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		"Waiting"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		"With Vet"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		"Done"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		("Edit Owner", "Edit client record")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		("Edit Animal", "Edit animal record")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		"Appointments for"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		"Operations for"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		"Appointment time is before the practice opens!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		"Appointment time is after the practice closes!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		"Invalid time - times must be HH:MM!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		"Client Search"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		"Clients"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Last Name",
		"Last Name"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		"Phone"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		"Address"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Post Code",
		"Zip Code"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		"Email"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		("Clear", "Clear all entries")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		("Search", "Perform the search")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		"Edit the selected client record"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		"Delete the selected client record"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		"Animals"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		"Name"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		"Sex"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		"Species"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		"Breed"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		"Chip #"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		"Comments"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		"Edit the selected animal record"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		"Delete the selected animal record"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		"Receipt item - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		"Really delete this receipt entry?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		"Empty the payment entry"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		"Payment"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		"Submit Payment"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		"Payment"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		"Configuration file not found! Create one now?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		"Evette folder not found! Create it now?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		"Unable to locate Evette database! Would you like to create one now?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		"Configuration file created"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		"Evette folder created"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		"Database IP Address"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		"Database User"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		"Database Password"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		"Unable to create database, please check your MySQL server configuration!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		"Database created successfully!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		"Log in"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		"Edit Colour Lookups"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		"Edit Species Lookups"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		"Edit Breed Lookups"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		"Refresh the list"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		"Delete the selected lookup"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		"Submit lookup"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		"That lookup already exists, it's pointless putting it in again!"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		"You must give a name for this lookup!"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		"Are you sure that you want to delete this lookup?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		"Edit Medication"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Refresh Medication List",
		"Refresh Medication List"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		"Delete the selected medication"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		"Batch #"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		"Generate a report showing all movements of this batch"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		"Print a list of your current stock"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		"Movements of "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		"Are you sure you want to delete "
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		"Are you sure you want to overwrite this medication?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		"Movements of Batch Number "
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		"Expires"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		"Refresh the details of this medication"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		"Delete this medication movement"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		"Movement"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		"Are you sure that you want to overwrite this movement?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		"Are you sure that you want to delete this movement?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		"Refresh the details of this medication"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		"Reset search entries"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		"Current Batch"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		"Unit Price"
		)
	
	##Weekdays
	
	dictionary["monday"] = (
		"Monday",
		"Monday"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		"Tuesday"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		"Wednesday"
		)
	dictionary["thursday"] = (
		"Thursday",
		"Thursday"
		)
	dictionary["friday"] = (
		"Friday",
		"Friday"
		)
	dictionary["saturday"] = (
		"Saturday",
		"Saturday"
		)
	dictionary["sunday"] = (
		"Sunday",
		"Sunday"
		)
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		"Edit Procedures"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		"Refresh the list of procedures"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		"Delete the selected procedure"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		"You must give this procedure a name!"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		"Are you sure that you want to edit this procedure?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		"Are you sure that you want to delete this procedure?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		"Random Data"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		"Number of clients"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		"Number of animals"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		"Number of appointments"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		"Number of operations"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		"Number of medications"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		"Clients"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		"Animals"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		"Appointments"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		"Operations"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		"Medication"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		"Create random data"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		"Practice Name"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		"Open from"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		"Open to"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		"Operating time"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		"HTML viewer"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		"HTML viewer"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		"American English"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		"Edit Vet Form"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		"Edit Finances"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		"Show Toolbar"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		"View Changelogs"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		"Edit Settings"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		"Edit Rota"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		"Edit Rota"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		"Staff Member"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		"Delete the selected user"
		)
	dictionary["clientslabel"] = (
		"Clients",
		"Clients"
		)
	dictionary["animalslabel"] = (
		"Animals",
		"Animals"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		"Appointments"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		"Medication"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		"Clients"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		"Lookups"
		)
	dictionary["formslabel"] = (
		"Forms",
		"Forms"
		)
	dictionary["userslabel"] = (
		"Users",
		"Users"
		)
	dictionary["misclabel"] = (
		"Misc",
		"Misc"
		)
	dictionary["tickalllabel"] = (
		"Check All",
		"Check All"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		"Give the user permission to use ALL areas of the system. Use with care!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		"Are you sure that you want to overwrite this user?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		"Are you sure that you want to delete this user?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		"Edit Rota"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		"Time On"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		"Time Off"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		"Operating"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		"Staff Summary"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		"Day Plan"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		"You must enter a vets name!"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		"The vet cannot finish before starting!"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This vet cannot be in two places at once!",
		"This vet cannot be in two places at once!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		"Edit Vaccinations"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		"Vaccine"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		"Refresh the list of vaccinations"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		"Delete the selected vaccination"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		"Print a list of your current stock"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		"Are you sure you want to delete this vaccination?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		"Are you sure you want to overwrite this vaccination?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		"Refresh the details of this vaccination"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		"Delete this vaccination movement"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		"Are you sure that you want to edit this movement?"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		"Are you sure that you want to delete this movement?"
		)
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		"Vet Form"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		"Appointment History"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		"Appointment Details"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		"Med"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		"Vacc"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		"Proc"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		"Man"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		"Delete the selected item from the receipt"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		"Mark this appointment as complete and close"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		"Save any changes made to this vet form"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		"Receipt Item"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		"Are you sure you want to delete this receipt item?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		"Clear the \"Contains\" entry"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		"Refresh the medication list"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		"Enter the number of units that you are dispensing here"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		"Instructions"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		"Enter instructions on how to administer this medication here"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		"Print a label for this medication"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		"Enter the batch number here"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		"Refresh the vaccination list"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		"Refresh the procedures list"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		"You must give a description!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		"View Appointments"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		"View Operations"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		"Mark this appointment as with the vet"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		"Choose a vet"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		"Carry out the vet visit for this appointment"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		"Mark this appointment as arrived"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		"Mark this appointment as done"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		"Edit Client"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		"Edit this clients record (so they can pay their bill)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		"Vets On"
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		"Appointment Search"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		("Appointment Search", "Find an appointment")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		"Animal Name"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		"Reason"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		"View Operations"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		"EUR "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		("Mail Shot", "Compile a list of clients to contact")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		"Mail Shot"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		"Any Vaccine"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		"Any Species"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		"Deceased"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		"Cause of Death"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		"Include Deceased"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		("Create Appointment", "Create an appointment for this vaccination")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		"CSV file saved to"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		"Version table not found, create it now?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		"ou are attempting to run evette"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		"your database is version"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		"Would you like to upgrade your database?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		"All tables have been reset!"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		"Add staff?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		"Vets"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		"Nurses"
		)
	dictionary["otherslabel"] = (
		"Others",
		"Others"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		"Show next month"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		"Show previous month"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		"Back to calendar"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		"Add a member of staff to this days rota"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		"Delete this rota entry"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		"Submit this rota entry"
		)
	dictionary["vetpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet
		"Vet",
		"Vet"
		)
	dictionary["vetnursepositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a vet nurse
		"Nurse",
		"Nurse"
		)
	dictionary["managerpositiontitle"] = (#Note: If a user is given this position, Evette will assume that the user is a manager
		"Manager",
		"Manager"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		"Sorry, the following error has occured"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		("Edit Diary", "Edit the diary")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		"Edit Diary"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		"Up to"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		"Subject contains"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		"Note contains"
		)
	dictionary["showremovedlabel"] = (
		"Include removed?",
		"Include removed?"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		"Subject"
		)
	dictionary["notelabel"] = (
		"Note",
		"Note"
		)
	dictionary["removedlabel"] = (
		"Removed",
		"Removed"
		)
	dictionary["linklabel"] = (
		"Link",
		"Link"
		)
	dictionary["clientlabel"] = (
		"Client",
		"Client"
		)
	dictionary["animallabel"] = (
		"Animal",
		"Animal"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		"Open the record linked to this diary note"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		"Diary Note"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		"Are you sure that you want to delete this diary note?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		"No Link"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		"Create a diary note associated with this record"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		"Create a new diary note"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		"Edit the selected diary note"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		"Delete the selected diary note"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		"Refresh the list of diary notes"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		"Clear the diary filters"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade then try again",
		"You are trying to run an out-of-date client, please upgrade then try again"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		"Add to diary"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		"Edit diary"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		"Delete from diary"
		)
	dictionary["diarylabel"] = (
		"Diary",
		"Diary"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		("View License", "View the license for this software.")
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		("File Associations", "Edit the external applications associated with attached files")
		)
	dictionary["licenselabel"] = (
		"License",
		"License"
		)
	dictionary["aboutlabel"] = (
		"About",
		"About"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		"Attached Files"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		"Are you sure that you want to delete this file?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		"Add a new external file to this record"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		"Update the description of the selected file"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		"Delete the selected file"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		"Save the selected file to disk"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		"File Associations"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		"Extension"
		)
	dictionary["programlabel"] = (
		"Program",
		"Program"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		"There is already a program associated with this file extension!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		"Are you sure that you want to delete this file association?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		"There is no program associated with this file type!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		"This file is too large to attach!"
		)
	############################## 1.1.9 ###############################################
	
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		"Weight"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		"Delete the selected weight"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		"Are you sure that you want to delete this weight?"
		)
	dictionary["samelabel"] = (
		"Same",
		"Same"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		"Minimum"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		"Running Low?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		"&Diary"
		)
	
	############################## 1.2 ###############################################
	
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		"If you wish to filter the animals by name, enter the name here"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( "Browse Appointments", "Browse all appointments" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		"Browse Appointments"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		"appointment"
		)
	dictionary["januarylabel"] = (
		"January",
		"January"
		)
	dictionary["februarylabel"] = (
		"February",
		"February"
		)
	dictionary["marchlabel"] = (
		"March",
		"March"
		)
	dictionary["aprillabel"] = (
		"April",
		"April"
		)
	dictionary["maylabel"] = (
		"May",
		"May"
		)
	dictionary["junelabel"] = (
		"June",
		"June"
		)
	dictionary["julylabel"] = (
		"July",
		"July"
		)
	dictionary["augustlabel"] = (
		"August",
		"August"
		)
	dictionary["septemberlabel"] = (
		"September",
		"September"
		)
	dictionary["octoberlabel"] = (
		"October",
		"October"
		)
	dictionary["novemberlabel"] = (
		"November",
		"November"
		)
	dictionary["decemberlabel"] = (
		"December",
		"December"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		"To learn about file associations - visit the help section."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"Website"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"Generate a printable invoice for this client"
		)
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"Animal Forms", u"Create or edit forms that be generated using an animal's details")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"Client Forms", u"Create or edit forms that be generated using an client's details")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"Animal Forms"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"Client Forms"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"Preview"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"Wordkeys"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"Invoice Forms", u"Edit the invoice templates")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"Edit Invoices"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"Medication Forms", u"Edit the medication templates")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"Medication Forms"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"Invoices"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"Create a new invoice"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"Edit the selected invoice"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"Delete the selected invoice"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"Invoices are not allowed to overlap, please adjust the dates"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"Generate a form using this clients details"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results."
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"Invoice ID"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"paid"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"unpaid"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"Choose an invoice ID to mark an invoice as paid."
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"Edit the amount paid on the selected invoice."
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"Edit payment"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"Edit Animal"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"Stock"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("Edit Stock", "Edit Stock")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("Batch Search", "Show movements for a specific batch number")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"View a breakdown of the current stock by batch number"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"Edit Movement"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"Create Movement"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"Consumable"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"Shop"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"Procedure"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"Manual"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"Prescribe Medication"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"Quantity"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"Invalid quantity"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"View Invoice"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"Diagnosis"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"Create a receipt item"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		("Edit Kennels", "Edit kennels available")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		("View Kennels", "View Kennels")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		"&Kennels"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		"Kennel Blocks"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		"Kennels"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		"Edit kennel block"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		"Are you sure that you want to delete this kennel block?"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		"Are you sure that you want to delete this kennel?"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		"Edit kennel"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		"Staying"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		"occupied"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		"vacant"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		"Transfer ownership of this animal"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		"Choose new owner"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		"Double click to select"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		"Create an animal record from an ASM record"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		"Choose an animal"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		"Reference Number"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		"Your search produced too many results to display, please narrow down your search"
		)
	dictionary["idlelabel"] = (
		"Idle",
		"Idle"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		"Connecting"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		"Connected"
		)
	dictionary["errorlabel"] = (
		"Error",
		"Error"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		"Unsuccessful Login"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		"Successful Login"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		"Creating Evette folder"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		"Created Evette database"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		"Error creating Evette database"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		("ASM Import", "Import an animal from ASM")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		"Unable to find owner"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		"This animal has already been imported. Would you like to view it?"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		"Add Weight"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		"Edit Weight"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		"Add User"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		"Edit User"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		("Edit Reasons", "Edit common appointment reasons")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		"Appointment Reason Lookups"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		"Double click for a choice of common appointment reasons"
		)
	dictionary["filemenu"] = (
		"File",
		"File"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		("Exit", "Exit Evette")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		("Close All Panels", "Close all open panels")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		("Are you sure that you want to close all open panels? Any unsaved data will be lost.")
		)
	dictionary["locationlabel"] = (
		"Location",
		"Location"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		"Edit Procedure"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"Create a new lookup"
		)
	dictionary["malelabel"] = (
		"Male",
		u"Male"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"Female"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"Unknown"
		)
	dictionary["dayslabel"] = (
		"days",
		u"days"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"weeks"
		)
	dictionary["monthslabel"] = (
		"months",
		u"months"
		)
	dictionary["yearslabel"] = (
		"years",
		u"years"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"Invalid DOB"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"Create a new kennel block"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"Create a new kennel"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"ASM Client Import", u"Import a client from ASM")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"Choose client"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"Double click to choose from a calendar"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"Choose a date"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"Edit Appointment"
		)
	dictionary["agelabel"] = (
		"Age",
		u"Age"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"Add Vaccination"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"Print"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Another user has altered this file since you opened it. Please close this record and try again."
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM Ref"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Deselect"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Create Appointment"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Allow multiple panels open"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Another user has altered this file since you opened it. Would you like to force through your changes?"
		)
	dictionary["latelabel"] = (
		"Late",
		u"Late"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"mins"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Microchip"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Microchip implanted"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Cost Price"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"View Vet Notes"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Right click to view available vets\nDouble click to choose time slot"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"Shop Sale"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"Shop Items"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"Basket"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"Put back"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"Add to basket"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"Merge another client into this one"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"Clients merged"
		)
	dictionary["addlabel"] = (
		"Add",
		u"Add"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"Subtract"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"Define Markup Rules", u"Define Markup Rules")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"Multiply by"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"Round up to"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures."
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"Invalid Price!"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"Please enter price in cents eg. \"50\" to round to the nearest 50 cents, \"100\" to round to the nearest euro."
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"Customer Price"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"Submit settings"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"Apply the current markup settings to all stock."
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"Markup applied to all prices"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"Continuing will alter all of your public prices, are you sure that you want to continue?"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"Type \"a\" to autogenerate a price from markup rules."
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"Type \"c\" for help calculating the cost price."
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"Calculate Cost Price"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"Price per pack"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"Units per pack"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"CTRL + P to toggle public availability."
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"Lost Animal"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"Found Animal"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"Lost and Found", u"View/Edit Lost and Found")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"Lost"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"Found"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"Date Lost"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"Date Found"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"Fur Length"
		)
	dictionary["longlabel"] = (
		"Long",
		u"Long"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"Short"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"Fluffy"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"Hairless"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"Size"
		)
	dictionary["largelabel"] = (
		"Large",
		u"Large"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"Medium"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"Small"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"Juvenile"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"Adult"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"Elderly"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"Temperament"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"Friendly"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"Timid"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"Aggressive"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"Collar"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"Collar description"
		)
	dictionary["arealabel"] = (
		"Area",
		u"Area"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces."
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"Date complete"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"Save"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"Contact"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"Complete"
		)
	dictionary["idlabel"] = (
		"ID",
		u"ID"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"Right click for available options."
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"Search for a match"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"Search ceiling"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"Search floor"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"This animal is already on the lost and found!"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"Include complete?"
		)
	dictionary["closelabel"] = (
		"Close",
		u"Close"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"Score"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"Lost and Found Search Results"
		)
	dictionary["systemlabel"] = (
		"System",
		u"System"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"Version"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"Add Lost", u"Add a lost animal")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"Add Found", u"Add a found animal")
		)
	dictionary["alllabel"] = (
		"All",
		u"All"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"Refresh"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"Filter Animals"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"Mark as paid?"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"ASM Shelter"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner."
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"Appointment Refresh Interval"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"ASM Vaccination"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"Choose which ASM vaccine you would like Evette to use when updating animal records."
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"Unable to update ASM record!"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"Sync with ASM record"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"Field"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"Sync this field on Evette and ASM records"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"Sync to ASM"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"Sync to Evette"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"Unable to connect to ASM."
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"Record updated via ASM."
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"Record updated via Evette."
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"Update current owner"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"Note: when you run the evette client following this upgrade you will need to re-input your database settings."
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"You can switch between the user and password entries with the TAB key."
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"Discharge"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"Overnight Stay"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"This animal has stayed overnight, creating a new vet form."
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"Prescription Fee"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"On time"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"Did not arrive"
		)
	dictionary["viewlabel"] = (
		"View",
		u"View"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"Rename"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"Filter"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"Browse to find an appropriate program."
		)
	dictionary["agelabel"] = (
		"Age",
		u"Age"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"Batch No Breakdown"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"Return to shelter"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"This owner may already be known to the system. Would you like to view the list of similar clients?"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"Imported from ASM"
		)
	
	return dictionary
