#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####Norwegian####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Brukernavn"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Passord"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Send"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Total"
		)
	dictionary["fromlabel"] = (
		"From",
		u"Fra"
		)
	dictionary["tolabel"] = (
		"To",
		u"Til"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Pris"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Beskrivelse"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Ja"
		)
	dictionary["nolabel"] = (
		"No",
		u"Nei"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Rediger"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Slett"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"Søk"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"Reset"
		)
	dictionary["movelabel"] = (
		"Move",
		u"Flytt"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"Stk"
		)
	dictionary["onlabel"] = (
		"on",
		u"på"
		)
	dictionary["namelabel"] = (
		"Name",
		u"Navn"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"Den komplette GRATIS pakken for organisering av veterinærpraksis"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"Endre overskriften til det du vil"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"Laget av"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Tidspunkt"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Operasjon"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Opererer"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"Konsultasjon"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Veterinær"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Opplysninger om dyret"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Opplysninger om eier"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Kvittering"
		)
	dictionary["problemlabel"] = (
		"Problem",
		u"Problem"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"Notater"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"Plan"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Bruker slettet"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Endre logg"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Posisjon"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Dato"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Ugyldig tidspunkt"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Inneholder"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Neste time"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Ingen"
		)
	
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"Eiere"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"Timer"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"Medisiner"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"Prosedyrer"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"Oppslag"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"Skjemaer"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"Ansatte"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"Innstillinger"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"Hjelp"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Komplett"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Kastrert"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		(u"Ny eier", u"Opprett ny eier")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Finn eier", u"Finn opplysninger om eier og dyr")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"Avtaleboka", u"Dagens timer")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"Vis operasjoner", u"Vis dagens operasjoner")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		(u"Rediger bruker", u"Legg til eller endre Evette-brukere")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Rediger vaktliste", u"Rediger vaktliste")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Endre medisinering", u"Endre medisinering")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Endre vaksinasjoner", u"Endre vaksinasjoner")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Endre prosedyrer", u"Endre prosedyrer")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Endre farger", u"Endre farger")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Endre raser", u"Endre raser")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Endre arter", u"Endre arter")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Endre skjemaer", u"Endre skjemaer")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Endre innstillinger", u"Endre innstillinger for denne klinikken")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Tilfeldige data", u"Lag eksempeldata for testing")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Nullstill database", u"Gjenopprett orginal database")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Hjelp", u"Hjelp til Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Om", u"Informasjon om Evette")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u" Ny eier", u"Legg inn ny eier")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u" Søk etter eier", u"Søk etter dyr og eiere")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u" Dagens timer", u"Vis dagens timer")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u" Dagens operasjoner", u"Vis dagens operasjoner")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Ny eier"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Tittel"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"Fornavn"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"Etternavn"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"Postnr"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Hjemmenr"
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Mobilnr"
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Tlf arb"
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"Epost"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Kommentarer"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Dyr"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Legg til nytt dyr"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Endre valgt dyr"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Slett opplysninger om valgt dyr"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Oppdater listen over dyr"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Opprett time for valgt dyr"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Utestående"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Detaljert regning"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"Lagre endringer"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Det finnes ulagrede endringer på denne eieren, vil du likevel lukke?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Vil du virkelig slette dyret?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Oppdater regning"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u" Nylige prislinjer", u"Endre utvalg av datoer for visning av regningsdetaljer")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Fjern markering, ikke lagre endringer"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Lagre endringer på valgt prislinje"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Slett valgt prislinje"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Nytt dyr"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Eier"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Endre eier"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Navn"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Kjønn"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Art"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Rase"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Farge"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"Født"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Chipnr"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Kommentarer"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"Kryss av hvis dyret er kastrert"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Utskriftsvennlig side"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Lag et skjema med informasjonen om dette dyret"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Timer"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Lag ny time for dette dyret"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Endre valgt time"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"Oppdater liste over timer"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Slett valgt time"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Lag utskriftvennlig side for valgt time"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Journal", u"Rediger journal for denne timen")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Opplysninger om time"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Vaksinasjoner"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Lagre alle endringer på dette dyret"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Det er ikke-lagrede opplysninger på dette dyret, vil du virkelig lukke?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Skal denne timen slettes?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Nullstill vaksinasjonsdata"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"Vaksine"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Gitt: "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u" Neste: "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Slett valgt vaksinasjon"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Lagre denne vaksinasjonen"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Er du sikker på at du vil slette denne vaksinasjonen?"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Gruppe: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Time for"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Operasjon for"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Hvis denne timen er hos en bestemt veterinær - skriv veterin�rens navn her"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Oppdater timelisten"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Årsak til time"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Tidspunkt for time"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"Operasjon?", u"Kryss av her for å reservere en operasjon")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Lagre time"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Slett time"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Status"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"Ikke møtt"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Venter"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Med veterinær"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Ferdig"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Rediger eier", u"Endre opplysninger om eier")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Rediger dyr", u"Endre opplysninger om dyr")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Time for"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Operasjon for"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"Timen er satt opp før vi åpner!"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"Timen er satt opp etter vi har stengt!"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Ugyldig tidsformat - må være på formatet TT:MM!"
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Søk etter eier"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Eiere"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"Etternavn"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Tlf"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"Postnr"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"Epost"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Nullstill", u"Nullstill alt")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Søk", u"Utfør søk")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"Endre valgt eier"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Slett valgt eier"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Dyr"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Navn"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Kjønn"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Art"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"Rase"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Chipnr"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Komentarer"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Rediger opplysninger om valgt dyr"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Slett opplysninger om valgt dyr"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Prislinje - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Vil du slette denne prislinjen?"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Nullstill betalingsinfo"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Betaling"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Lagre betaling"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Betaling"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Konfigurasjonsfil ikke funnet! Opprett nå?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Finner ikke Evette-mappen! Opprett nå?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Kan ikke oppnå kontakt med databaseserver! Kontroller at den er innstallert og kjører. Vil du endre lokale innstillinger?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"Finner ikke Evette-databasen! Skal det opprettes en nå?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Konfigurasjonsfil er opprettet"
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Evette-mappe er opprettet"
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"DB IP"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"DB bruker"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"DB passord"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Kan ikke opprette database, sjekk innstillingene på mysql-serveren din!"
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Databasen er opprettet!"
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Logg inn"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Endre fargeutvalg"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Endre artsutvalg"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Endre raseutvalg"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Oppfrisk liste"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Slett valgt oppslag"
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Lagre oppslag"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"Oppslaget finnes allerede!"
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Du må angi et navn for dette oppslaget"
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Sikker på at du vil slette valgt oppslag?"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Endre medisinering"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Edit Medication",
		u"Endre medisinering"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Slett valgt medisinering"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Batchnr"
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Lag en rapport som viser all bevegelse for denne batchen"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Skriv ut liste av nåværende beholdning"
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Endring av varebeholdning for "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		u"Vil du virkelig slette?"
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Vil du virkelig overskrive denne medisinen?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Oppdateringer av batchnr"
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Utløper"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Oppdater medisinopplysningene"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Slett oppdateringen på denne medisinen"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		u"Oppdatering"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Vil du virkelig overskrive denne oppdateringen?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Vil du virkelig slette denne oppdateringen?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Oppdater opplysningene om denne medisinen"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Nullstill søkekriterie"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Gjeldende batch"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Pris pr enhet"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"Mandag"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"Tirsdag"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Onsdag"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"Torsdag"
		)
	dictionary["friday"] = (
		"Friday",
		u"Fredag"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Lørdag"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Søndag"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Endre prosedyre"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Oppdater prosedyreliste"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Slett valgt prosedyre"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"Du må gi denne prosedyren et navn!"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"Sikker på at du vil endre denne prosedyren?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"Sikker på at du vil slette denne prosedyren?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Tilfeldige data"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"Antall eiere"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"Antall dyr"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"Antall timer"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"Antall operasjoner"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"Antall medisiner"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Eiere"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Dyr"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"Timer"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Operasjoner"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Medisin"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Opprett tilfeldige data"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Klinikknavn"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Åpen fra"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Åpen til"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Operasjonstidspunkt"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"HTML-visning"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"HTML-visning"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Språk"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Endre veterinærskjema"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Rediger økonomi"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Vis verktøylinje"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"Se endringslogg"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Rediger innstillinger"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Rediger vaktliste"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Rediger vaktliste"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"Ansatt"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Slett valgt bruker"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Eiere"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Dyr"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Timer"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Medisiner"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Eiere"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Oppslagsord"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"Skjemaer"
		)
	dictionary["userslabel"] = (
		"Users",
		u"Brukere"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"Diverse"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"Merk alle"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"Gi brukeren tillatelse til ALLE områder i systemet. Brukes med omtanke!"
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"Vil du virkelig overskrive denne brukeren?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"Vil du virkelig slette denne brukeren?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Endre vaktliste"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Start"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"Slutt"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Opererer"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Liste over ansatte"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Dagsplan"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Du må skrive inn navnet på en veterinær!"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"Veterinæren kan ikke avslutte før han har begynt!"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"Denne personen kan ikke være på to steder samtidig!"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"Endre vaksinasjoner"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"Vaksine"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Oppdater vaksinasjonsliste"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"Slett valgt vaksinering"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Skriv ut en oppdatert liste av beholdningen"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"Vil du virkelig slette denne vaksineringen?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"Vil du virkelig overskrive denne vaksinen?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"Oppdater detaljene på denne vaksineringen"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"Slette denne oppdateringen av vaksinebeholdningen"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"Vil du virkelig endre denne oppdateringen?"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Vil du virkelig slette denne oppdateringen?"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"Journal"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Timehistorikk"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Timedetaljer"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"Med"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"Vaks"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"Pros"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"Man"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"Slett valgt prislinje fra kvitteringen?"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"Marker denne timen som gjennomført og avsluttet"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"Lagre endringer i denne journalen"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"Prislinje"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"Er du sikker på at du vil slette denne prislinjen?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"Nullstill \"Inneholder\"-elementet"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"Oppdater medisineringslisten"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"Skriv inn antall enheter som gis ut her"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"Instruksjoner"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"Skriv inn instruksjoner om hvordan denne medisinen skal gis"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"Skriv ut en merkelapp til denne medisinen"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"Skriv inn batchnr her"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"Oppdater vaksinasjonslisten"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"Oppdater prosedyrelisten"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"Du må angi en beskrivelse!"
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Vis timer"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Vis operasjoner"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"Kryss av om denne timen skal gjøres MED veterinær"
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Velg en veterinær"
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Gjennomfør veterinærbesøket for denne timen"
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Marker denne timen som ankommet"
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Marker denne timen som ferdig"
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Endre eier"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Endre opplysningene på denne eieren (så de kan få betalt)"
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"Veterinær opptatt"
		)
	
	
	######################## NEW #################################
	
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Timesøk"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Timesøk", u"Finn en time")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Dyrets navn"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Årsak"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Vis operasjoner"
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		"kr "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Epostutsending", u"Opprett en liste med eiere som skal kontaktes")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Epostutsending"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Enhver vaksine"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Enhver art"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Død"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Dødsårsak"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Inkluder døde"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Opprett time", u"Lag en time for denne vaksinasjonen")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"Opprett CSV-fil", u"Oppretter og lagrer en CSV-fil til disk. Kan benyttes til å generere epostutsendinger")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"CSV-fil lagret til"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Versjonstabell ble ikke funnet, opprett nå?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"Du forsøker å kjøre Evette"
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"databasen din er versjon"
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Vil du oppgradere databasen din?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"Er du sikker på at du vil nullstille alle tabeller? ALLE DATA VIL BLI SLETTET!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"Alle tabeller er nullstilt!"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Legg til ansatte?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Veterinærer"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Dyrepleiere"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Andre"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Vis neste måned"
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Vis forrige måned"
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Tilbake til kalenderen"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Legg en ansatt til vaktlisten for denne dagen"
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Slett denne vaktlisten"
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Lagre vaktliste"
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"Veterinær"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"Dyrepleier"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"Leder"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"Beklager, følgende feil har oppstått"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Skriv i dagbok", u"Skriv i dagbok")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Skriv i dagbok"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Innstilt på"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Temaet inneholder"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Notatet inneholder"
		)
	dictionary["showremovedlabel"] = (
		"Include removed",
		u"Inkludert fil fjernet"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Emne"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Notat"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Fjernet"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Link"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Eier"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Dyr"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Åpne dokumenter linket til dette dagboknotatet"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Dagboknotat"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"Er du sikker på at du vil slette dette dagboknotatet"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"Ingen link"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Lag et dagboknotat assosiert med dette dokumentet"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Lag et nytt dagboknotat"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Endre valgt dagboknotat"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Slett valgt dagboknotat"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Oppdater listen av dagboknotater"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Nullstill dagbokfilter"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade to continue",
		u"Du prøver å kjøre en utdatert klient, oppgrader for å fortsette"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Legg til i dagbok"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Rediger dagbok"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Slett fra dagbok"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Dagbok"
		)
	#################################################################################################
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Vis lisens", u"Vis lisens for denne programvaren")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Lisens"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Om"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Vedlegg"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Sikker på at du vil slette denne filen?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Legg til ekstern fil"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Oppdater beskrivelsen av merket fil"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Slett merket fil"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Lagre valgt fil til disk"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Åpnes i"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Filtype"
		)
	dictionary["programlabel"] = (
		"Program",
		"Program"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Det er allerede et program knyttet til disse filtypene"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Vil du virkelig fjerne angivelsen av hvilket program filen skal åpnes i?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		u"Det er ingen programmer tilknyttet disse filtypene!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Denne fila er for stor til å legge ved!"
		)
	
	############################## 1.1.9 ###############################################
	
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Vis lisens", "uVis lisens for dette programmet")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Lisens"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Om"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Vedlegg"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Vil du virkelig slette denne filen?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Legg til en ekstern fil"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Oppdater beskrivelsen av valgt fil?"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Slett valgt fil"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Lagre valgt fil til disk"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Åpnes i"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Filtype"
		)
	dictionary["programlabel"] = (
		"Program",
		u"Program"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Det finnes allerede et program assosiert med denne filtypen"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Vil du virkelig fjerne angivelsen av hvilket program filen skal åpnes i?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		u"Det finnes ingen programmer assosiert med denne filtypen!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Filen er for stor til å legges ved!"
		)
	
	############################## 1.1.9 ###############################################
	
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Vekt"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Slett valgt vekt"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"Vil du virkelig slette denne vekten?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Samme"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Minimum"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"Running Low?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Dagbok"
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Åpnes i", u"Endre eksternt program assosiert med vedlegg")
		)
	
	############################## 1.2 ###############################################
	
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Hvis du ønske å filterene dyrene ved navn , gå inn navnet her over"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Kikke alle avtaler" ),
		( u"Kikke Avtaler", u"New Language" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Kikke Avtaler"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"time"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Januar"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Februar"
		)
	dictionary["marchlabel"] = (
		"March",
		u"Mars"
		)
	dictionary["aprillabel"] = (
		"April",
		u"April"
		)
	dictionary["maylabel"] = (
		"May",
		u"Mai"
		)
	dictionary["junelabel"] = (
		"June",
		u"Juni"
		)
	dictionary["julylabel"] = (
		"July",
		u"Juli"
		)
	dictionary["augustlabel"] = (
		"August",
		u"August"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"September"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Oktober"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"November"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"Desember"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"Å høre om arkiv foreningene besøk det hjelpe avdeling."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"New Language"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"New Language"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"New Language", u"New Language")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"New Language", u"New Language")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"New Language"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"New Language"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"New Language"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"New Language"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"New Language"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"New Language"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"New Language"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"New Language"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"New Language"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"New Language"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"New Language"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"New Language"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"New Language"
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"New Language"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"New Language"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"New Language"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"New Language"
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"New Language"
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"New Language"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"New Language"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"New Language"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("New Language", "New Language")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("New Language", "New Language")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"New Language"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"New Language"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"New Language"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"New Language"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"New Language"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"New Language"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"New Language"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"New Language"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"New Language"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"New Language"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"New Language"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"New Language"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"New Language"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"New Language", u"New Language")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"New Language", u"New Language")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"New Language"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		u"New Language"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"New Language"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"New Language"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"New Language"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"New Language"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"New Language"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"New Language"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"New Language"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"New Language"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"New Language"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"New Language"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"New Language"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"New Language"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"New Language"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"New Language"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"New Language"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"New Language"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"New Language"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"New Language"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"New Language"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"New Language"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"New Language"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"New Language"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"New Language"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"New Language"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"New Language"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"New Language"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"New Language"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"New Language"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"New Language"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"New Language"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"New Language", u"New Language")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"New Language"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"New Language"
		)
	dictionary["filemenu"] = (
		"File",
		u"New Language"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"New Language", u"New Language")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"New Language", u"New Language")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"New Language")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"New Language"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"New Language"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"New Language"
		)
	dictionary["malelabel"] = (
		"Male",
		u"New Language"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"New Language"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"New Language"
		)
	dictionary["dayslabel"] = (
		"days",
		u"New Language"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"New Language"
		)
	dictionary["monthslabel"] = (
		"months",
		u"New Language"
		)
	dictionary["yearslabel"] = (
		"years",
		u"New Language"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"New Language"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"New Language"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"New Language"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"New Language"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"New Language"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"New Language"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"New Language"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"New Language"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"New Language"
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"New Language"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"New Language"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"New Language"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"New Language"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"New Language"
		)
	dictionary["latelabel"] = (
		"Late",
		u"New Language"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"New Language"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"New Language"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"New Language"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"New Language"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"New Language"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"New Language"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
