#!/usr/bin/python
# -*- coding: UTF-8 -*-

#Copyright (C) 2007 Adam Spencer - Free Veterinary Management Suite

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##Contact: evetteproject@dsl.pipex.com

####German####

def GetDictionary():
	
	dictionary = {}
	
	##Misc
	dictionary["usernamelabel"] = (
		"Username",
		u"Benutzername"
		)
	dictionary["passwordlabel"] = (
		"Password",
		u"Passwort"
		)
	dictionary["submitlabel"] = (
		"Submit",
		u"Bestätigen"
		)
	dictionary["totallabel"] = (
		"Total",
		u"Summe"
		)
	dictionary["fromlabel"] = (
		"From",
		u"Von"
		)
	dictionary["tolabel"] = (
		"To",
		u"An"
		)
	dictionary["pricelabel"] = (
		"Price",
		u"Preis"
		)
	dictionary["descriptionlabel"] = (
		"Description",
		u"Beschreibung"
		)
	dictionary["yeslabel"] = (
		"Yes",
		u"Ja"
		)
	dictionary["nolabel"] = (
		"No",
		u"Nein"
		)
	dictionary["editlabel"] = (
		"Edit",
		u"Bearbeiten"
		)
	dictionary["deletelabel"] = (
		"Delete",
		u"Löschen"
		)
	dictionary["searchlabel"] = (
		"Search",
		u"Suchen"
		)
	dictionary["resetlabel"] = (
		"Reset",
		u"Zurücksetzen"
		)
	dictionary["movelabel"] = (
		"Move",
		u"Verschieben"
		)
	dictionary["unitlabel"] = (
		"Unit",
		u"Einheit"
		)
	dictionary["onlabel"] = (
		"on",
		u"im Dienst"
		)
	dictionary["namelabel"] = (
		"Name",
		u"Name"
		)
	dictionary["headertext1"] = (
		"The complete FREE veterinary practice management package",
		u"Das gesamte freie Tierarztpraxis-Management Paket"
		)
	dictionary["headertext2"] = (
		"You can change this header to anything you like by editing",
		u"Sie können diese Überschrift ganz nach Ihrer Vorstellung anpassen"
		)
	dictionary["generatedbylabel"] = (
		"Generated by",
		u"Erstellt durch"
		)
	dictionary["timelabel"] = (
		"Time",
		u"Zeit"
		)
	dictionary["operationslabel"] = (
		"Operations",
		u"Operationen"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"Z. Zt. in einer Operation"
		)
	dictionary["consultinglabel"] = (
		"Consulting",
		u"Z. Zt. in einer Sprechstunde"
		)
	dictionary["vetlabel"] = (
		"Vet",
		u"Tierarzt"
		)
	dictionary["animaldetailslabel"] = (
		"Animal Details",
		u"Patientendaten"
		)
	dictionary["ownerdetailslabel"] = (
		"Owner Details",
		u"Eigentümerdaten"
		)
	dictionary["receiptlabel"] = (
		"Receipt",
		u"Quittung"
		)
	dictionary["problemlabel"] = (
		"Problem",
		u"Tücke"
		)
	dictionary["noteslabel"] = (
		"Notes",
		u"Notizen"
		)
	dictionary["planlabel"] = (
		"Plan",
		u"Plan"
		)
	dictionary["userdeleted"] = (
		"User deleted",
		u"Benutzer gelöscht"
		)
	dictionary["changelog"] = (
		"Change Log",
		u"Änderungshistorie"
		)
	dictionary["positionlabel"] = (
		"Position",
		u"Position"
		)
	dictionary["datelabel"] = (
		"Date",
		u"Datum"
		)
	dictionary["invalidtimemessage"] = (
		"Invalid Time",
		u"Ungültige Zeitangabe"
		)
	dictionary["containslabel"] = (
		"Contains",
		u"Enthält"
		)
	dictionary["nextduelabel"] = (
		"Next Due",
		u"Nächster"
		)
	dictionary["nonelabel"] = (
		"None",
		u"Keiner"
		)
	
	
	##Menus
	
	dictionary["clientmenu"] = (
		"Clients",
		u"Kunden"
		)
	dictionary["appointmentsmenu"] = (
		"Appointments",
		u"Termine"
		)
	dictionary["medicationmenu"] = (
		"Medication",
		u"Behandlung"
		)
	dictionary["proceduresmenu"] = (
		"Procedures",
		u"Prozeduren"
		)
	dictionary["lookupsmenu"] = (
		"Lookups",
		u"Suchen"
		)
	dictionary["formsmenu"] = (
		"Forms",
		u"Formulare"
		)
	dictionary["staffmenu"] = (
		"Staff",
		u"Belegschaft"
		)
	dictionary["settingsmenu"] = (
		"Settings",
		u"Einstellunge"
		)
	dictionary["helpmenu"] = (
		"Help",
		u"Hilfe"
		)
	dictionary["entirelabel"] = (
		"Entire",
		u"Gesamt"
		)
	dictionary["neuteredlabel"] = (
		"Neutered",
		u"Neutrum"
		)
	
	
	##Menu items
	
	dictionary["addclientmenu"] = (
		("Add Client", "Create a new client record"),
		("Kunden anlegen", "Einen neuen Kundendatensatz erzeugen")
		)
	dictionary["findclientmenu"] = (
		("Find Clients", "Find client and animal records"),
		(u"Kunden finden", u"Kunden- und Patientendatensätze finden")
		)
	dictionary["viewappointmentsmenu"] = (
		("View Appointments", "View todays appointments"),
		(u"Termine ansehen", u"Die heutigen Termine ansehen")
		)
	dictionary["viewoperationsmenu"] = (
		("View Operations", "View todays operations"),
		(u"Operationen ansehen", u"Die heutigen Operationen ansehen")
		)
	dictionary["editusersmenu"] = (
		("Edit Users", "Add and edit Evette users"),
		("Benutzer bearbeiten", "Evette-Benutzer hinzufügen und bearbeiten")
		)
	dictionary["editrotamenu"] = (
		("Edit Rota", "Edit the rota"),
		(u"Dienstplan bearbeiten", "uDen Dienstplan bearbeiten")
		)
	dictionary["editmedicationmenu"] = (
		("Edit Medication", "Edit Medication"),
		(u"Medikamentenbehandlung bearbeiten", u"Medikamentenbehandlung bearbeiten")
		)
	dictionary["editvaccinationsmenu"] = (
		("Edit Vaccinations", "Edit Vaccinations"),
		(u"Impfungen bearbeiten", u"Impfungen bearbeiten")
		)
	dictionary["editproceduresmenu"] = (
		("Edit Procedures", "Edit Procedures"),
		(u"Prozeduren bearbeiten", u"Prozeduren bearbeiten")
		)
	dictionary["editcoloursmenu"] = (
		("Edit Colours", "Edit Colours"),
		(u"Farben bearbeiten", u"Farben bearbeiten")
		)
	dictionary["editbreedsmenu"] = (
		("Edit Breeds", "Edit Breeds"),
		(u"Rassen bearbeiten", u"Rassen bearbeiten")
		)
	dictionary["editspeciesmenu"] = (
		("Edit Species", "Edit Species"),
		(u"Arten bearbeiten", u"Arten bearbeiten")
		)
	dictionary["editformsmenu"] = (
		("Edit Forms", "Edit Forms"),
		(u"Formulare bearbeiten", u"Formulare bearbeiten")
		)
	dictionary["editsettingsmenu"] = (
		("Edit Settings", "Edit settings unique to this practice"),
		(u"Einstellungen bearbeiten", u"Spezielle Einstellungen für diese Praxis bearbeiten")
		)
	dictionary["randomdatamenu"] = (
		("Random Data", "Generate random sample data to experiment with"),
		(u"Zufallsdaten", u"Zufallsdaten für Demozwecke generieren")
		)
	dictionary["resettablesmenu"] = (
		("Reset Database", "Completely reset the evette database"),
		(u"Datenbank zurücksetzen", u"Evette-Datenbank in den Ausgangszustand versetzen")
		)
	dictionary["gethelpmenu"] = (
		("Help", "Get help on using Evette"),
		(u"Hilfe", u"Hilfe für die Benutzung von Evette")
		)
	dictionary["aboutmenu"] = (
		("About", "Information about this program"),
		(u"Über Evette", u"Informationen zum Programm")
		)
	
	##Toolbar
	
	dictionary["addclienttoolbar"] = (
		(" Add Client ", "Create a new client record"),
		(u"Kunden hinzufügen", u"einen neuen Kundendatensatz anlegen")
		)
	dictionary["findclienttoolbar"] = (
		(" Client Search ", "Find clients and animals"),
		(u"Kundensuche", u"Kunden und Patienten suchen")
		)
	dictionary["viewappointmentstoolbar"] = (
		(" Todays Appointments ", "View todays appointments"),
		(u"Die heutigen Termine", u"Die heutigen Termine ansehen")
		)
	dictionary["viewoperationstoolbar"] = (
		(" Todays Operations ", "View todays operations"),
		(u"Die heutigen Operationen", u"Die heutigen Operationen ansehen")
		)
	
	##Client Panel
	
	dictionary["newclientpagetitle"] = (
		"New Client",
		u"Neuer Kunde"
		)
	dictionary["clienttitlelabel"] = (
		"Title",
		u"Titel"
		)
	dictionary["clientforenameslabel"] = (
		"Forenames",
		u"Vornamen"
		)
	dictionary["clientsurnamelabel"] = (
		"Surname",
		u"Nachname"
		)
	dictionary["clientaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientpostcodelabel"] = (
		"Postcode",
		u"PLZ"
		)
	dictionary["clienthomephonelabel"] = (
		"Home Phone",
		u"Private Telefonnr."
		)
	dictionary["clientmobilephonelabel"] = (
		"Mobile Phone",
		u"Mobile Telefonnr. "
		)
	dictionary["clientworkphonelabel"] = (
		"Work Phone",
		u"Dienstliche Telefonnr."
		)
	dictionary["clientemailaddresslabel"] = (
		"Email",
		u"E-Mail"
		)
	dictionary["clientcommentslabel"] = (
		"Comments",
		u"Bemerkungen"
		)
	dictionary["clientanimalslabel"] = (
		"Animals",
		u"Haustiere"
		)
	dictionary["clientaddanimaltooltip"] = (
		"Create a new animal",
		u"Ein neues Haustier anlegen"
		)
	dictionary["clienteditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Den ausgewählten Datensatz bearbeiten"
		)
	dictionary["clientdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Den ausgewählten Datensatz löschen"
		)
	dictionary["clientrefreshanimalstooltip"] = (
		"Refresh the list of animals",
		u"Die Liste der haustiere aktualisieren"
		)
	dictionary["clientcreateappointmenttooltip"] = (
		"Create an appointment for the selected animal",
		u"Einen Behandlungstermin für das ausgewählte Haustier erstellen"
		)
	dictionary["clientbalancelabel"] = (
		"Balance",
		u"Bilanz"
		)
	dictionary["clientdetailedbilllabel"] = (
		"Detailed Bill",
		u"Detaillierte Rechnung"
		)
	dictionary["clientsavetooltip"] = (
		"Save changes to client record",
		u"Änderungen des Kundendatensatzes speichern"
		)
	dictionary["clientunsavedchangesmessage"] = (
		"This client record has unsaved changes, are you sure you want to close?",
		u"Der Kundendatensatz enthält ungespeicherte Änderungen, trotzdem schließen?"
		)
	dictionary["clientdeleteanimalmessage"] = (
		"Really delete animal?",
		u"Soll das Haustier wirklich gelöscht werden?"
		)
	dictionary["clientrefreshbilltooltip"] = (
		"Refresh bill",
		u"Rechnung aktualisieren"
		)
	dictionary["clientrecentbillitems"] = (
		(" Recent Items", "Adjust the date range of the bill items displayed"),
		(u"Aktuelle Rechnungsposten", u"Den Wertebereich der dargestellten Rechnungsposten anpassen")
		)
	dictionary["clientcleardetailedbillentriestooltip"] = (
		"Unselect the current bill item and clear the price and description entries",
		u"Die aktuellen Rechnungsposten deselektieren, Preis und Beschreibungen löschen"
		)
	dictionary["clientsubmitdetailedbillentriestooltip"] = (
		"Submit changes to the selected bill item",
		u"Ändernungen der ausgewählten Rechnungsposten speichern"
		)
	dictionary["clientdeletedetailedbillentriestooltip"] = (
		"Delete the selected bill item",
		u"Den ausgewählten Rechnungsposten löschen"
		)
	
	##Animal Panel
	
	dictionary["newanimalpagetitle"] = (
		"New Animal",
		u"Neues Haustier"
		)
	dictionary["animalownerlabel"] = (
		"Owner",
		u"Besitzer"
		)
	dictionary["animaleditownertooltip"] = (
		"Edit this animals owner",
		u"Diesen Besitzer bearbeiten"
		)
	dictionary["animalnamelabel"] = (
		"Name",
		u"Name"
		)
	dictionary["animalsexlabel"] = (
		"Sex",
		u"Geschlecht"
		)
	dictionary["animalspecieslabel"] = (
		"Species",
		u"Art"
		)
	dictionary["animalbreedlabel"] = (
		"Breed",
		u"Rasse"
		)
	dictionary["animalcolourlabel"] = (
		"Colour",
		u"Farbe"
		)
	dictionary["animaldoblabel"] = (
		"DOB",
		u"DOB"
		)
	dictionary["animalchipnolabel"] = (
		"Chip #",
		u"Chip #"
		)
	dictionary["animalcommentslabel"] = (
		"Comments",
		u"Bemerkungen"
		)
	dictionary["animalneuteredtooltip"] = (
		"Tick if the animal is neutered",
		u"Anchecken, wenn das Tier kastriert ist"
		)
	dictionary["animalprintentirerecordtooltip"] = (
		"Generate printable output of this entire animal record",
		u"Druckansicht des gesamten Datensatzes erzeugen"
		)
	dictionary["animalgenerateformtooltip"] = (
		"Generate a form using this animals details",
		u"Ein Formular mit den Angaben dieses Tieres erzeugen"
		)
	dictionary["animalappointmentslabel"] = (
		"Appointments",
		u"Behandlungstermine"
		)
	dictionary["animalcreateappointmenttooltip"] = (
		"Create an appointment for this animal",
		u"Einen Behandlungstermin für dieses Tier erzeugen"
		)
	dictionary["animaleditappointmenttooltip"] = (
		"Edit the selected appointment",
		u"Den ausgewählten Behandlungstermin bearbeiten"
		)
	dictionary["animalrefreshappointmentstooltip"] = (
		"Refresh the list of appointments",
		u"NDie Liste der Behandlungstermine aktualisieren"
		)
	dictionary["animaldeleteappointmenttooltip"] = (
		"Delete the selected appointment",
		u"Die ausgewählten Behandlungstermine löschen"
		)
	dictionary["animalprintappointmenttooltip"] = (
		"Generate printable output for the selected appointment",
		u"Eine Druckansicht für den ausgewählten Behandlungstermin erzeugen"
		)
	dictionary["animalvetformbutton"] = (
		("Vet Form", "Edit the vet form for the selected appointment"),
		(u"Tierarztformular", u"Das Tierarztformular für den ausgewählten Behanslungstermin bearbeiten")
		)
	dictionary["animalappointmentdetailslabel"] = (
		"Appointment Details",
		u"Details des Behandlungstermins"
		)
	dictionary["animalvaccinationslabel"] = (
		"Vaccinations",
		u"Impfungen"
		)
	dictionary["animalsavebuttontooltip"] = (
		"Save any changes made to this animal record",
		u"Änderungen dieses Datensatzes speichern"
		)
	dictionary["animalunsavedchangesmessage"] = (
		"This animal record has unsaved changes, are you sure you want to close?",
		u"Dieser Datensatz enthält ungesicherte Änderungen, trotzdem schließen?"
		)
	dictionary["animalconfirmdeleteappointmentmessage"] = (
		"Really delete appointment?",
		u"Soll der Behandlungstermin wirklich gelöscht werden?"
		)
	dictionary["animalresetvaccinationentries"] = (
		"Reset vaccination entries",
		u"Impfeinträge zurücksetzen"
		)
	dictionary["animalvaccinelabel"] = (
		"Vaccine",
		u"Impfen"
		)
	dictionary["animalgivenlabel"] = (
		"Given: ",
		u"Es liegt vor: "
		)
	dictionary["animalnextlabel"] = (
		" Next: ",
		u" Nächster: "
		)
	dictionary["animaldeletevaccinationtooltip"] = (
		"Delete the selected vaccination",
		u"Die ausgewählte Impfung löschen"
		)
	dictionary["animalsubmitvaccinationtooltip"] = (
		"Submit this vaccination",
		u"Diese Impfung abspeichern"
		)
	dictionary["animalconfirmdeletevaccinationmessage"] = (
		"Are you sure that you want to delete this vaccination?",
		u"Sind Sie sicher, dass Sie diese Impfung löschen wollen"
		)
	dictionary["animalvaccinationbatchlabel"] = (
		" Batch: ",
		u" Stapelverarbeitung: "
		)
	
	##Appointments
	
	dictionary["appointmentappointmentforlabel"] = (
		"Appointment for",
		u"Behandlungsttermin für"
		)
	dictionary["appointmentoperationforlabel"] = (
		"Operation for",
		u"Operation für"
		)
	dictionary["appointmententervettooltip"] = (
		"If this appointment is for a specific vet, enter the vet's name here",
		u"Wenn dieser Termin für einen bestimmten Tierarzt ist, dann bitte dessen Namen hier eingeben"
		)
	dictionary["appointmentrefreshtooltip"] = (
		"Refresh the list of appointments",
		u"Die Liste der Behandlungstermine aktualisieren"
		)
	dictionary["appointmentreasonlabel"] = (
		"Reason For Appointment",
		u"Grund für Behandlungstermin"
		)
	dictionary["appointmenttimelabel"] = (
		"Appointment time",
		u"Uhrzeit"
		)
	dictionary["appointmentisopcheckbox"] = (
		("Operation?", "Tick this box if you would like to book an operation"),
		(u"Operation?", u"Zum Buchen einer Operation dieses Kästchen selektieren")
		)
	dictionary["appointmentsubmittooltip"] = (
		"Submit this appointment",
		u"Behandlungstermin speichern"
		)
	dictionary["appointmentdeletetooltip"] = (
		"Delete this appointment",
		u"Behandlungstermin löschen"
		)
	dictionary["appointmentstatuslabel"] = (
		"Status",
		u"Status"
		)
	dictionary["appointmentnotarrivedlabel"] = (
		"Not Arrived",
		u"Nicht angekommen"
		)
	dictionary["appointmentwaitinglabel"] = (
		"Waiting",
		u"Wartet"
		)
	dictionary["appointmentwithvetlabel"] = (
		"With Vet",
		u"Beim Tierarzt"
		)
	dictionary["appointmentdonelabel"] = (
		"Done",
		u"Fertig"
		)
	dictionary["appointmenteditownerbutton"] = (
		("Edit Owner", "Edit client record"),
		(u"Besitzer bearbeiten", u"Kundendaten bearbeiten")
		)
	dictionary["appointmenteditanimalbutton"] = (
		("Edit Animal", "Edit animal record"),
		(u"Tier bearbeiten", u"Datensatz des Tieres bearbeiten")
		)
	dictionary["appointmentappointmentsforlabel"] = (
		"Appointments for",
		u"Behandlungstermin für"
		)
	dictionary["appointmentoperationsforlabel"] = (
		"Operations for",
		u"Operation von"
		)
	dictionary["appointmenttimetooearlymessage"] = (
		"Appointment time is before the practice opens!",
		u"Uhrzeit des Termins liegt vor dem Arbeitsbeginn"
		)
	dictionary["appointmenttimetoolatemessage"] = (
		"Appointment time is after the practice closes!",
		u"Uhrzeit des Termins liegt nach dem Arbeitsende"
		)
	dictionary["appointmentinvalidtimemessage"] = (
		"Invalid time - times must be HH:MM!",
		u"Ungültiges Format - bitte als HH:MM angeben."
		)
	
	##Client search panel
	
	dictionary["clientsearchpagetitle"] = (
		"Client Search",
		u"Kundensuche"
		)
	dictionary["clientsearchstitlelabel"] = (
		"Clients",
		u"Kunden"
		)
	dictionary["clientsearchsurnamelabel"] = (
		"Surname",
		u"Nachname"
		)
	dictionary["clientsearchphonelabel"] = (
		"Phone",
		u"Telefon"
		)
	dictionary["clientsearchaddresslabel"] = (
		"Address",
		u"Adresse"
		)
	dictionary["clientsearchpostcodelabel"] = (
		"Postcode",
		u"PLZ"
		)
	dictionary["clientsearchemaillabel"] = (
		"Email",
		u"Email"
		)
	dictionary["clientsearchclearbutton"] = (
		("Clear", "Clear all entries"),
		(u"Löschen", u"Alle Einträge löschen")
		)
	dictionary["clientsearchsearchbutton"] = (
		("Search", "Perform the search"),
		(u"Suchen", u"Suche durchführen")
		)
	dictionary["clientsearcheditclienttooltip"] = (
		"Edit the selected client record",
		u"Den ausgewählten Kundendatensatz editieren"
		)
	dictionary["clientsearchdeleteclienttooltip"] = (
		"Delete the selected client record",
		u"Den ausgewählten Kundendatensatz löschen"
		)
	dictionary["clientsearchanimallabel"] = (
		"Animals",
		u"Tiere"
		)
	dictionary["clientsearchanimalnamelabel"] = (
		"Name",
		u"Name"
		)
	dictionary["clientsearchanimalsexlabel"] = (
		"Sex",
		u"Geschlecht"
		)
	dictionary["clientsearchanimalspecieslabel"] = (
		"Species",
		u"Art"
		)
	dictionary["clientsearchanimalbreedlabel"] = (
		"Breed",
		u"Rasse"
		)
	dictionary["clientsearchanimalchipnolabel"] = (
		"Chip #",
		u"Chip #"
		)
	dictionary["clientsearchanimalcommentslabel"] = (
		"Comments",
		u"Bemerkungen"
		)
	dictionary["clientsearcheditanimaltooltip"] = (
		"Edit the selected animal record",
		u"Den ausgewählten Tierdatensatz editieren"
		)
	dictionary["clientsearchdeleteanimaltooltip"] = (
		"Delete the selected animal record",
		u"Den ausgewählten Tierdatensatz löschen"
		)
	dictionary["clientreceiptchangeloglabel"] = (
		"Receipt item - ",
		u"Rezeptposten - "
		)
	dictionary["clientreceiptdeletemessage"] = (
		"Really delete this receipt entry?",
		u"Diesen Rezeptdatensatz löschen"
		)
	dictionary["clientclearpaymenttooltip"] = (
		"Empty the payment entry",
		u"Den Zahlungsdatensatz leeren"
		)
	dictionary["clientpaymentlabel"] = (
		"Payment",
		u"Zahlung"
		)
	dictionary["clientsubmitpaymenttooltip"] = (
		"Submit Payment",
		u"Zahlung abschicken"
		)
	dictionary["clientpaymentinreceiptlabel"] = (
		"Payment",
		u"Zahlung"
		)
	
	##Launch panels
	
	dictionary["launchcreateconffilemessage"] = (
		"Conf file not found! Create one now?",
		u"Die Konfigurationsdatei wurde nicht gefunden. Neu erstellen?"
		)
	dictionary["launchevettefoldermessage"] = (
		"Evette folder not found! Create it now?",
		u"Das Evette-Verzeichnis wurde nicht gefunden. Jetzt erstellen?"
		)
	dictionary["launchnodatabaseservermessage"] = (
		"Unable to connect to database server! Please check that it is installed and running. Would you like to adjust your local settings?",
		u"Keine Verbindung zum Datenbank-Server. Bittel überprüfen, ob ein Datenbank-Server installiert ist und läuft. Möchten Sie Ihre lokalen Eisntellungen anpassen?"
		)
	dictionary["launchnoevettedatabasemessage"] = (
		"Unable to locate evette database! Would you like to create one now?",
		u"die Evette Datenbank wurde nicht gefunden. Jetzt erstellen?"
		)
	dictionary["launchconffilecreatedmessage"] = (
		"Conf file created",
		u"Konfigurationsdatei erstellt."
		)
	dictionary["launchevettefoldercreatedmessage"] = (
		"Evette folder created",
		u"Evette-Verzeichnis erstellt."
		)
	dictionary["launchdbiplabel"] = (
		"DB IP",
		u"Datenbank IP-Adresse"
		)
	dictionary["launchdbuserlabel"] = (
		"DB User",
		u"Datenbank-Benutzer"
		)
	dictionary["launchdbpasslabel"] = (
		"DB Pass",
		u"Datenbank-Passwort"
		)
	dictionary["launchunabletocreatedatabasemessage"] = (
		"Unable to create database, please check your mysql server config!",
		u"Die Datenbank konnte nicht erstellt werden. Bitte die MySQL-Einstellungen überprüfen."
		)
	dictionary["launchdatabasecreatedmessage"] = (
		"Database created successfully!",
		u"Datenbank wurde erstellt."
		)
	dictionary["launchlogintooltip"] = (
		"Log in",
		u"Anmelden"
		)
	
	##Lookups
	
	dictionary["lookupscolourpagetitle"] = (
		"Edit Colour Lookups",
		u"Auswahllisten für Farben bearbeiten"
		)
	dictionary["lookupsspeciespagetitle"] = (
		"Edit Species Lookups",
		u"Auswahllisten für Tierarten bearbeiten"
		)
	dictionary["lookupsbreedpagetitle"] = (
		"Edit Breed Lookups",
		u"Auswahllisten für Rassen bearbeiten"
		)
	dictionary["lookupsrefreshtooltip"] = (
		"Refresh the list",
		u"Die Liste aktualisieren"
		)
	dictionary["lookupsdeletetooltip"] = (
		"Delete the selected lookup",
		u"Die selektierte Auswahlliste löschen."
		)
	dictionary["lookupssubmittooltip"] = (
		"Submit lookup",
		u"Auswahlliste speichern"
		)
	dictionary["lookupsduplicatemessage"] = (
		"That lookup already exists, it's pointless putting it in again!",
		u"Die Auswahlliste existiert schon."
		)
	dictionary["lookupsnonamemessage"] = (
		"You must give a name for this lookup!",
		u"Sie müssen dieser Auswahlliste einen Namen geben."
		)
	dictionary["lookupsdeletemessage"] = (
		"Are you sure that you want to delete this lookup?",
		u"Sind Sie sicher, dass Sie diese Auswahlliste löschen möchten"
		)
	
	##Medication
	
	dictionary["medicationeditmedicationpagetitle"] = (
		"Edit Medication",
		u"Medikament bearbeiten"
		)
	dictionary["medicationrefreshtooltip"] = (
		"Edit Medication",
		u"Medikament bearbeiten"
		)
	dictionary["medicationdeletetooltip"] = (
		"Delete the selected medication",
		u"Das ausgewählte Medikament löschen"
		)
	dictionary["medicationbatchnolabel"] = (
		"Batch #",
		u"Stapelnr."
		)
	dictionary["medicationbatchmovementreporttooltip"] = (
		"Generate a report showing all movements of this batch",
		u"Einen Bericht mit allen Veränderungen dieses Stapels erstellen"
		)
	dictionary["medicationstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Drucken Sie eine Liste Ihres aktuellen Vorrats."
		)
	dictionary["medicationmovementsoflabel"] = (
		"Movements of ",
		u"Änderungen von "
		)
	dictionary["medicationconfirmdeletemessage"] = (
		"Are you sure you want to delete ",
		"Bestätigen Sie das Löschen von "
		)
	dictionary["medicationconfirmoverwritemessage"] = (
		"Are you sure you want to overwrite this medication?",
		u"Sind Sie sicher, dass Sie  dieses Medikamentes überschreiben wollen?"
		)
	dictionary["medicationmovementsofbatchnumberlabel"] = (
		"Movements of Batch Number ",
		u"Änderungen von Stapel Nr. "
		)
	dictionary["medicationexpireslabel"] = (
		"Expires",
		u"Läuft ab"
		)
	dictionary["medicationrefreshdetailstooltip"] = (
		"Refresh the details of this medication",
		u"Die Angaben zu diesem Medikament aktualisieren"
		)
	dictionary["medicationdeletemovementtooltip"] = (
		"Delete this medication movement",
		u"Die Änderungen dieses Medikamentes löschen"
		)
	dictionary["movementmovementlabel"] = (
		"Movement",
		"Änderung"
		)
	dictionary["movementoverwritemovementmessage"] = (
		"Are you sure that you want to overwrite this movement?",
		u"Sind Sie sicher, dass Sie diese Änderung überschreiben möchten?"
		)
	dictionary["movementconfirmdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Bist Sie gewiß jene Sie wollt zu ausstreichen dieses Bewegung?"
		)
	dictionary["movementrefreshmovementsmessage"] = (
		"Refresh the details of this medication",
		u"Die Angaben zu diesem Medikament aktualisieren"
		)
	dictionary["movementresetsearchentriestooltip"] = (
		"Reset search entries",
		u"Suchkriterien zurücksetzen"
		)
	dictionary["medicationcurrentbatchlabel"] = (
		"Current Batch",
		u"Aktueller Stapel"
		)
	dictionary["medicationunitpricelabel"] = (
		"Unit Price",
		u"Preis pro Einheit"
		)
	
	##Weekdays
	dictionary["monday"] = (
		"Monday",
		u"Montag"
		)
	dictionary["tuesday"] = (
		"Tuesday",
		u"Dienstag"
		)
	dictionary["wednesday"] = (
		"Wednesday",
		u"Mittwoch"
		)
	dictionary["thursday"] = (
		"Thursday",
		u"Donnerstag"
		)
	dictionary["friday"] = (
		"Friday",
		u"Freitag"
		)
	dictionary["saturday"] = (
		"Saturday",
		u"Samstag"
		)
	dictionary["sunday"] = (
		"Sunday",
		u"Sonntag"
		)
	
	
	##Procedures
	
	dictionary["editprocedurespagetitle"] = (
		"Edit Procedures",
		u"Prozeduren bearbeiten"
		)
	dictionary["proceduresrefreshprocedurestooltip"] = (
		"Refresh the list of procedures",
		u"Die Liste der Prozeduren bearbeiten"
		)
	dictionary["proceduresdeleteproceduretooltip"] = (
		"Delete the selected procedure",
		u"Die ausgewählte Prozedur löschen"
		)
	dictionary["proceduresunnamedproceduremessage"] = (
		"You must give this procedure a name!",
		u"Sie müssen diese Prozedur benennen"
		)
	dictionary["proceduresoverwritemessage"] = (
		"Are you sure that you want to edit this procedure?",
		u"Sind Sie sicher, dass Sie diese Prozedur bearbeiten wollen?"
		)
	dictionary["proceduresdeletemessage"] = (
		"Are you sure that you want to delete this procedure?",
		u"Sind Sie sicher, dass Sie diese Prozedur löschen wollen?"
		)
	
	##Random data
	
	dictionary["randomdatapagetitle"] = (
		"Random Data",
		u"Demo-Daten"
		)
	dictionary["randomdatanoofclientslabel"] = (
		"No of clients",
		u"Anzahl von Kunden"
		)
	dictionary["randomdatanoofanimalslabel"] = (
		"No of animals",
		u"Anzahl von Tieren"
		)
	dictionary["randomdatanoofappointmentslabel"] = (
		"No of appointments",
		u"Anzahl von Terminen"
		)
	dictionary["randomdatanoofoperationslabel"] = (
		"No of operations",
		u"Anzahl von Operationen"
		)
	dictionary["randomdatanoofmedicationslabel"] = (
		"No of medications",
		u"Anzahl von Medikamenten"
		)
	dictionary["randomdataclientslabel"] = (
		"Clients",
		u"Kunden"
		)
	dictionary["randomdataanimalslabel"] = (
		"Animals",
		u"Tiere"
		)
	dictionary["randomdataappointmentslabel"] = (
		"Appointments",
		u"Termine"
		)
	dictionary["randomdataoperationslabel"] = (
		"Operations",
		u"Operationen"
		)
	dictionary["randomdatamedicationlabel"] = (
		"Medication",
		u"Medikament"
		)
	dictionary["randomdatasubmittooltip"] = (
		"Create random data",
		u"Demodaten erstellen"
		)
	
	##Settings Panel
	
	dictionary["settingspracticenamelabel"] = (
		"Practice Name",
		u"Praxisname"
		)
	dictionary["settingsopenfromlabel"] = (
		"Open from",
		u"Geöffnet ab"
		)
	dictionary["settingsopentolabel"] = (
		"Open to",
		u"Geöffnet bis"
		)
	dictionary["settingsoperatingtimelabel"] = (
		"Operating time",
		u"Operationszeiten"
		)
	dictionary["settingshtmlviewerlabel"] = (
		"HTML viewer",
		u"HTML Betrachter"
		)
	dictionary["settingsfindhtmlviewertooltip"] = (
		"HTML viewer",
		u"HTML Betrachter"
		)
	dictionary["settingslanguagelabel"] = (
		"Language",
		u"Sprache"
		)
	
	##Staff settings
	
	dictionary["editvetformlabel"] = (
		"Edit Vet Form",
		u"Tierarztformular bearbeiten"
		)
	dictionary["editfinanceslabel"] = (
		"Edit Finances",
		u"Finanzen bearbeiten"
		)
	dictionary["showtoolbarlabel"] = (
		"Show Toolbar",
		u"Werkzeugleiste bearbeiten"
		)
	dictionary["viewchangeloglabel"] = (
		"View Changelogs",
		u"Änderungs-Logs betrachten"
		)
	dictionary["editsettingslabel"] = (
		"Edit Settings",
		u"Einstellungen bearbeiten"
		)
	dictionary["editrotalabel"] = (
		"Edit Rota",
		u"Behandlungspläne bearbeiten"
		)
	dictionary["editstaffpagetitle"] = (
		"Edit Rota",
		u"Behandlungspläne bearbeiten"
		)
	dictionary["staffmemberlabel"] = (
		"Staff Member",
		u"Team-Mitglied"
		)
	dictionary["deleteusertooltip"] = (
		"Delete the selected user",
		u"Den selektierten Benutzer löschen"
		)
	dictionary["clientslabel"] = (
		"Clients",
		u"Kunden"
		)
	dictionary["animalslabel"] = (
		"Animals",
		u"Tiere"
		)
	dictionary["appointmentslabel"] = (
		"Appointments",
		u"Termine"
		)
	dictionary["medicationlabel"] = (
		"Medication",
		u"Medikament"
		)
	dictionary["procedureslabel"] = (
		"Clients",
		u"Kunden"
		)
	dictionary["lookupslabel"] = (
		"Lookups",
		u"Auswahllisten"
		)
	dictionary["formslabel"] = (
		"Forms",
		u"Formulare"
		)
	dictionary["userslabel"] = (
		"Users",
		u"Benutzer"
		)
	dictionary["misclabel"] = (
		"Misc",
		u"Diverse"
		)
	dictionary["tickalllabel"] = (
		"Tick All",
		u"Alle auswählen"
		)
	dictionary["tickalltooltip"] = (
		"Give the user permission to use ALL areas of the system. Use with care!",
		u"Dem Benutzer die Erlaubnis für alle Bereiche des System erteilen."
		)
	dictionary["useroverwritemessage"] = (
		"Are you sure that you want to overwrite this user?",
		u"Sind Sie sicher, dass Sie diesen Benutzer überschreiben wollen?"
		)
	dictionary["userdeletemessage"] = (
		"Are you sure that you want to delete this user?",
		u"Sind Sie sicher, dass Sie diesen Benutzer löschen wollen?"
		)
	
	##Edit Rota
	
	dictionary["editrotapagetitle"] = (
		"Edit Rota",
		u"Behandlungspläne bearbeiten"
		)
	dictionary["timeonlabel"] = (
		"Time On",
		u"Zeit läuft"
		)
	dictionary["timeofflabel"] = (
		"Time Off",
		u"Zeit angehalten"
		)
	dictionary["operatinglabel"] = (
		"Operating",
		u"In einer Operation"
		)
	dictionary["staffsummarylabel"] = (
		"Staff Summary",
		u"Team-Zusammenfassung"
		)
	dictionary["dayplanlabel"] = (
		"Day Plan",
		u"Tagesplan"
		)
	dictionary["novetnamemessage"] = (
		"You must enter a vets name!",
		u"Sie müssen den Namen eines Tierarztes angeben"
		)
	dictionary["vetfinishedbeforestartingmessage"] = (
		"The vet cannot finish before starting!",
		u"Der Behandlungsstart kann nicht vor dem behandlungsende liegen"
		)
	dictionary["vettwoplacesatoncemessage"] = (
		"This person cannot be in two places at once!",
		u"Die Person kann nicht an zwei Orten gleichzeitig sein"
		)
	
	##Vaccinations
	
	dictionary["vaccinationseditvaccinationspagetitle"] = (
		"Edit Vaccinations",
		u"Impfungen bearbeiten"
		)
	dictionary["vaccinationsvaccinelabel"] = (
		"Vaccine",
		u"Impfen"
		)
	dictionary["vaccinationsrefreshvaccinationstooltip"] = (
		"Refresh the list of vaccinations",
		u"Die Liste der Impfungen aktualisieren"
		)
	dictionary["vaccinationsdeletevaccinationstooltip"] = (
		"Delete the selected vaccination",
		u"Die selektierten Impfungen löschen"
		)
	dictionary["vaccinationsprintstocklisttooltip"] = (
		"Print a list of your current stock",
		u"Eine Liste des aktuellen Vorrats ausdrucken"
		)
	dictionary["vaccinationsconfirmdeletevaccinationmessage"] = (
		"Are you sure you want to delete this vaccination?",
		u"Sind Sie sicher, dass Sie die selektierte Impfung löschen wollen?"
		)
	dictionary["vaccinationsconfirmoverwritevaccinationmessage"] = (
		"Are you sure you want to overwrite this vaccination?",
		u"Sind Sie sicher, dass Sie diese Impfung überschreiben möchten?"
		)
	dictionary["vaccinationsrefreshmovementstooltip"] = (
		"Refresh the details of this vaccination",
		u"die Angaben zu dieser Imfpung aktualisieren"
		)
	dictionary["vaccinationsdeletemovementtooltip"] = (
		"Delete this vaccination movement",
		u"Die Änderung dieser Impfung löschen"
		)
	dictionary["vaccinationsoverwritemovementmessage"] = (
		"Are you sure that you want to edit this movement?",
		u"Sind Sie sicher, dass Sie diese Impfng bearbeiten möchten"
		)
	dictionary["vaccinationsdeletemovementmessage"] = (
		"Are you sure that you want to delete this movement?",
		u"Sind Sie sicher, dass Sie diese Änderung löschen möchten?"
		)
	
	
	##Vet Form
	
	dictionary["vetformpagetitle"] = (
		"Vet Form",
		u"Tierarztformular"
		)
	dictionary["vetformotherappointmentslabel"] = (
		"Appointment History",
		u"Termin-Historie"
		)
	dictionary["vetformappointmentdetailslabel"] = (
		"Appointment Details",
		u"Termin-Details"
		)
	dictionary["vetformmedlabel"] = (
		"Med",
		u"Med"
		)
	dictionary["vetformvacclabel"] = (
		"Vacc",
		u"Vacc"
		)
	dictionary["vetformproclabel"] = (
		"Proc",
		u"Proc"
		)
	dictionary["vetformmanlabel"] = (
		"Man",
		u"Man"
		)
	dictionary["vetformdeletereceipttooltip"] = (
		"Delete the selected item from the receipt",
		u"Den selektierten Posten vom Rezept löschen"
		)
	dictionary["vetformdonetooltip"] = (
		"Mark this appointment as complete and close",
		u"Diesen Termin als beendet erklären und schließen"
		)
	dictionary["vetformsavetooltip"] = (
		"Save any changes made to this vet form",
		u"Änderungen an diesem Tierarztformular speichern"
		)
	dictionary["vetformreceiptitemlabel"] = (
		"Receipt Item",
		u"Rezeptposten"
		)
	dictionary["vetformdeletereceiptmessage"] = (
		"Are you sure you want to delete this receipt item?",
		u"Sind Sie sicher, dass Sie diesen Rezeptposten löschen möchten?"
		)
	dictionary["vetformmedicationclearcontainstooltip"] = (
		"Clear the \"Contains\" entry",
		u"Den \"Enthält\"-Eintrag löschen"
		)
	dictionary["vetformrefreshmedicationtooltip"] = (
		"Refresh the medication list",
		u"Die Medikamentenliste aktualisieren"
		)
	dictionary["vetformnoofunitstooltip"] = (
		"Enter the number of units that you are dispensing here",
		u"Die Anzahl der ausgegebenen Einheiten hier eintragen"
		)
	dictionary["vetforminstructionslabel"] = (
		"Instructions",
		u"Anweisungen"
		)
	dictionary["vetforminstructionstooltip"] = (
		"Enter instructions on how to administer this medication here",
		u"Die Anweisungen zur Verwaltung der Medikamente hier eintragen"
		)
	dictionary["vetformprintlabeltooltip"] = (
		"Print a label for this medication",
		u"Ein Etikett für dieses Medikament ausdrucken"
		)
	dictionary["vetformbatchnotooltip"] = (
		"Enter the batch number here",
		u"Die Stapelnr. hier eintragen"
		)
	dictionary["vetformrefreshvaccinationtooltip"] = (
		"Refresh the vaccination list",
		u"Die Impfliste aktualisieren"
		)
	dictionary["vetformrefreshprocedurestooltip"] = (
		"Refresh the procedures list",
		u"Die Produktliste aktualisieren"
		)
	dictionary["vetformnodescriptionmessage"] = (
		"You must give a description!",
		u"Sie müssen eine Beschreibung eingeben."
		)
	
	##View Appointments
	
	dictionary["viewappointmentspagetitle"] = (
		"View Appointments",
		u"Termine betrachten"
		)
	dictionary["viewoperationsspagetitle"] = (
		"View Operations",
		u"Operationen betrachten"
		)
	dictionary["viewappointmentsmarkwithvettooltip"] = (
		"Mark this appointment as with the vet",
		u"Diesen Termin als \"Beim Tierarzt\" markieren."
		)
	dictionary["viewappointmentschoosevettooltip"] = (
		"Choose a vet",
		u"Einen Tierarzt auswählen."
		)
	dictionary["viewappointmentsvetformtooltip"] = (
		"Carry out the vet visit for this appointment",
		u"Den Tierarztbesuch für diesen Termin durchführen."
		)
	dictionary["viewappointmentsmarkarrivedtooltip"] = (
		"Mark this appointment as arrived",
		u"Diesen Termin als \"angekommen\"kennzeichen."
		)
	dictionary["viewappointmentsmarkdonetooltip"] = (
		"Mark this appointment as done",
		u"Diesen Termin als \"beendet\"kennzeichen."
		)
	dictionary["viewappointmentseditclientbuttonlabel"] = (
		"Edit Client",
		u"Kunden bearbeiten"
		)
	dictionary["viewappointmentseditclientbuttontooltip"] = (
		"Edit this clients record (so they can pay their bill)",
		u"Kundendatensatz bearbeiten (damit die Rechnung bezahlt werden kann)."
		)
	dictionary["viewappointmentsvetsonlabel"] = (
		"Vets On",
		u"Tierarzt hat Termin"
		)
	dictionary["appointmentsearchpagetitle"] = (
		"Appointment Search",
		u"Terminsuche"
		)
	dictionary["appointmentsearchmenu"] = (
		("Appointment Search", "Find an appointment"),
		(u"Terminsuche", u"Einen Termin finden")
		)
	dictionary["appointmentsearchanimalnamelabel"] = (
		"Animal Name",
		u"Tiername"
		)
	dictionary["reasonlabel"] = (
		"Reason",
		u"Grund"
		)
	dictionary["viewoperationspagetitle"] = (
		"View Operations",
		u"Operationen betrachten."
		)
	dictionary["dateformat"] = (
		"DDMMYYYY",
		"DDMMYYYY"
		)
	dictionary["currency"] = (
		"&pound;",
		u"EUR "
		)
	dictionary["mailshotmenu"] = (
		("Mail Shot", "Compile a list of clients to contact"),
		(u"Serienbrief", u"Eine Kontaktliste zusammentstellen")
		)
	dictionary["mailshotpagetitle"] = (
		"Mail Shot",
		u"Serienbrief"
		)
	dictionary["anyvaccine"] = (
		"Any Vaccine",
		u"Jede Impfung"
		)
	dictionary["anyspecies"] = (
		"Any Species",
		u"Jede Tierart"
		)
	dictionary["deceasedlabel"] = (
		"Deceased",
		u"Gestorben"
		)
	dictionary["causeofdeathlabel"] = (
		"Cause of Death",
		u"Todesursache"
		)
	dictionary["includedeceasedlabel"] = (
		"Include Deceased",
		u"Gestorbene miteinbeziehen"
		)
	dictionary["createvaccinationappointmentbutton"] = (
		("Create Appointment", "Create an appointment for this vaccination"),
		(u"Termin erstellen", u"Einen Termin für diese Impfung erstellen.")
		)
	dictionary["generatevaccinationcsvbutton"] = (
		("Create CSV File", "Create and save a CSV file to disc. This can be used by most word processors to create mail shots"),
		(u"CSV-Datei erstellen", u"Eine CSV-Datei erstellen und auf Platte speichern. Kann für Serienbriefe benutzt werden.")
		)
	dictionary["csvsavedtolabel"] = (
		"CSV file saved to",
		u"CSV-Datei, in die gespeichert wurde"
		)
	dictionary["versiontablenotfoundquestion"] = (
		"Version table not found, create it now?",
		u"Versiontabelle wurde nicht gefunden, jetzt erstellen?"
		)
	dictionary["versionupdatequestion1"] = (
		"You are attempting to run evette",
		u"Sie versuchen evette zu starten."
		)
	dictionary["versionupdatequestion2"] = (
		"your database is version",
		u"Ihre Datenbankversion ist "
		)
	dictionary["versionupdatequestion3"] = (
		"Would you like to upgrade your database?",
		u"Möchten Sie ein Upgrade Iher Datenbank vornehmen?"
		)
	dictionary["resetdatabasequestion"] = (
		"Are you sure that you want to reset all tables? ALL DATA WILL BE LOST!",
		u"Sind Sie sicher, dass Sie alle Tabellen zurücksetzen möchten? ALLE DATEN GEHEN VERLOREN!"
		)
	dictionary["alltablesresetmessage"] = (
		"All tables have been reset!",
		u"Alle Tabellen wurden zurückgesetzt"
		)
	dictionary["addstafflabel"] = (
		"Add staff?",
		u"Mitarbeiter hinzufügen?"
		)
	dictionary["vetslabel"] = (
		"Vets",
		u"Tierärzte"
		)
	dictionary["nurseslabel"] = (
		"Nurses",
		u"Pflegepersonal"
		)
	dictionary["otherslabel"] = (
		"Others",
		u"Andere"
		)
	dictionary["nextmonthtooltip"] = (
		"Show next month",
		u"Den nächsten Monat anzeigen."
		)
	dictionary["previousmonthtooltip"] = (
		"Show previous month",
		u"Den vorigen Monat anzeigen."
		)
	dictionary["backtocalendartooltip"] = (
		"Back to calendar",
		u"Zurück zum Kalender"
		)
	dictionary["addstafftodailyrotatooltip"] = (
		"Add a member of staff to this days rota",
		u"Diesem Tagesplan einen Mitarbeiter hinzufügen."
		)
	dictionary["deleterotaitemtooltip"] = (
		"Delete this rota entry",
		u"Diesen Eintrag des Behandlungsplanes löschen."
		)
	dictionary["submitrotaitemtooltip"] = (
		"Submit this rota entry",
		u"Diesen Eintrag des Behandlungsplanes speichern."
		)
	dictionary["vetpositiontitle"] = (
		"Vet",
		u"Vet"
		)
	dictionary["vetnursepositiontitle"] = (
		"Nurse",
		u"Pfleger"
		)
	dictionary["managerpositiontitle"] = (
		"Manager",
		u"Manager"
		)
	dictionary["errorlabel"] = (
		"Sorry, the following error has occured",
		u"Der folgende Fehler ist aufgetreten"
		)
	dictionary["editdiarytoolbar"] = (
		("Edit Diary", "Edit the diary"),
		(u"Aufbereiten Notizbuch", u"Aufbereiten die Notizbuch")
		)
	dictionary["editdiarypagetitle"] = (
		"Edit Diary",
		u"Aufbereiten Notizbuch"
		)
	dictionary["notesuptolabel"] = (
		"Up to",
		u"Bis zu"
		)
	dictionary["subjectcontainslabel"] = (
		"Subject contains",
		u"Unterziehen beinhaltet"
		)
	dictionary["notecontainslabel"] = (
		"Note contains",
		u"Vermerken beinhaltet"
		)
	dictionary["showremovedlabel"] = (
		"Include removed?",
		u"Aufnehmen entfernt?"
		)
	dictionary["subjectlabel"] = (
		"Subject",
		u"Subjekt"
		)
	dictionary["notelabel"] = (
		"Note",
		u"Notiz"
		)
	dictionary["removedlabel"] = (
		"Removed",
		u"Removed"
		)
	dictionary["linklabel"] = (
		"Link",
		u"Anbinden"
		)
	dictionary["clientlabel"] = (
		"Client",
		u"Klient"
		)
	dictionary["animallabel"] = (
		"Animal",
		u"Tier"
		)
	dictionary["opentargetrecordtooltip"] = (
		"Open the record linked to this diary note",
		u"Übersichtlich die zu Buche bringen verbunden hierzu Notizbuch vermerken"
		)
	dictionary["diarynotelabel"] = (
		"Diary Note",
		u"Notizbuch Vermerken"
		)
	dictionary["confirmdeletediarynotemessage"] = (
		"Are you sure that you want to delete this diary note?",
		u"Bist Sie gewiß jene Sie wollt zu ausstreichen dieses Notizbuch vermerken?"
		)
	dictionary["nolinklabel"] = (
		"No Link",
		u"Null Anbinden"
		)
	dictionary["createassociateddiarynotetooltip"] = (
		"Create a diary note associated with this record",
		u"Anlegen ein Notizbuch vermerken angeschlossen zu diesem Zweck zu Buche bringen"
		)
	dictionary["newdiarynotetooltip"] = (
		"Create a new diary note",
		u"Anlegen ein neu Notizbuch vermerken"
		)
	dictionary["editdiarynotetooltip"] = (
		"Edit the selected diary note",
		u"Aufbereiten die ausgewählt Notizbuch vermerken"
		)
	dictionary["deletediarynotetooltip"] = (
		"Delete the selected diary note",
		u"Delete the selected diary note"
		)
	dictionary["refreshdiarytooltip"] = (
		"Refresh the list of diary notes",
		u"Erfrischen die aufführen über Notizbuch Tone"
		)
	dictionary["cleardiarytooltip"] = (
		"Clear the diary filters",
		u"Abdecken die Notizbuch Filter"
		)
	dictionary["clientolderthanservermessage"] = (
		"You are trying to run an out-of-date client, please upgrade then try again",
		u"Sie sind schwierig zu verkehren ein raus - über - ausgehen Klient , bitte ansteigend derzeitig versuchen wieder"
		)
	dictionary["adddiarynotes"] = (
		"Add to diary",
		u"Zurechnen Notizbuch"
		)
	dictionary["editdiarynotes"] = (
		"Edit diary",
		u"Aufbereiten Notizbuch"
		)
	dictionary["deletediarynotes"] = (
		"Delete from diary",
		u"Ausstreichen ab Notizbuch"
		)
	dictionary["diarylabel"] = (
		"Diary",
		u"Notizbuch"
		)
	dictionary["viewlicensemenu"] = (
		("View License", "View the license for this software."),
		(u"Überblick Lizenz", u"Überblick die Lizenz hierfür Software.")
		)
	dictionary["fileaccosiationmenu"] = (
		("File Associations", "Edit the external applications associated with attached files"),
		(u"Akte Verbände", u"Aufbereiten die auswärtig Bewerbungen angeschlossen mit befestigt Akten")
		)
	dictionary["licenselabel"] = (
		"License",
		u"Lizenz"
		)
	dictionary["aboutlabel"] = (
		"About",
		u"Bei"
		)
	dictionary["attachedfileslabel"] = (
		"Attached Files",
		u"Befestigt Akten"
		)
	dictionary["deleteattachedfileconfirm"] = (
		"Are you sure that you want to delete this file?",
		u"Bist Sie gewiß jene Sie wollt zu ausstreichen dieses Akte?"
		)
	dictionary["addnewmediatooltip"] = (
		"Add a new external file to this record",
		u"Addieren ein neu auswärtig Akte hierzu zu Buche bringen"
		)
	dictionary["replacemediatooltip"] = (
		"Update the description of the selected file",
		u"Aktualisierung die Beschreibung des ausgewählt Akte"
		)
	dictionary["deletemediatooltip"] = (
		"Delete the selected file",
		u"Ausstreichen die ausgewählt Akte"
		)
	dictionary["savemediatooltip"] = (
		"Save the selected file to disk",
		u"Sparen die ausgewählt Akte zu Scheibe"
		)
	dictionary["fileassociationspagetitle"] = (
		"File Associations",
		u"Akte Verbände"
		)
	dictionary["extensionlabel"] = (
		"Extension",
		u"Ausdehnung"
		)
	dictionary["programlabel"] = (
		"Program",
		u"Programme"
		)
	dictionary["fileassociationexistsmessage"] = (
		"There is already a program associated with this file extension!",
		u"Es ist bereits ein program angeschlossen zu diesem Zweck Akte Ausdehnung!"
		)
	dictionary["deleteassociationconfirm"] = (
		"Are you sure that you want to delete this file association?",
		u"Bist Sie gewiß jene Sie wollt zu ausstreichen dieses Akte Genossenschaft?"
		)
	dictionary["noprogramassociatedmessage"] = (
		"There is no program associated with this file type!",
		u"Es ist null program angeschlossen zu diesem Zweck Akte Typ!"
		)
	dictionary["mediatoolargemessage"] = (
		"This file is too large to attach!",
		u"Dieses Akte ist zu erklecklich zu anbringen!"
		)
	############################## 1.1.9 ###############################################
	
	dictionary["weightpanelpagetitle"] = (
		"Weight",
		u"Schwere"
		)
	dictionary["deleteweighttooltip"] = (
		"Delete the selected weight",
		u"Ausstreichen die ausgewählt Schwere"
		)
	dictionary["deleteweightconfirm"] = (
		"Are you sure that you want to delete this weight?",
		u"Bist Sie gewiß jene Sie wollt zu ausstreichen dieses Schwere?"
		)
	dictionary["samelabel"] = (
		"Same",
		u"Gleich"
		)
	dictionary["reorderlabel"] = (
		"Minimum",
		u"Mindestmaß"
		)
	dictionary["runninglowlabel"] = (
		"Running Low?",
		u"Rennend Mißraten?"
		)
	dictionary["diarymenu"] = (
		"&Diary",
		u"&Notizbuch"
		)
	
	############################## 1.2 ###############################################
	
	dictionary["clientanimalsearchtooltip"] = (
		"If you wish to filter the animals by name, enter the name here",
		u"Falls Sie Wunsch zu Filter die Tiere namentlich , beitreten die angebracht hier"
		)
	dictionary["browseappointmentsmenu"] = (
		( "Browse Appointments", "Browse all appointments" ),
		( u"Blättern Berufungen", u"Blättern alle Berufungen" )
		)
	dictionary["browseappointmentspagetitle"] = (
		"Browse Appointments",
		u"Blättern Berufungen"
		)
	dictionary["appointmentlabel"] = (
		"appointment",
		u"termine"
		)
	dictionary["januarylabel"] = (
		"January",
		u"Januar"
		)
	dictionary["februarylabel"] = (
		"February",
		u"Februar"
		)
	dictionary["marchlabel"] = (
		"March",
		u"März"
		)
	dictionary["aprillabel"] = (
		"April",
		u"April"
		)
	dictionary["maylabel"] = (
		"May",
		u"Mai"
		)
	dictionary["junelabel"] = (
		"June",
		u"Juni"
		)
	dictionary["julylabel"] = (
		"July",
		u"Juli"
		)
	dictionary["augustlabel"] = (
		"August",
		u"August"
		)
	dictionary["septemberlabel"] = (
		"September",
		u"September"
		)
	dictionary["octoberlabel"] = (
		"October",
		u"Oktober"
		)
	dictionary["novemberlabel"] = (
		"November",
		u"November"
		)
	dictionary["decemberlabel"] = (
		"December",
		u"Dezember"
		)
	dictionary["readfileassociationhelpmessage"] = (
		"To learn about file associations - visit the help section.",
		u"Zu erfahren bei Akte Verbände besuchen die abhelfen Referat."
                )
	dictionary["websitelabel"] = (
		"Website",
		u"New Language"
		)
	dictionary["generateinvoicelabel"] = (
		"Generate a printable invoice for this client",
		u"New Language"
		)
	#######################1.2.1#############################
	dictionary["animalformsmenu"] = (
		("Animal Forms", "Create or edit forms that be generated using an animal's details"),
		(u"New Language", u"New Language")
		)
	dictionary["clientformsmenu"] = (
		("Client Forms", "Create or edit forms that be generated using an client's details"),
		(u"New Language", u"New Language")
		)
	dictionary["animalformspagetitle"] = (
		"Animal Forms",
		u"New Language"
		)
	dictionary["clientformspagetitle"] = (
		"Client Forms",
		u"New Language"
		)
	dictionary["previewlabel"] = (
		"Preview",
		u"New Language"
		)
	dictionary["wordkeyslabel"] = (
		"Wordkeys",
		u"New Language"
		)
	dictionary["invoiceformsmenu"] = (
		("Invoice Forms", "Edit the invoice templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editinvoicepagetitle"] = (
		"Edit Invoices",
		u"New Language"
		)
	dictionary["medicationformsmenu"] = (
		("Medication Forms", "Edit the medication templates"),
		(u"New Language", u"New Language")
		)
	dictionary["editmedicationtformspagetitle"] = (
		"Medication Forms",
		u"New Language"
		)
	dictionary["invoicespagetitle"] = (
		"Invoices",
		u"New Language"
		)
	dictionary["newinvoicetooltip"] = (
		"Create a new invoice",
		u"New Language"
		)
	dictionary["editinvoicetooltip"] = (
		"Edit the selected invoice",
		u"New Language"
		)
	dictionary["deleteinvoicetooltip"] = (
		"Delete the selected invoice",
		u"New Language"
		)
	dictionary["invoiceoverlapmessage"] = (
		"Invoices are not allowed to overlap, please adjust the dates",
		u"New Language"
		)
	dictionary["clientgenerateformtooltip"] = (
		"Generate a form using this clients details",
		u"New Language"
		)
	dictionary["randomdatawarningmessage"] = (
		"Note: Evette will need close when this process has completed,\nplease start Evette again to see the results.",
		u"New Language"
		)
	dictionary["invoiceidlabel"] = (
		"Invoice ID",
		u"New Language"
		)
	dictionary["paidlabel"] = (
		"paid",
		u"New Language"
		)
	dictionary["unpaidlabel"] = (
		"unpaid",
		u"New Language"
		)
	dictionary["invoiceidchoicetooltip"] = (
		"Choose an invoice ID to mark an invoice as paid.",
		u"New Language"
		)
	dictionary["editpaymentinvoicetooltip"] = (
		"Edit the amount paid on the selected invoice.",
		u"New Language"
		)
	dictionary["editinvoicepaymenttitle"] = (
		"Edit payment",
		u"New Language"
		)
	dictionary["editanimaltooltip"] = (
		"Edit Animal",
		u"New Language"
		)
	###################1.2.2#####################
	dictionary["stocklabel"] = (
		"Stock",
		u"New Language"
		)
	dictionary["editstockmenu"] = (
		("Edit Stock", "Edit Stock"),
		("New Language", "New Language")
		)
	dictionary["batchsearchmenu"] = (
		("Batch Search", "Show movements for a specific batch number"),
		("New Language", "New Language")
		)
	dictionary["batchbreakdowntooltip"] = (
		"View a breakdown of the current stock by batch number",
		u"New Language"
		)
	dictionary["editmovementlabel"] = (
		"Edit Movement",
		u"New Language"
		)
	dictionary["createmovementlabel"] = (
		"Create Movement",
		u"New Language"
		)
	dictionary["consumablelabel"] = (
		"Consumable",
		u"New Language"
		)
	dictionary["shoplabel"] = (
		"Shop",
		u"New Language"
		)
	dictionary["procedurelabel"] = (
		"Procedure",
		u"New Language"
		)
	dictionary["manuallabel"] = (
		"Manual",
		u"New Language"
		)
	dictionary["prescribemedicationlabel"] = (
		"Prescribe Medication",
		u"New Language"
		)
	dictionary["quantitylabel"] = (
		"Quantity",
		u"New Language"
		)
	dictionary["quantityerrormessage"] = (
		"Invalid quantity",
		u"New Language"
		)
	dictionary["viewinvoicetooltip"] = (
		"View Invoice",
		u"New Language"
		)
	dictionary["diagnosislabel"] = (
		"Diagnosis",
		u"New Language"
		)
	dictionary["createreceiptitemtooltip"] = (
		"Create a receipt item",
		u"New Language"
		)
############################## 1.2.3 ###############################################
	dictionary["editkennelsmenu"] = (
		("Edit Kennels", "Edit kennels available"),
		(u"New Language", u"New Language")
		)
	dictionary["viewkennelsmenu"] = (
		("View Kennels", "View Kennels"),
		(u"New Language", u"New Language")
		)
	dictionary["kennelsmenu"] = (
		"&Kennels",
		u"New Language"
		)
	dictionary["kennelblocktitlelabel"] = (
		"Kennel Blocks",
		u"New Language"
		)
	dictionary["kennelstitlelabel"] = (
		"Kennels",
		u"New Language"
		)
	dictionary["editkennelblocktitle"] = (
		"Edit kennel block",
		u"New Language"
		)
	dictionary["deletekennelblockconfirmation"] = (
		"Are you sure that you want to delete this kennel block?",
		u"New Language"
		)
	dictionary["deletekennelconfirmation"] = (
		"Are you sure that you want to delete this kennel?",
		u"New Language"
		)
	dictionary["editkenneltitle"] = (
		"Edit kennel",
		u"New Language"
		)
	dictionary["stayinglabel"] = (
		"Staying",
		u"New Language"
		)
	dictionary["occupiedlabel"] = (
		"occupied",
		u"New Language"
		)
	dictionary["vacantlabel"] = (
		"vacant",
		u"New Language"
		)
	dictionary["changeownershiptooltip"] = (
		"Transfer ownership of this animal",
		u"New Language"
		)
	dictionary["choosenewownerdialogtitle"] = (
		"Choose new owner",
		u"New Language"
		)
	dictionary["doubleclicktoselecttooltip"] = (
		"Double click to select",
		u"New Language"
		)
	dictionary["importasmanimaltooltip"] = (
		"Create an animal record from an ASM record",
		u"New Language"
		)
	dictionary["chooseananimaltitle"] = (
		"Choose an animal",
		u"New Language"
		)
	dictionary["clientrefnolabel"] = (
		"Reference Number",
		u"New Language"
		)
	dictionary["toomanyresultsmessage"] = (
		"Your search produced too many results to display, please narrow down your search",
		u"New Language"
		)
	dictionary["idlelabel"] = (
		"Idle",
		u"New Language"
		)
	dictionary["connectinglabel"] = (
		"Connecting",
		u"New Language"
		)
	dictionary["connectedlabel"] = (
		"Connected",
		u"New Language"
		)
	dictionary["errorlabel"] = (
		"Error",
		u"New Language"
		)
	dictionary["usernamepassworderrormessage"] = (
		"Unsuccessful Login",
		u"New Language"
		)
	dictionary["successfulloginmessage"] = (
		"Successful Login",
		u"New Language"
		)
	dictionary["creatingevettefolder"] = (
		"Creating Evette folder",
		u"New Language"
		)
	dictionary["evettedatabasecreatedmessage"] = (
		"Created Evette database",
		u"New Language"
		)
	dictionary["errorcreatingdatabasemessage"] = (
		"Error creating Evette database",
		u"New Language"
		)
	dictionary["asmimportmenu"] = (
		("ASM Import", "Import an animal from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["errorobtainingownermessage"] = (
		"Unable to find owner",
		u"New Language"
		)
	dictionary["alreadyimportedmessage"] = (
		"This animal has already been imported. Would you like to view it?",
		u"New Language"
		)
	dictionary["addweighttooltip"] = (
		"Add Weight",
		u"New Language"
		)
	dictionary["editweightlabel"] = (
		"Edit Weight",
		u"New Language"
		)
	dictionary["adduserlabel"] = (
		"Add User",
		u"New Language"
		)
	dictionary["edituserlabel"] = (
		"Edit User",
		u"New Language"
		)
	dictionary["editreasonsmenu"] = (
		("Edit Reasons", "Edit common appointment reasons"),
		(u"New Language", u"New Language")
		)
	dictionary["lookupsreasonpagetitle"] = (
		"Appointment Reason Lookups",
		u"New Language"
		)
	dictionary["doubleclickforreasonstooltip"] = (
		"Double click for a choice of common appointment reasons",
		u"New Language"
		)
	dictionary["filemenu"] = (
		"File",
		u"New Language"
		)
	dictionary["fileexitmenu"] = (
		("Exit", "Exit Evette"),
		(u"New Language", u"New Language")
		)
	dictionary["fileclosewindowsmenu"] = (
		("Close All Panels", "Close all open panels"),
		(u"New Language", u"New Language")
		)
	dictionary["confirmcloseallwindowsmessage"] = (
		("Are you sure that you want to close all open panels? Any unsaved data will be lost."),
		(u"New Language")
		)
	dictionary["locationlabel"] = (
		"Location",
		u"New Language"
		)
	dictionary["editprocedurelabel"] = (
		"Edit Procedure",
		u"New Language"
		)
############################## 1.2.4 ###############################################
	dictionary["addlookuptooltip"] = (
		"Create a new lookup",
		u"New Language"
		)
	dictionary["malelabel"] = (
		"Male",
		u"New Language"
		)
	dictionary["femalelabel"] = (
		"Female",
		u"New Language"
		)
	dictionary["unknownlabel"] = (
		"Unknown",
		u"New Language"
		)
	dictionary["dayslabel"] = (
		"days",
		u"New Language"
		)
	dictionary["weekslabel"] = (
		"weeks",
		u"New Language"
		)
	dictionary["monthslabel"] = (
		"months",
		u"New Language"
		)
	dictionary["yearslabel"] = (
		"years",
		u"New Language"
		)
	dictionary["invaliddobtooltip"] = (
		"Invalid DOB",
		u"New Language"
		)
	dictionary["addkennelblocktooltip"] = (
		"Create a new kennel block",
		u"New Language"
		)
	dictionary["addkenneltooltip"] = (
		"Create a new kennel",
		u"New Language"
		)
############################## 1.2.5 ###############################################
	dictionary["asmclientimportmenu"] = (
		("ASM Client Import", "Import a client from ASM"),
		(u"New Language", u"New Language")
		)
	dictionary["chooseclientlabel"] = (
		"Choose client",
		u"New Language"
		)
	dictionary["datectrltooltip"] = (
		"Double click to choose from a calendar",
		u"New Language"
		)
	dictionary["choosedatetitle"] = (
		"Choose a date",
		u"New Language"
		)
	dictionary["editappointmentlabel"] = (
		"Edit Appointment",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["addvaccinationtooltip"] = (
		"Add Vaccination",
		u"New Language"
		)
	dictionary["printtooltip"] = (
		"Print",
		u"New Language"
		)
############################## 1.2.6 ###############################################
	dictionary["filealteredmessage"] = (
		"Another user has altered this file since you opened it. Please close this record and try again.",
		u"Seit dem letzten in anderer Nutzer hat die Datei geändert. Bitte schließen Sie den Datensatz und versuchen Sie es erneut."
		)
	dictionary["asmreflabel"] = (
		"ASM Ref",
		u"ASM Ref"
		)
	dictionary["deselectlabel"] = (
		"Deselect",
		u"Auswahl aufheben"
		)
	dictionary["createappointmentlabel"] = (
		"Create Appointment",
		u"Termin erstellen"
		)
	dictionary["multiplepanellabel"] = (
		"Allow multiple panels open",
		u"Das Öffnen mehrerer Panels erlauben"
		)
	dictionary["filealteredchoice"] = (
		"Another user has altered this file since you opened it. Would you like to force through your changes?",
		u"Seit dem letzten in anderer Nutzer hat die Datei geändert. Möchten Sie die Übernahme Ihrer Änderungen erzwingen?"
                )
	dictionary["latelabel"] = (
		"Late",
		u"Spät"
		)
	dictionary["minslabel"] = (#Abrreviation of minutes - it is advisable to keep this as short as possible.
		"mins",
		u"Min"
		)
	dictionary["microchiplabel"] = (
		"Microchip",
		u"Microchip"
		)
	dictionary["microchippedlabel"] = (
		"Microchip implanted",
		u"Microchip implantiert"
		)
	dictionary["costpricelabel"] = (
		"Cost Price",
		u"Kostenbetrag"
		)
	dictionary["viewvetnoteslabel"] = (
		"View Vet Notes",
		u"Notizen des Tierarztes anzeigen"
		)
	dictionary["appointmentsummarylistboxtooltip"] = (
		"Right click to view available vets\nDouble click to choose time slot",
		u"Rechts-Klicken um freie Tierärzte anzuzeigen\n Doppelklicken um den Zeitraum zu schließen"
		)
############################## 1.2.7 ###############################################
	dictionary["shopsalemenuitem"] = (
		"Shop Sale",
		u"New Language"
		)
	dictionary["shopitemstitle"] = (
		"Shop Items",
		u"New Language"
		)
	dictionary["basketlabel"] = (
		"Basket",
		u"New Language"
		)
	dictionary["putbacktooltip"] = (
		"Put back",
		u"New Language"
		)
	dictionary["addtobaskettooltip"] = (
		"Add to basket",
		u"New Language"
		)
	dictionary["clientmergetooltip"] = (
		"Merge another client into this one",
		u"New Language"
		)
	dictionary["clientsmergedmessage"] = (
		"Clients merged",
		u"New Language"
		)
	dictionary["addlabel"] = (
		"Add",
		u"New Language"
		)
	dictionary["subtractlabel"] = (
		"Subtract",
		u"New Language"
		)
	dictionary["editmarkupmenu"] = (
		("Define Markup Rules", "Define Markup Rules"),
		(u"New Language", u"New Language")
		)
	dictionary["multiplybylabel"] = (
		"Multiply by",
		u"New Language"
		)
	dictionary["roundtolabel"] = (
		"Round up to",
		u"New Language"
		)
	dictionary["costpriceentrytooltip"] = (
		"This value is not included in your settings, it is here simply to allow you to try your settings out on some real figures.",
		u"New Language"
		)
	dictionary["invalidpricemessage"] = (
		"Invalid Price!",
		u"New Language"
		)
	dictionary["priceinpenniestooltip"] = (
		"Please enter price in pennies eg. \"50\" to round to the nearest 50p, \"100\" to round to the nearest pound.",
		u"New Language"
		)
	dictionary["customerpricelabel"] = (
		"Customer Price",
		u"New Language"
		)
	dictionary["submitsettingstooltip"] = (
		"Submit settings",
		u"New Language"
		)
	dictionary["applymarkuptostocktooltip"] = (
		"Apply the current markup settings to all stock.",
		u"New Language"
		)
	dictionary["markupappliedtoallmessage"] = (
		"Markup applied to all prices",
		u"New Language"
		)
	dictionary["automarkupconfirmmessage"] = (
		"Continuing will alter all of your public prices, are you sure that you want to continue?",
		u"New Language"
		)
	dictionary["unitpricentrytooltip"] = (
		"Type \"a\" to autogenerate a price from markup rules.",
		u"New Language"
		)
	dictionary["costpricentrytooltip"] = (
		"Type \"c\" for help calculating the cost price.",
		u"New Language"
		)
	dictionary["calculatecostpricetitle"] = (
		"Calculate Cost Price",
		u"New Language"
		)
	dictionary["packpricelabel"] = (
		"Price per pack",
		u"New Language"
		)
	dictionary["unitsperpacklabel"] = (
		"Units per pack",
		u"New Language"
		)
############################## 1.2.8 ###############################################
	dictionary["phonenumbertooltip"] = (
		"CTRL + P to toggle public availability.",
		u"New Language"
		)
	dictionary["lostanimallabel"] = (
		"Lost Animal",
		u"New Language"
		)
	dictionary["foundanimallabel"] = (
		"Found Animal",
		u"New Language"
		)
	dictionary["lostandfoundmenu"] = (
		("Lost and Found", "View/Edit Lost and Found"),
		(u"New Language", u"New Language")
		)
	dictionary["lostlabel"] = (
		"Lost",
		u"New Language"
		)
	dictionary["foundlabel"] = (
		"Found",
		u"New Language"
		)
	dictionary["datelostlabel"] = (
		"Date Lost",
		u"New Language"
		)
	dictionary["datefoundlabel"] = (
		"Date Found",
		u"New Language"
		)
	dictionary["furlengthlabel"] = (
		"Fur Length",
		u"New Language"
		)
	dictionary["longlabel"] = (
		"Long",
		u"New Language"
		)
	dictionary["shortlabel"] = (
		"Short",
		u"New Language"
		)
	dictionary["fluffylabel"] = (
		"Fluffy",
		u"New Language"
		)
	dictionary["hairlesslabel"] = (
		"Hairless",
		u"New Language"
		)
	dictionary["sizelabel"] = (
		"Size",
		u"New Language"
		)
	dictionary["largelabel"] = (
		"Large",
		u"New Language"
		)
	dictionary["mediumlabel"] = (
		"Medium",
		u"New Language"
		)
	dictionary["smalllabel"] = (
		"Small",
		u"New Language"
		)
	dictionary["juvenilelabel"] = (
		"Juvenile",
		u"New Language"
		)
	dictionary["adultlabel"] = (
		"Adult",
		u"New Language"
		)
	dictionary["elderlylabel"] = (
		"Elderly",
		u"New Language"
		)
	dictionary["temperamentlabel"] = (
		"Temperament",
		u"New Language"
		)
	dictionary["friendlylabel"] = (
		"Friendly",
		u"New Language"
		)
	dictionary["timidlabel"] = (
		"Timid",
		u"New Language"
		)
	dictionary["aggressivelabel"] = (
		"Aggressive",
		u"New Language"
		)
	dictionary["collarlabel"] = (
		"Collar",
		u"New Language"
		)
	dictionary["collardescriptiontooltip"] = (
		"Collar description",
		u"New Language"
		)
	dictionary["arealabel"] = (
		"Area",
		u"New Language"
		)
	dictionary["areatooltip"] = (
		"Please put in likely areas by postcode if possible as well as the city/state, separated by spaces.",
		u"New Language"
		)
	dictionary["datecompletelabel"] = (
		"Date complete",
		u"New Language"
		)
	dictionary["savetooltip"] = (
		"Save",
		u"New Language"
		)
	dictionary["contacttooltip"] = (
		"Contact",
		u"New Language"
		)
	dictionary["completelabel"] = (
		"Complete",
		u"New Language"
		)
	dictionary["idlabel"] = (
		"ID",
		u"New Language"
		)
	dictionary["rightclickformenutooltip"] = (
		"Right click for available options.",
		u"New Language"
		)
	dictionary["lostandfoundsearchtooltip"] = (
		"Search for a match",
		u"New Language"
		)
	dictionary["searchuptolabel"] = (
		"Search ceiling",
		u"New Language"
		)
	dictionary["searchfromlabel"] = (
		"Search floor",
		u"New Language"
		)
	dictionary["alreadyonlostandfoundmessage"] = (
		"This animal is already on the lost and found!",
		u"New Language"
		)
	dictionary["includecompletelabel"] = (
		"Include complete?",
		u"New Language"
		)
	dictionary["closelabel"] = (
		"Close",
		u"New Language"
		)
	dictionary["scorelabel"] = (
		"Score",
		u"New Language"
		)
	dictionary["lostandfoundsearchresultspagetitle"] = (
		"Lost and Found Search Results",
		u"New Language"
		)
	dictionary["systemlabel"] = (
		"System",
		u"New Language"
		)
	dictionary["versionlabel"] = (
		"Version",
		u"New Language"
		)
############################## 1.3 ###############################################
	dictionary["addlostmenu"] = (
		("Add Lost", "Add a lost animal"),
		(u"New Language", u"New Language")
		)
	dictionary["addfoundmenu"] = (
		("Add Found", "Add a found animal"),
		(u"New Language", u"New Language")
		)
	dictionary["alllabel"] = (
		"All",
		u"New Language"
		)
	dictionary["refreshlabel"] = (
		"Refresh",
		u"New Language"
		)
	dictionary["filteranimalslabel"] = (
		"Filter Animals",
		u"New Language"
		)
	dictionary["markaspaidlabel"] = (
		"Mark as paid?",
		u"New Language"
		)
############################## 1.3.1 ###############################################
	dictionary["asmshelterlabel"] = (
		"ASM Shelter",
		u"New Language"
		)
	dictionary["asmsheltertooltip"] = (
		"If you use the Animal Shelter Manager system you can mark a client as \"The Shelter\" allowing you to import animal records from ASM who do not have an owner.",
		u"New Language"
		)
	dictionary["appointmentrefreshlabel"] = (
		"Appointment Refresh Interval",
		u"New Language"
		)
############################## 1.3.2 ###############################################
	dictionary["asmvaccinationlabel"] = (
		"ASM Vaccination",
		u"New Language"
		)
	dictionary["asmvaccinationtooltip"] = (
		"Choose which ASM vaccine you would like Evette to use when updating animal records.",
		u"New Language"
		)
	dictionary["asmerrormessage"] = (
		"Unable to update ASM record!",
		u"New Language"
		)
	dictionary["asmsynctooltip"] = (
		"Sync with ASM record",
		u"New Language"
		)
	dictionary["fieldlabel"] = (
		"Field",
		u"New Language"
		)
	dictionary["asmsyncbuttontooltip"] = (
		"Sync this field on Evette and ASM records",
		u"New Language"
		)
	dictionary["synctoasmlabel"] = (
		"Sync to ASM",
		u"New Language"
		)
	dictionary["synctoevettelabel"] = (
		"Sync to Evette",
		u"New Language"
		)
	dictionary["asmconnectionerrormessage"] = (
		"Unable to connect to ASM.",
		u"New Language"
		)
	dictionary["asmdeathreasonlabel"] = (
		"Record updated via ASM.",
		u"New Language"
		)
	dictionary["evettedeathreasonlabel"] = (
		"Record updated via Evette.",
		u"New Language"
		)
	dictionary["importnewasmownermenuitem"] = (
		"Import new ASM owner",
		u"New Language"
		)
	dictionary["updateownermenuitem"] = (
		"Update current owner",
		u"New Language"
		)
	dictionary["1.3.2updatemessage"] = (
		"Note: when you run the evette client following this upgrade you will need to re-input your database settings.",
		u"New Language"
		)
        dictionary["tabbetweenentriestooltip"] = (
		"You can switch between the user and password entries with the TAB key.",
		u"New Language"
		)
	dictionary["dischargelabel"] = (
		"Discharge",
		u"New Language"
		)
	dictionary["overnightstaylabel"] = (
		"Overnight Stay",
		u"New Language"
		)
	dictionary["animalstayedmessage"] = (
		"This animal has stayed overnight, creating a new vet form.",
		u"New Language"
		)
	dictionary["prescriptionfeelabel"] = (
		"Prescription Fee",
		u"New Language"
		)
	dictionary["ontimelabel"] = (
		"On time",
		u"New Language"
		)
	dictionary["dnalabel"] = (
		"Did not arrive",
		u"New Language"
		)
	dictionary["viewlabel"] = (
		"View",
		u"New Language"
		)
	dictionary["renamelabel"] = (
		"Rename",
		u"New Language"
		)
	dictionary["filterlabel"] = (
		"Filter",
		u"New Language"
		)
	dictionary["programbrowsertooltip"] = (
		"Browse to find an appropriate program.",
		u"New Language"
		)
	dictionary["agelabel"] = (
		"Age",
		u"New Language"
		)
	dictionary["batchbreakdownlabel"] = (
		"Batch No Breakdown",
		u"New Language"
		)
	dictionary["returntoshelterlabel"] = (
		"Return to shelter",
		u"New Language"
		)
	dictionary["possibleduplicateownermessage"] = (
		"This owner may already be known to the system. Would you like to view the list of similar clients?",
		u"New Language"
		)
	dictionary["asmimportlabel"] = (
		"Imported from ASM",
		u"New Language"
		)
	
	return dictionary
